### ISSUE TITLE
404 for dpd.js

### ISSUE THREAD

**Issue by teknotica** [deployd/deployd#104]
Hello!

I'm testing Deployd and attempting to use the data I just created using the Dashboard. 

I can access and see the data by http but I would like to use the JavaScript methods instead. I added then the dpd.js into my index.html (or any other page) I got a 404 error all the time.

<script type="text/javascript" src="/dpd.js"></script>

Does this file get generated somewhere? I can't see it.

Thanks in advance!

**Comment by wolfdogg** [comment]
incendintally replacing the script include on your index.html line from "/dpd.js" to "http://localhost:2403/dpd.js"  solved my issue.  I was including the site from my dev wildcard domains (dev.ast_deployd.ld.pvt) so it couldnt find that file only, as if it didnt have permissions for it to be generated.  changing to this saved my ass `<script type="text/javascript" src="localhost:2403/dpd.js">`
