### ISSUE TITLE
Store Files !?

### ISSUE THREAD

**Issue by softdap** [deployd/deployd#106]
Will be great if you will add file storing !

**Comment by NicolasRitouet** [comment]
There's also a module for that:
https://github.com/NicolasRitouet/dpd-fileupload/

Given the current resources we have, I don't think we'll be able to add this to the core soon.

**Comment by ericfong** [comment]
Just publish the new version of dpd-s3 (https://www.npmjs.com/package/dpd-s3)

I think file upload should not be put into the core.

**Comment by NicolasRitouet** [comment]
I close this since we have many modules for this and it won't be in the core.
