### ISSUE TITLE
Add support for the operator $addToSet

### ISSUE THREAD

**Issue by clooket** [deployd/deployd#140]
Add support for the operator $addToSet, MongoDB like (http://docs.mongodb.org/manual/reference/operator/addToSet/)

Suppose you want to add some tags in a tag list without duplicates, $addToSet is the fastest way, e.g.:
 {"$addToSet":{myFieldTagsArray:{"$each":["d","a","b","c"]}}} 

You can probably replace the operator $addToSet by defining a custom logic that allows the modification of the data before the POST / PUT.
Thanks,
Denis

**Comment by NicolasRitouet** [comment]
Close since done with #418
