### ISSUE TITLE
emit() with query to multiple connected clients for a single user

### ISSUE THREAD

**Issue by justinwalsh** [deployd/deployd#141]
When using emit and the follow syntax:

emit(dpd.users, {'id': {$in: this.users}}, 'something:happened', this);

The event is only emitted to last connected client by each of the users in the this.users array. For example, if there are two browsers windows open with the same user logged into both, only the browser that is connected last will receive events for that user.

If the query on the emit statement is omitted, then the event is sent to all browsers as expected, but no longer filtered to a group of users.

**Comment by shaggybb** [comment]
There is any plan to solve it?

**Comment by shaggybb** [comment]
This issue has been resolved in 0.8.4 version, hasn't it?

**Comment by andreialecu** [comment]
Yep.
