### ISSUE TITLE
User collection event authorization

### ISSUE THREAD

**Issue by tUrG0n** [deployd/deployd#145]
I noticed that with the default user collections, anyone can perform the following actions:

- ``dpd.users.get``
- ``dpd.users.del``
- ``dpd.users.put``

You just get the id's from the ``get`` command and use it to ``put`` or ``delete``.

I'm wondering, is that something good? Yet i want to ``get`` all users, but why do you tell me their ``id``?

Also, it doesn't make sense to have anyone but ``me``,  ``put`` or ``delete`` ``me``, right?

## Suggestion

What I suggest adding the following as defaults in a user collection:

### GET event
```
// Example: On Get /users
// Hide properties unless this is the current user
if (!isMe(this.id)) {
    hide("id");
}
```

### PUT and DELETE events
```
// Only allow the user to delete his account
if (!isMe(this.id)) {
  cancel("Not allowed!", 401);
}
```

What say you? :)

**Comment by ericfong** [comment]
Shall we put them into examples of deployd events?  into docs repo? or we have an example folder?
