### ISSUE TITLE
.me() return value

### ISSUE THREAD

**Issue by scharissis** [deployd/deployd#146]
Hi,

According to the docs, dpd.users.me() should return null if there is no current user: http://docs.deployd.com/docs/users/authenticating-users.md#s-Getting%20the%20current%20user

But, I find that it doesn't. Instead, I have to check if (user == "").

I am using it like so:
```
dpd.users.me(function(user, error) {
    ...
});
```

**Comment by andreialecu** [comment]
Just use `if (user)`.
