### ISSUE TITLE
Using email for authentification instead of username

### ISSUE THREAD

**Issue by gabrielstuff** [deployd/deployd#150]
Is there any ways to make username not mandatory and use email for login ?

This would be nice to simply signup process.

Thank you,

:+1:

**Comment by NicolasRitouet** [comment]
Thanks to @simpleTechs , we have a nice solution to use passport.
I close this ticket.
If you need more and have specific issues for that, don't hesitate to reopen it.

**Comment by epiphanydigital** [comment]
@simpleTechs, is there a way to retrieve more that the displayName and id from Facebook?  Sorry to post here, but I don't see a way to post on the github or bb repo.
