### ISSUE TITLE
User looses session when 2 dpd instances are running

### ISSUE THREAD

**Issue by tUrG0n** [deployd/deployd#154]
I have 2 dpd instances, each connected to a different database and listening to different ports.

- db1 allows users to login.
- db2 logs actions performed by the user.
- db1 is accesses via dpd on the client side.
- db2 is accesses by my express server via ``HTTP`` 

Here's what happens:
- User logs in  (via the first dpd).
- I then perform a ``GET`` request on the second dpd machine.
- Finally, the user refreshes the page, only to find out that he needs to sign-in again.

What is going wrong in here??

The case is kind of hard and complex. I hope it makes sense.
Thank you for any help you can provide!

**Comment by andreialecu** [comment]
If you still have this issue please reopen.
