### ISSUE TITLE
deployd ember-data mappings issue

### ISSUE THREAD

**Issue by joshua1** [deployd/deployd#156]
Deployd returns json data for a GET request as for e.g 
[{"firstName":"javi","lastName":"garcia","age":56,"isMale":true,"id":"d873ed0deedb3a8a"}]

from a users collection. ember data expects a
["users":{"firstName":"javi","lastName":"garcia","age":56,"isMale":true,"id":"d873ed0deedb3a8a"}],
otherwise it throws this error "Your server returned a hash with the key '' but you have no mapping for it". Is there a way to format the json output from deployd? again is there an ember-data adapter for deployd.you have shown how this works out of the box for angular and backbone, but nothing for ember-data

**Comment by ericfong** [comment]
I guess. deployd core won't directly hook to angular or ember or react.

Fill free to create dpd-module for that.

I close this issue first.
