### ISSUE TITLE
dpd.js not working behind SSL proxy

### ISSUE THREAD

**Issue by cmil** [deployd/deployd#162]
In [line 43 of lib/resources/client-lib.js](https://github.com/deployd/deployd/blob/master/lib/resources/client-lib.js#L43) the base URL dpd uses for XMLHTTP requests is set to value with a hardcoded http scheme. Apparently this would make it impossible to use client-side dpd to access a deployd server hosted behind an SSL proxy.

**Comment by ericfong** [comment]
I think this problem have been fixed.
I am using nginx + ssl + deployd
Feel free to ask me questions about that

I close this first.
