### ISSUE TITLE
server shuts down

### ISSUE THREAD

**Issue by davidhq** [deployd/deployd#177]
Hi,

I installed deployd on my Debian Squeeze VPS via npm and when I start it with dpd and then access the dashboard via browser, the instance shuts down... it happens every time. My VPS is at Rackspace so they should be reliable. It is something in the deployd server that causes the shutoff.. I don't see anything useful in logs though :(

Another question: I could access the dashboard without entering my generated key in the browser - how come?

thank you!
david

**Comment by ericfong** [comment]
Any console log?

**Comment by NicolasRitouet** [comment]
Since it's a really old issue (almost 2 years), I'll close the ticket.
If you still have the issue, please, reopen it with additional details.
