### ISSUE TITLE
Schema deep question

### ISSUE THREAD

**Issue by CodersBrothers** [deployd/deployd#187]
I have a schema for forum, but i have a question with deep organization:
    
    - id
    - createdAt
    - updatedAt
    - userId
    - title
    - titleUrl
    -...

Or:

    - id
    - createdAt
    - updatedAt
    - userId
    - title
         - normal
         - url
    -...

My question is: What is better? 
I need search by title.
I have the same problem with "message" field:

     - messageOriginal
     - messageFormated

Thanks.

**Comment by ericfong** [comment]
Let's continue this discussion on gitter or google group or stack-overflow.

Let's close this first.
