### ISSUE TITLE
Missing file .latestversion

### ISSUE THREAD

**Issue by giodamelio** [deployd/deployd#190]
Every time I run the dpd command I get the message
```fs: missing callback Error: EACCES, open '/usr/local/lib/node_modules/deployd/.latestversion'```

I am running version 0.6.10 with node 0.10.6.

**Comment by NicolasRitouet** [comment]
Is the problem still appearing on 0.8.0?
Since it's an issue from an old version, I'll close it, but feel free to comment or reopen it if it's still happening. (with additional details: OS, deployd, node, npm and how you start your app: with Deployd CLI or a node script?).

Thanks.

**Comment by mgundogdu38** [comment]
i have same problem. i Run a Command as Administrator from the Windows 7. problem solved

**Comment by RSC1** [comment]
I encountered the same problem after my Windows 8 machine had crashed. Running the command from a command prompt running with administrator privileges as mgundogdu38 suggested resolved the problem for me, as well.

**Comment by wolfdogg** [comment]
happened to me today, stikingly similar timing to when i was messing with callbacks in angular, and having problems with jsonp.  
this is  a win7 machine, dos ran from user, not admin, via mapped net drive to linux samba share.  so `w:` `cd site` `ast` then i get 'fs: missing callback Error: EPERM, open `C:\Program Files (x86)\Deployd\node_modules\deployd\.katestversion`'

**Comment by wolfdogg** [comment]
**RESOLVED**  i drafted a solution that touches on this today, please check this answer http://stackoverflow.com/questions/31826689/node-and-or-npm-issue
