### ISSUE TITLE
Unable to find access to the dashboard

### ISSUE THREAD

**Issue by Ujilon** [deployd/deployd#193]
Hi guys,

I sucessfully installed deployd on my dedicated server (or i think so), but after the "dpd" command in my deployd app's directory, without errors or warnings, i can't find access to the dashboard. htop can't find any "dpd" binary.

http://my-domain.com:2403 or http://my-domain.com:2403/dashboard don't work.

Can anyone help to find why ?
Thank you.

**Comment by shawneric** [comment]
the first link is broken, please fix.
