### ISSUE TITLE
Wont install on OS X 10.8.3

### ISSUE THREAD

**Issue by anthonycastelli** [deployd/deployd#194]
I've spent a few hours trying to install Deployd on 10.8.3 but have had no luck. The link to the Installer Package is broken so I tried using npm to install it as well as manually via the source. Nothing seems to work, it completes, doesn't appear to be any issues other than some warnings about links to packages, but nothing indicating it fails. When I run 'dpd -V' it says the command isn't found. I've added the location to my .profile file and no luck with that. I discovered that it doesnt even get installed on my system, when I try and cd into the directory where its supposed to be installed, there is nothing there. Here is my installation output from terminal if anyone wants to take a look at it. 

http://cl.ly/PEds

I'm not a backend developer, so I've never played with Node or MongoDB. I've used Ruby Rails and MySQL in some really basic learning projects. I'd definitely like to see if I can get this running. 

Thanks

Update: I finally was able to get it installed but im now having issues starting an app. I run the command
$ dpd create MyApp -d
After that, it just hangs at "starting deployd v0.6.11..."

**Comment by oleole90** [comment]
@slively thanks man. -d did the trick.
[Win8 64bit]

**Comment by vlasix** [comment]
chmod 666 /usr/local/lib/node_modules/deployd/.latestversion resolves this issue.
