### ISSUE TITLE
emit() with query

### ISSUE THREAD

**Issue by hshsiao** [deployd/deployd#200]
I am not sure how to reopen an issue, but the bug described in
https://github.com/deployd/deployd/issues/93

is still there.

I cannot use emit(dpd.users,query,"something",this);

I think there is something wrong with this function

session.js

````javascript
Session.prototype.save = function(fn) {
  var session = this
    , data = this.data
    , query = {id: data.id};

  session.remove(function (err) {
    if(err) return fn(err);
    session.store.insert(data, function (err, res) {
      fn(err, res);
    });
  });
  return this;
};
````
which calls

````javascript
delete session.store.socketIndex[this.data.id];
````

resulting the socketIndex[sid] with undefined value

**Comment by andreialecu** [comment]
This should've been fixed in recent versions of deployd.
