### ISSUE TITLE
Using  deployd in existing Express application 

### ISSUE THREAD

**Issue by Shadowfaxenator** [deployd/deployd#224]
Hi, my question is: How to integrate deployd in existing express application?
For example:
```javascript
app.get("/api/v1/",function(req, res){
// allow http://domain.com/api/v1/resource be managed by deployed
});
```
or using a subdomain  http://api.domain.com

Additional question is using HTTPS instead of HTTP as most REST api require.

**Comment by NicolasRitouet** [comment]
The latest version of deployd (0.8.0) can be used as express middleware:
http://docs.deployd.com/docs/server/work-with-express.html
