### ISSUE TITLE
AngularJS $resource and extra & at the end of query

### ISSUE THREAD

**Issue by maciejjankowski** [deployd/deployd#235]
angularJS does not like your way of not using named arguments like this:

$resource.query(JSON.stringify({"branchId":{"$exists":"true"}}))

b/c it results in:
?0={"branchId":{"$exists":"true"}}
and deployd doesnt like that.

Is there a way to use it with $resource or should I rewrite my module to use $http?

-----------------------
UPDATE:
Okay, I figured out how to pass it:
   var ProductRes = $resource('/products/:productId', 
		{ 'productId':'@productId','queryStr':'@query' },
		{ 'q':{method:'GET', isArray:true, url:'/products?:queryStr'} }
	);

But now another issue: Angular attached extra & at the end of query string, right after queryStr - how can I strip it?

**Comment by NicolasRitouet** [comment]
It looks like it's more an angular question than a deployd question.
I suggest you ask the question on stackoverflow, you'll have more answers.
I close the ticket since it's really old.
