### ISSUE TITLE
Emit to certain user

### ISSUE THREAD

**Issue by javieret** [deployd/deployd#238]
Im uploading data from with an adruino and I would like the user to be notified in real time in the webpage.

I have my emit function but it display the data to everyone not only to that certain logged user. 

This is on POST
if (me.id) {
    this.creator = me.id;
    emit(dpd.users, {creator: this.creator}, 'proyecto', this); 
}

and in my client side I have this. 
    dpd.on('proyecto', function(post) {
      alert("hola");
    });

But the thing is that the alert pop up on every connected user. Not only to the one that posted.

**Comment by NicolasRitouet** [comment]
I close this ticket since it's really old, if the problem still exists, feel free to reopen it with additional details.
Thanks.
