### ISSUE TITLE
dpd get var

### ISSUE THREAD

**Issue by zimt28** [deployd/deployd#242]
This might not be the best place to put it but I didn't find any better ..
Any idea on how to get the var out of the closure? dpd doesn't return anything and the loop keeps running forever.

    chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZ';
    random = '';

    while ( ! this.short) {
        for (i = 0; i < 5; i++) {
            randomNumber = Math.floor(Math.random() * chars.length);
            random += chars.substring(randomNumber, randomNumber + 1);
        }

        dpd.links.get({short: random}, function(res, err) {
            if (err)
                cancel('Error', 500);

            if ( ! res.length)
                this.short = random;
        }); 
    }

**Comment by NicolasRitouet** [comment]
Try to post your question on stackoverflow, you'll get more answers.
I also hope that the problem was solved since you asked (2 years ago), so I'll close the ticket.
Reopen it if necessary.
