### ISSUE TITLE
Configuring deployd application to serve with nginx instead

### ISSUE THREAD

**Issue by rngadam** [deployd/deployd#246]
Trying to use nginx reverse proxy to put the API and the web application that uses it under the same URL 

Extract from my configuration:

```
upstream backend {
        server localhost:3000;
}

server {
        location ~ ^/dashboard/js/ {
                root APP_PATH/node_modules/deployd/lib/resources/;
        }

        location ~ ^/dashboard/stylesheets/ {
                root APP_PATH/node_modules/deployd/lib/resources/;
        }

        location ~ ^/dashboard(.*) {
                proxy_pass http://backend/dashboard$1$is_args$args;
        }

        location ~ ^/api/(.*) {
                proxy_pass http://backend/$1$is_args$args;
        }

```

Problems:

* having trouble to server dpd.js (the location directive is serving from another root) - probably something I don't understand about nginx directives:

```
        location /dpd.js {
                proxy_pass http://backend/dpd.js;
        }
```

* dpd.js fails with Origin PUBLIC_DOMAIN_NAME is not allowed by Access-Control-Allow-Origin
* would really prefer if it was using relative locations
* should there be a way to generate a static "dist/" directory that could be published (with copy of the assets and the dpd.js)?

All this makes me believe that deployd was never tested as a upstream server behind nginx. Am I wrong? 

Documentation (such as http://docs.deployd.com/docs/server/your-server.md) certainly doesn't mention this.

**Comment by ericfong** [comment]
I believe this problem fixed.
I am using nginx in front of deployd too.
Feel free to ask me questions about the config problems.

I close this first.
