### ISSUE TITLE
Deployd + Apache2 + mod proxy

### ISSUE THREAD

**Issue by heldrida** [deployd/deployd#247]
Hi,

I'm using Deployd alongside with Apache2.

When I try to access my vhost without specifying the port
the "Dashboard" loads, but only the top navbar and I can read in the console.log:

TypeError: res is not an object
[Break On This Error]    

var types = Object.keys(res).reduce(function(prevValue, curValue) {

sidebar.js (line 27)
TypeError: res is null
[Break On This Error]    

resources = res.sort(function(a, b) {

If I try to access my vhost specifying the port, let's say :5000 it works fine. For example: www.foo.com:5000/dashboard but www.foo.com/dashboard doesn't work.

I wonder why isn't this working ?

<VirtualHost *:80>
        ServerAdmin user@foo.com
        ServerName fooserver

        DocumentRoot /var/www/deployd/foo

        ProxyRequests off

        ProxyPass / http://foo.com:5000/
        ProxyPassReverse / http://foo.com:5000/
</VirtualHost>

This is my production.js

// production.js
var deployd = require('deployd');

var server = deployd({
  port: 5000,
  env: 'production',
  db: {
        host: 'localhost',
        port: 27017,
        name: 'comments',
        credentials: {
                username: 'test',
                password: 'test'
        }
  }
});

server.listen();

server.on('listening', function() {
  console.log("Server is listening");
});

server.on('error', function(err) {
  console.error(err);
  process.nextTick(function() { // Give the server a chance to return an error
    process.exit();
  });
});

Thanks for looking,
H'

**Comment by NicolasRitouet** [comment]
hi @heldrida 
Do you still have this issue?
Were you able to solve it?
Since it's really old, I'll close the ticket, but feel free to reopen it if you need help on this.
