### ISSUE TITLE
emit() from within an event broken after user login!

### ISSUE THREAD

**Issue by freakabcd** [deployd/deployd#257]
I have tried this with both 0.6.10 and master. Both produce the same result.

Create a new empty app
`dpd create myapp`

Create two collections:
* `/users` User collection
* `/objects` collection

Create a user `user` with password `password` in the `users` collection. Add a string field called `name` in the `objects` collection. Last thing for the setup is
`emit('object:added', this);`
in On Post (or really `resources/objects/post.js`)

Navigate to `http://localhost:2403` and open firebug/web_console. Add a callback for the emit event:
```
dpd.on('object:added', function(item) {
    console.log('object added');
    console.log(item);
});
```

Add a new object and notice the `object:added` callback fire
```javascript
dpd.objects.post({
    name: 'chair'
    }, function() {
});
````

Now log in as `user` and add another object
```javascript
dpd.users.login({
    username: 'user',
    password: 'password'
    }, function(res, err) {
        dpd.objects.post({
            name: 'table'
        }, function() {
    });
});
```
and notice that it does not trigger the `object:added` callback. More importantly, your callback will never get fired even if you keep adding new objects!

Refresh the page with Ctrl-R or F5 (user is still logged in). If you now add the `objects:added` callback (necessary because the browser removed it on page refresh), adding objects triggers the callback!

I added a REPL on port 5000 as `repl.js` within a node_modules subdir under myapp, i.e. `myapp/node_modules/repl.js`
```javascript
var net = require('net');
var repl = require('repl');

net.createServer(function(socket) {
    var r = repl.start({
        prompt: 'TCP> ',
        input: socket,
        output: socket,
        //useGlobal: true,
        terminal: true
    });

    r.on('exit', function() {
        socket.end();
    });

    r.context.socket = socket;
}).listen(5000);
```
also also made 1 other change in `lib/server.js` about line 75 to expose the sessionStore within the server.
```
// persist sessions ...
var sessionStore = ...

this.sessionStore = sessionStore;
```

Now I can `telnet localhost 5000` and type `process.server.sessionStore` to see what is going on with the sessionStore. Here is what I see:

* User loads main page `http://localhost:2403`. `socketQueue._events` is empty and `socketIndex` has an object keyed to the sessionid. `emit`s work fine
* User logs in successfully. `socketQueue._events` has an object keyed to the previously seen sessionid and most importantly `socketIndex` is empty! `emit`s do *not* work
* User refreshes the page. `socketQueue._events` and `socketIndex` are as before the user logged in. `emit`s work properly.

**Comment by andreialecu** [comment]
Closing this old issue, this entire code was rewritten in later versions.
