### ISSUE TITLE
CORS with AngularJS and cookies

### ISSUE THREAD

**Issue by fgodino** [deployd/deployd#269]
Hi, I am developing an app that uses AngularJs and Deployd in the server-side. They are not in the same host so I have to deal with CORS. The problem comes when I do login and then I try to access [resource]/me. These are the request and response headers.

Request:

GET /discouser/me HTTP/1.1
Host: localhost:2403
Connection: keep-alive
Cache-Control: no-cache
Pragma: no-cache
Accept: application/json, text/plain, */*
Origin: http://localhost:9000
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.65 Safari/537.36
Referer: http://localhost:9000/index.html
Accept-Encoding: gzip,deflate,sdch
Accept-Language: es-ES,es;q=0.8
Cookie: sid=7fafc00900496d738cf3cec599b165083f31cbf58df5e7bfa509bbb1db89d989942fee3abb69020417ec3f0a2bb872d5f369537cc15e6a1e49c0a812c160289d

Response:

HTTP/1.1 204 No Content
Access-Control-Allow-Origin: http://localhost:9000
Access-Control-Allow-Credentials: true
set-cookie: sid=7fafc00900496d738cf3cec599b165083f31cbf58df5e7bfa509bbb1db89d989942fee3abb69020417ec3f0a2bb872d5f369537cc15e6a1e49c0a812c160289d; path=/; httponly
Date: Thu, 19 Sep 2013 19:47:42 GMT
Connection: keep-alive

am I doing something wrong?? Thank you

**Comment by woodpig07** [comment]
I got the same 204 problem when I only include {withCredentials: true} for the GET request to /me but not the POST request to /users/login. Configure that flag for both GET and POST would resolve it.

**Comment by ericfong** [comment]
Same as @woodpig07, I use withCredentials everywhere. 

I will close this issue as it is CORS problem to me instead of dpd problem. Feel free to reopen it.
