### ISSUE TITLE
Array property returned as list in event 'previous'

### ISSUE THREAD

**Issue by richardwardza** [deployd/deployd#273]
Using deployd v0.6.10
On my user collection I have added a property "list" of type Array.
I have added console.log(this) and console.log(previous) to the onPut event.

I noticed that it then returns the list property in a different format, I would have thought it would be an array both times.

The console output:

*****this
{ 
  email: 'david@gmail.com',
  firstname: 'David',
  list: 
   [ { name: '111' },
     { name: '222' },
     { name: '333' },
     { name: 'test' },
     { name: 'test2' } 
   ],
  id: 'f17240f2e8730954' 
}

*****previous
{ 
  email: 'david@gmail.com',
  firstname: 'David',
  list: 
   { '0': { name: '111' },
     '1': { name: '222' },
     '2': { name: '333' },
     '3': { name: 'test' },
     '4': { name: 'test2' } 
   },
  id: 'f17240f2e8730954' 
}

**Comment by andreialecu** [comment]
If you still have this issue please reopen.
