### ISSUE TITLE
difference between put $push and put in event

### ISSUE THREAD

**Issue by richardwardza** [deployd/deployd#274]
Using deployd v0.6.10.

I have an inconsistency in the 'previous' data when using the PUT event on my user collection.

A record in my user collection looks like:
{
  email: 'david@gmail.com',
  firstname: 'David',
  list: 
   [ { name: '111' },
     { name: '222' },
     { name: '333' },
     { name: 'test' }
],
  id: 'f17240f2e8730954' 
}

My put event has:
console.log(this);
console.log(previous);
cancel();

When I do try add "test2" to the list using:
dpd.user.put("f17240f2e8730954", {"list":[{"name":"111"}, {"name":"222"}, {"name":"333"}, {"name":"test"}, {"name":"test2"}]}, function(result, err) {...

Then the "previous"output has the following:
{ 
  email: 'david@gmail.com',
  firstname: 'David',
  list: 
   { '0': { name: '111' },
     '1': { name: '222' },
     '2': { name: '333' },
     '3': { name: 'test' } 
},
  id: 'f17240f2e8730954' 
}

Which is correct.

When I try add "test2" using the put $push method: 
dpd.user.put("f17240f2e8730954", {"list": {$push : {"name":"test2"}}}, function(result, err) {...

Then the "previous" output has the following:
{
  email: 'david@gmail.com',
  firstname: 'David',
  list: 
   { '0': { name: '111' },
     '1': { name: '222' },
     '2': { name: '333' },
     '3': { name: 'test' },
     '4': { name: 'test2' } 
},
  id: 'f17240f2e8730954' 
}

With test2 in the list.
Is that how it should be?

**Comment by andreialecu** [comment]
This should've been fixed in recent versions. Please reopen if you still see this issue.
