### ISSUE TITLE
/<user collection>/logout returning text/html

### ISSUE THREAD

**Issue by jfla** [deployd/deployd#280]
When I send a POST request to the logout url, even with the Accept header set to application/json, I get back an empty response, as expected, but with a Content-Type of text/html. This is a problem because I'm using Restkit and it throws an error if the content type is different, even if there is no content. I would think that instead of the 200 response code that is returned, there should be a 204 (No Content) code, as there obviously is no content.

Response headers when tested with Poster in Chrome:
Access-Control-Allow-Credentials →true
Access-Control-Allow-Origin →chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm
Connection →keep-alive
Content-Type →text/html; charset=utf-8
Date →Fri, 25 Oct 2013 22:11:12 GMT
Transfer-Encoding →chunked

**Comment by andreialecu** [comment]
This shouldn't be a problem in latest versions.
