### ISSUE TITLE
unique _id as a 10 character alpha-numeric hex for Parse.com migration?

### ISSUE THREAD

**Issue by kimballfrank** [deployd/deployd#292]
Maybe I'm barking up the wrong tree, but I'm very keen on seeing how hard it would be to migrate an existing app from Parse.com to a self-hosted deployd instance. 

One thing out of the shoot is migrating data. Parse unique "objectId" that looks like: "yyuTxK9VDb". Deployd won't accept that string into the "id" field.

**Comment by ericfong** [comment]
Please try to use another field to store the parse.com id
And setup a unique index in mongodb.
