### ISSUE TITLE
Error loading resources, undefined

### ISSUE THREAD

**Issue by jeffbcross** [deployd/deployd#30]
When trying to run my deployd app (deployd.com) with deploy 0.6.0, I get "Error loading resources" and the next line is undefined. The program terminates without starting the app.

**Comment by alobintechnologies** [comment]
We got the same issue "Error loading resources" and the next line is undefined.

We solved this by adding "type": "Collection", inside <project folder>/resources/<collection-name>/config.json

We faced "cannot find type property undefined" in browser. This happens while renaming a collection property name. While updating config.json, deployd is missing "type": "Collection" property in that file.

**Comment by ericfong** [comment]
Which version are you using? 

Personally, don't know how to reproduce this bug, as I don't know the ENV of your setup.

"This happened to be a missing node module."
You may solve it by "npm install"

**Comment by alobintechnologies** [comment]
Currently I'm using deploy 0.6.1. We solved our issue! Anyway thanks

**Comment by daslicht** [comment]
Same issue here, after a while , for some unclear reason , one property folder got renamed to *t* and the content is deleted, which results in:
```
Expected file: resources/t/config.json
```

see: https://github.com/deployd/deployd/issues/681

**Comment by pkosenko** [comment]
And here's what I am getting with version 0.8.7:

dpd > resources
resources
TypeError: Cannot read property 'type' of undefined
    at c:\Users\[USER]\AppData\Roaming\npm\node_modules\deployd\lib\client\repl.js:54:17
    at Array.forEach (native)
    at Object.commands.resources (c:\Users\[USER]\AppData\Roaming\npm\node_modules\deployd\lib\client\repl.js:53:40)
    at tryCommand (c:\Users\[USER]\AppData\Roaming\npm\node_modules\deployd\lib\client\repl.js:81:23)
    at REPLServer.replEval (c:\Users\[USER]\AppData\Roaming\npm\node_modules\deployd\lib\client\repl.js:23:5)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
    at ReadStream.emit (events.js:110:17)
    at readline.js:1175:14
    at Array.forEach (native)
dpd > 

And here is the "resources" command:

resources: function () {
	server.resources && server.resources.forEach(function (r) {
		if(r.settings.type) console.log('\t' + r.settings.path, '(' + r.settings.type + ')');
	});
},

**Comment by daslicht** [comment]
Is that meanwhile fixed?

**Comment by travisstaloch** [comment]
I am having the same problem.  Is the "resources" folder special?  I am serving static contents from this folder. I tried creating a config.json file with` { "type": "Collection"}` and that seemed to work.  But now i get `Error: Expected file: resources\css\config.json`  Do I need to put the same config.json file in all of the subdirectories of resources?  I must be doing something wrong here.

**Comment by travisstaloch** [comment]
I worked around the errors I was getting and the need for all the empty config.json files by moving my static resources to another folder.  I had forgotten the resources folder was where deployd stores info about all they data types you create at the dashboard.  I am trying to integrate deployd with a clojurescript front end.  By default clojure build tools boot and lein use resources/public for static files.
