### ISSUE TITLE
app.dpd launching wrong version

### ISSUE THREAD

**Issue by charlietfl** [deployd/deployd#303]
When check version in command line get `0.6.10` , however running WIndows when launching using `app.dpd` am getting launched version as `0.6.9`. 

Thus am running into Firefox issue receiving json ( gets html instead) for 400 requests as noted in this issue  https://github.com/deployd/deployd/issues/133

**Update** Just realized was using download of  `chatroom` demo. Created a new app using `dpd create` and get same result...launches `0.6.9` when launched from `app.dpd`

**Comment by NicolasRitouet** [comment]
problem solved?
If not, feel free to reopen.
