### ISSUE TITLE
Huge session collection

### ISSUE THREAD

**Issue by wieshka** [deployd/deployd#314]
I am using Deployd for a year+, and the problem is that my sessions collection is quite big - is it safe to remove all records from this collections on DB level?

db.sessions.stats()
{
	"ns" : "database.sessions",
	"count" : 14469487,
	"size" : 2083649920,
	"avgObjSize" : 144.00302650674485,
	"storageSize" : 3918532608,
	"numExtents" : 22,
	"nindexes" : 1,
	"lastExtentSize" : 1021419520,
	"paddingFactor" : 1,
	"systemFlags" : 1,
	"userFlags" : 0,
	"totalIndexSize" : 3894482256,
	"indexSizes" : {
		"_id_" : 3894482256
	},
	"ok" : 1
}

If it is safe, maybe there should be mechanism for auto cleaning old records ?

**Comment by andreialecu** [comment]
This will happen if the client does not send cookies (the sid cookie in particular) with the request to reuse an existing session id. I will try to work on a fix for it.

**Comment by andreialecu** [comment]
This was fixed a while ago. Closing.
