### ISSUE TITLE
bad properties / invalid properties

### ISSUE THREAD

**Issue by beaspider** [deployd/deployd#324]
Hi, after writing an ON POST event to handle a git post-recieve webhook (from GitLab) I noticed that a property posted by GitLab: "user_name"; is missing from `this` in my event handler's scope.
I get that we cannot create properties with `_` through the deployd dashboard but it would be great to have access to *bad properties* in the events so we can fix any sent over e.g. where we don't have control over what is sent - or maybe just exposing the raw http request in the events API for edge cases like this?
Loving your work with deployd by the way :)

**Comment by andreialecu** [comment]
You can access properties not part of the collection (they get filtered out from `this`) using `ctx.body.propertyName`.
