### ISSUE TITLE
Running mongod with --auth

### ISSUE THREAD

**Issue by crshumate** [deployd/deployd#331]
I don't know if this is particular to my setup or if it is specific to deployd by accident (bug) or by design.

I found that when I started mongodb from the command line with the --auth parameter, I couldn't get or post from my collections. When I started mongodb without the --auth parameter everything worked fine. I had also setup a un and pw in the admin db.

I had also noticed after I logged in if I refreshed the page I woule then lose my session and had to relogin again.

Setup: Ubuntu 12.10, nginx 1.4.5, node 0.10.25, mongo 2.0.6

**Comment by NicolasRitouet** [comment]
any news regarding this issue?
Anybody had the same problem?

I'll close it, feel free to reopen it if necessary.
