### ISSUE TITLE
dpd-importer imports _id field as id

### ISSUE THREAD

**Issue by prt101g** [deployd/deployd#333]
I am using dpd-importer to import data into deployd.  The imported collections have both an _id, the mongodb objectid, and custom id fields.  However, the importer names both fields "id" and the imported collections end up having two fields with the same name, "id".

**Comment by NicolasRitouet** [comment]
This problem is not related to the core of Deployd, you should create a ticket on the repo: https://github.com/deployd/dpd-importer
