### ISSUE TITLE
401 Unauthorized for Every Login Request

### ISSUE THREAD

**Issue by mjhasbach** [deployd/deployd#335]
I've attempted to build my own Deployd app and even tried the example [here](https://github.com/deployd/examples/tree/master/users/login-form); however, I receive a 401 (Unauthorized) for every login request regardless of the credentials supplied. I have been able to successfully create users via dpd.users.post() and the dashboard, but cannot authenticate with any of them.

Windows 8 x64
Deployd 0.6.1
Node 0.10.26
Latest jQuery
Tested in Chrome 33 and IE 11

```
POST http://localhost:2403/users/login 401 (Unauthorized) jquery.js:8416
send jquery.js:8416
jQuery.extend.ajax jquery.js:7968
baseMethods.requestWithBody dpd.js:141
baseMethods.post dpd.js:152
r.exec dpd.js:262
dpd.users.login dpd.js:286
(anonymous function) index.html:32
jQuery.event.dispatch jquery.js:3063
elemData.handle.eventHandle
```

**Comment by andreialecu** [comment]
Closing this because it is targeting an older version. Please reopen if you still have this issue.
