### ISSUE TITLE
How to update deployd to newest version? 

### ISSUE THREAD

**Issue by ansarizafar** [deployd/deployd#337]
I have installed deployd with windows installer. now when I run dpd, a message displayed 
starting deployd v0.6.1...
deployd v0.6.10 is available. Use dpd-update command to install
listening on port 2403
 When I try to run dpd-update a window appears for few seconds and then disappears. after updating when I run dpd again the same above mentioned message reappears. Please let me know how to update deployed
dpd -V shows 0.6.1

**Comment by NicolasRitouet** [comment]
The update command of the v 0.6.1 of the windows installer didn't work properly.
To update, deinstall your version and [reinstall v 0.8.0](https://bintray.com/artifact/download/deployd/dpd-win-installer/deployd-win-0.8.0.exe) (soon available on the website).

**Comment by vpxavier** [comment]
Hello, 
The current version is 0.8.5
I installed using the windows installer and so, I get version 0.8.0.
How to upgrade to 0.8.5?

I also needed to install deployd locally using "npm install deployd" in the app folder to deploy it to amazon.
How to know which version is running locally as running dpd -V would return the windows package version, and how to upgrade the local version for my app folder?
Thanks a lot

**Comment by andreialecu** [comment]
`npm install -g deployd` should update the globally installed package for you.

However, I would suggest not having deployd installed globally at all. Uninstall the windows package and just keep deployd installed locally in your app via `npm install deployd --save`. 

If you need to use `dpd` to run your project, although I highly suggest using a [custom start script](https://gist.github.com/andreialecu/a563c9a5ab7fdd7dc02f), you can put the command line in package.json under `"scripts", eg:
```
"scripts": {
  "start": "dpd <optional parameters>"
}
```
And then start with `npm start`

**Comment by vpxavier** [comment]
Thanks, I will try that!
