### ISSUE TITLE
Date time field type required

### ISSUE THREAD

**Issue by ansarizafar** [deployd/deployd#339]
Why there is no date time collection field type? How to store date time in a collection?

**Comment by NicolasRitouet** [comment]
You should use Unix timestamp, that you store in the DB as number.
`new Date().getTime()`to get the unix timestamp from a Date object and `var date = new Date(unix_timestamp*1000);` to parse a timestamp into a Date object.

I close this ticket since it's not related to Deployd, but to javascript.

**Comment by andreialecu** [comment]
One small correction, you don't need to multiply by 1000.
