### ISSUE TITLE
Custom resource 'external' does not work as advertised.

### ISSUE THREAD

**Issue by ShadowZero3000** [deployd/deployd#346]
Following the advice given here:
http://docs.deployd.com/docs/developing-modules/internal-api/resource.md#s-External Prototype -1405
I have created the custom resource noted by adding:
<code>module.exports=Example;</code>
to the bottom of the example file.
However, within another resource's events (post.js in particular) when I attempt to call:
<code>dpd.example.hello({msg: 'hello world'});</code>
I receive the following error: 
<code>Object [object Object] has no method 'hello'</code>
and logging the object 'dpd.example' gives:
<code>{ get: [Function],
  post: [Function],
  put: [Function],
  del: [Function],
  exec: [Function] }</code>

I am attempting to utilize this functionality in a custom resource, and am unable to positively reproduce the example's results.

**Comment by cristianfd** [comment]
I know this topic is opened for a long time but @ShadowZero3000, have you implemented the example? Now the url is http://docs.deployd.com/docs/developing-modules/internal-api/resource.html#s-External%20Prototype%20-1405 and I'm getting
`TypeError: Cannot read property 'hello' of undefined`

**Comment by moorthi07** [comment]
@cristianfd pl. share you code / gist , to understand your flow vs the doc. Thx.

**Comment by cristianfd** [comment]
Yes, https://gist.github.com/cristianfd/539827f272b93c797b2736cbd4271ce9
Another test that I did is import the module as node module and include in example.js one function and this works:
example.js
```js
Example.test = function() {console.log("test");}
```

get.js
```js
var ex = require('example');
ex.test();
```

**Comment by moorthi07** [comment]
@cristianfd ,
1. Deployd currently loads **all your middleware code only from inside 'node_modules'** . So, all your  code should go inside 'nodemodules' folder.

2. One  **exception** is, the event files inside your '**resource'** folder. These files (get, post, put, validate, before, after commit, delete) are loaded when you start Deployd

3. If you like to use required from an event file from inside 'resource' folder - you have to install 'dpd-event-extention' module. Looks like you already did that, as you mentioned 'require' works inside get.js.

Having said that , can you check the following,
1. In your package.json do you have an entry for example.js (for your both approach). Deployd only loads packages / modules are in package.json.
2. Where exactly is your example.js (get.js of course inside 'resource' folder right?)

**Comment by cristianfd** [comment]
@moorthi07 yes, I know the tips.
1. Yes, I've included example.js in packages.json
2. /projectFolder/node_modules/example.js and get.js is inside /projectFolder/test/get.js

I will upload the example project (right now I don't have the code on this computer) to Github and share with you to clarify all points.

Thanks for your help

**Comment by moeinrahimi** [comment]
I'm stuck at this too
