### ISSUE TITLE
event on delete timeout

### ISSUE THREAD

**Issue by XciD** [deployd/deployd#349]
Hi, 
I've an issues when I want to delete an value, there is my problem 
I've two table : table "ones" and table "twos".

On the table "twos", there is an id of the table "ones"
```
two : { "name" : "test" , "oneId" : "3adazdazdza" }
```
when I delete a value on the table "twos" I would like to delete also in table "ones" by the id.

so there is my code :
ON DELETE EVENT : 
```
cancelUnless(me, "You are not logged in", 401);

dpd.ones.del({id: this.oneId, $limitRecursion: 1}, function(one) {

});
```

But I get a timeout 504, What should I do ?.
It doesn't work even if I replace del by get... 

Thank you

**Comment by andreialecu** [comment]
This looks like it should work. Please reopen this if you still have this issue. Closing.
