### ISSUE TITLE
ES6 Promises & dpd.js

### ISSUE THREAD

**Issue by tmcnab** [deployd/deployd#350]
Currently the signature for most client-side operations goes in the form of:

```js
dpd.foo.get(function (items, error) {
    // check for error or do something with items
});
```

What would be nice is switching over to the ES6-spec Promises system so that the above can be written as:

```js
dpd.foo.get().then(function (items) {
    // do something with items 
}).catch(myGenericErrorHandler);
```

I would imagine this is an opt-in scenario, since collection methods only need to return promises if no callback function is provided as an argument to the method.

**Comment by NicolasRitouet** [comment]
Done with pr #484
