### ISSUE TITLE
How to filter Objects/Arrays?

### ISSUE THREAD

**Issue by Revassin** [deployd/deployd#351]
Hi guys,

Well the subject kinda explains my question already but il go a bit more in depth.

I am building a app which makes use of PHP. I am using cURL to handle http requests. However in my mongo database I have a collection with a associated array that I want to filter.
How would I do this? The normal way is easy enough 

http://localhost:2403/campaigns?name=Parlor

But I have no idea how to do this with arrays & objects and the documentation didn't help me much.

**Comment by hongkongkiwi** [comment]
+1 for this

**Comment by ericfong** [comment]
if you have 
```
{
   "array": ["A", "B", "C"],
   "object": {"X":"Y"}
}
```

you can 
```
dpd.collection.get({ array: { $in : ['A':'B'] } } )
//OR
dpd.collection.get({ 'object.X':"Y" } )
```
Deployd suport most of the mongo query. 
Just reference to mongodb docs and try with dpd.
If it doesn't work, welcome Hacking and PR. :+1:

**Comment by Revassin** [comment]
That answer is a almost a year to late... I already finish this project for school. And I still think Parse is the superior alternative to deployd.
