### ISSUE TITLE
Promise support for server-side Collection API

### ISSUE THREAD

**Issue by dallonf** [deployd/deployd#375]
Thanks to the community, we now have Promise support in Dpd.js! (deployd/deployd#374)

The same (or similar) feature would be extremely helpful in the server-side Collection API, which usually mirrors Dpd.js.

**Comment by andreialecu** [comment]
Done as PR https://github.com/deployd/deployd/pull/484

**Comment by NicolasRitouet** [comment]
PR has not been merged yet, this ticket stays open until then.

**Comment by NicolasRitouet** [comment]
#484 rebased, ticket closed
