### ISSUE TITLE
Persist an "post" when disconnected

### ISSUE THREAD

**Issue by calebeaires** [deployd/deployd#377]
Is there any way to do an post/put when the user is disconnected, then the app sync data with the server?

**Comment by ericfong** [comment]
Will be good to have that.

But offline data sync over REST api is not an easy topic.

If you guys have any good library can do that. Please let me know.

**Comment by andreialecu** [comment]
This is something you could do on the client layer, just temporarily save to localStorage and use `dpd.on("reconnect", function() { ... }` to make sure everything was properly saved.
