### ISSUE TITLE
Deployd update Windows 7

### ISSUE THREAD

**Issue by crpr** [deployd/deployd#382]
I can´t seem to run dpd-update on windows 7 64bits machine. I have node 0.10.29 and npm 1.4.14.

When i try to update from 0.6.1 to 7.0 deployd identifies node as 0.8.2 and npm 1.1.36 and gives an error. 

Also can't install commander2.2.0.

Any help?

**Comment by Kvarkas** [comment]
Is that still an issue or this can be close?
