### ISSUE TITLE
How to use deployd with OpenShift

### ISSUE THREAD

**Issue by mastayoda** [deployd/deployd#388]
Hello everyone,

I'm evaluating some Bass for my app and I don't want to use Parse.com. I tried deployd locally and its awesome, now I'm trying to figure out how to use it with OpenShift, don't you guys plan to create a OpenShift Cartridge? I think it will fit perfectly, or any manual guide of how to do it its also really appreciate.

Thanks so much for your time, let me know if someone have done this before.

**Comment by kosir** [comment]
+1

**Comment by ipepe** [comment]
https://www.npmjs.com/package/dpd-openshift-start-script

**Comment by adyba** [comment]
Pratryk @ipepe, 
self promotion is OK but the self documentation is definitely the hurdle ;) Would you be so nice and make a video or write a blogpost to describe the whole process? Your `readme`  is even more confusing than original documentation. `code inside v2.3` inside what? Be kind and patient with rest of us ;)

**Comment by ipepe** [comment]
I will gry to improve it :)

Code inside (module of version) 2.3

**Comment by Chan-Dru** [comment]
+1

**Comment by NicolasRitouet** [comment]
If somebody wants to write a tutorial to use deployd on Openshift (or somewhere else), I can open the wiki on github and place the link in the readme.
In the meanwhile, I'll close this ticket.
