### ISSUE TITLE
Failed to start MongoDB

### ISSUE THREAD

**Issue by miralem-cebic** [deployd/deployd#389]
I have a Ubuntu 14.04 Server running.
Node.js is installed and I installed MongoDB with sudo apt-get install mongodb -y

Also deployed ist successfully installed.

When I setup a new project and try to run dpd I get this error

"Failed to start MongoDB"

With DEBUG
I get this

starting deployd v0.7.0...
  mongod starting mongod +0ms
  mongod <Buffer 53 61 74 20 41 75 67 20 20 32 20 31 32 3a 34 36 3a 35 34 2e 35 30 39 20 5b 69 6e 69 74 61 6e 64 6c 69 73 74 65 6e 5d 20 4d 6f 6e 67 6f 44 42 20 73 74 61 ...> +68ms
  mongod <Buffer 53 61 74 20 41 75 67 20 20 32 20 31 32 3a 34 36 3a 35 34 2e 35 31 34 20 5b 69 6e 69 74 61 6e 64 6c 69 73 74 65 6e 5d 20 64 62 20 76 65 72 73 69 6f 6e 20 ...> +4ms
  mongod <Buffer 53 61 74 20 41 75 67 20 20 32 20 31 32 3a 34 36 3a 35 34 2e 35 32 30 20 5b 69 6e 69 74 61 6e 64 6c 69 73 74 65 6e 5d 20 65 78 63 65 70 74 69 6f 6e 20 69 ...> +6ms
  mongod exit code 100 +6ms
Failed to start MongoDB
  mongod error: 1 +2ms
  mongod killing mongod +1ms

reinstalling mongodb doesn't fix the problem. Please help

**Comment by GUSCRAWFORD** [comment]
I know the issue is closed but I was able to produce this by trying to start dpd pointing at pre-existing WT data built from mongo 3.6.  Clearing the data solved the problem for me.
