### ISSUE TITLE
Moving from Deployd to where?

### ISSUE THREAD

**Issue by manviny** [deployd/deployd#416]
I love the way deployd do thing and really like the project to continue, but reality seems to be different to my wishes.

Has anybody try different options like: meteor, derby.js, loopback ...? What is your opinion?

**Comment by NicolasRitouet** [comment]
I'll close this ticket, feel free to continue this discussion on google groups or on the chat.

**Comment by pensierinmusica** [comment]
For fast backend API dev, still feels like Deployd is the best in league. I just wish the project could have more active development: so many structural product choices are spot on, and different from available alternatives.

Btw, [**Telepat**](http://telepat.io/) is also worth checking out.

**Comment by coderofsalvation** [comment]
rising talents:

https://github.com/thomas4019/expressa (100% jsonschema, allows nested-data & file/mongo/postgres per endpoint)
https://www.forestadmin.com/lumber (beautiful admin)

no frontend editor though (but you can just use your own)

**Comment by PaulMaly** [comment]
I think great thing: http://parseplatform.org/

**Comment by dopry** [comment]
I've been tinkering with keystone.js and trails.

**Comment by geocine** [comment]
Anyone still using `deployd` or have you moved to a different framework , care to share what is it?

**Comment by csvan** [comment]
@geocine we moved to http://loopback.io/ long ago and it works great.
