### ISSUE TITLE
deployd abort due to database connection interrutpion

### ISSUE THREAD

**Issue by ericq** [deployd/deployd#420]
Hi, 
I experienced deployd process abort caused by the db connection interruption. I was expecting the deployd to auto retry the connection once the DB connection is up again. 

Thoughts? Did I miss any configuration to enable the auto-reconnect?  
/Eric

**Comment by ericfong** [comment]
Have PR that use latest mongodb version. That may work

**Comment by andreialecu** [comment]
This should be fixed, closing.
