### ISSUE TITLE
Can't run deployd

### ISSUE THREAD

**Issue by phatpham9** [deployd/deployd#421]
I read this http://ericfong.github.io/deployd-docs/docs/getting-started/your-first-api.md.html and followed these instruction to run first deployd api:
dpd create hello-world
cd hello-world
dpd -d

Then nothing happened. The command prompts "starting deployd v0.7.0... and exits. What is wrong with it? Please help.

**Comment by j-a-y-c-e-e** [comment]
Just in case other people are still having issue.
Run using:
$dpd create <app-name>
$cd <app-name>
$ dpd --dbname <dbname>
starting deployd v0.6.10...
listening on port 2403
type help for a list of commands
dpd > 

This will use the mongod inside the deployd tools folder.
