### ISSUE TITLE
Socket.io load error with dpd.js when loading from different origin

### ISSUE THREAD

**Issue by jeffbcross** [deployd/deployd#45]
I've got deployd running at localhost:2403, and a consumer app running at localhost:8080, using dpd.js to interact with the API. I get this error in the console on page load:

Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8080/socket.io/1/?t=1345880809313

**Comment by NicolasRitouet** [comment]
It seems to be solved, I'm closing the issue.
Feel free to reopen it if you have more issues.
