### ISSUE TITLE
Ability to disable dpd.js client script generation 

### ISSUE THREAD

**Issue by andreialecu** [deployd/deployd#457]
I'm using deployd with angular, so I've been working on reimplementing dpd.js as an angular service:
https://github.com/andreialecu/angular-dpd

This means I don't need dpd.js at all, and I'd rather not have all of my collections listed there for security purposes. There needs to be a configurable parameter for the deployd server on whether to serve the dpd.js file or not. 

I think it still needs to be available for the dashboard, so it may need to be served only if the root admin cookie is set.

I'll probably work on a PR for this soon, though I think we need to decide what to do about my other PRs first, so I don't diverge even more from the HEAD, making things even harder to merge later.

**Comment by simpleTechs** [comment]
This sounds pretty good, I'd like to second that request! We're using deployd mainly as a backend for iS Apps, so dpd.js isn't necessary for us either.

**Comment by andreialecu** [comment]
Fixed was added in #535
