### ISSUE TITLE
Test: Patches to allow Travis to run Integration Tests

### ISSUE THREAD

**Issue by andreialecu** [deployd/deployd#458]
So, because the maintainers (@ericfong @NicolasRitouet) have been having trouble running the integration tests after my recent pull requests, I wanted to run them on Travis and I was able to do it using mocha-phantomjs and some changes to the dpd tool.

Check this successful build:
https://travis-ci.org/andreialecu/deployd/builds/44891277 and
https://travis-ci.org/andreialecu/deployd/builds/44892252
The results from the integration tests are there (98 passed)

I won't do a pull request for this unless you want me to, but the relevant commit is here:
https://github.com/andreialecu/deployd/commit/87768367c80b6dcebf4b44b6f059e8f2f3cb9ae5

You can manually pull/integrate it and Travis will do integration testing. For some reason it isn't running the regular tests now, but I didn't look into that - it's probably an easy fix. I was mainly after running the integration tests.

**Comment by NicolasRitouet** [comment]
Hi @andreialecu 

I'll take a look at this, give me a few days.

Thanks.

**Comment by andreialecu** [comment]
Closing this. Moving discussion to PR #476
