### ISSUE TITLE
Fixed an issue with UserCollection Authenticate/Login. But how do I get this to take effect everytime I create a project?

### ISSUE THREAD

**Issue by sw33n3y** [deployd/deployd#460]
UserCollections was not working out of the box. Could not create users on front or back-end. Fix was simple. Added  empty properties parameter to json.config file...

{
   "type: "UserCollection",
   "properties" : {}
}  

However, I cannot figure out how to add this simple line when I create a new project. I'm sure it involves the user-collection.js but it seems to be more than simply appending a string.

**Comment by andreialecu** [comment]
@sw33n3y which version of deployd are you using? There is a test for this specific functionality here:
https://github.com/deployd/deployd/commit/9d4363fd8806e385f19523affeb23bae100d786b

It passes and seems to have been fixed in 2012.

**Comment by sw33n3y** [comment]
I'm currently using version 6.1. Simply because the newest version(the one that installs with npm) had an issue involving mongoDB that I couldn't really find a fix for. It was the same discussed here:

https://github.com/deployd/deployd/issues/276

**Comment by andreialecu** [comment]
You could start mongod separately, and then pass the host and port to the dpd CLI if you're using it. However, I would suggest actually not using `dpd` and starting your own server with your own code, like this:

https://gist.github.com/andreialecu/345559fd0e98d9fe7ad1

**Comment by andreialecu** [comment]
Note that for the above code to work you need to use the latest version of deployd (0.8+)

**Comment by NicolasRitouet** [comment]
@sw33n3y Since @andreialecu gave you an answer, I'll close this ticket, feel free to reopen it if you have more questions.
