### ISSUE TITLE
Server restart and mongodb connection issue 

### ISSUE THREAD

**Issue by hugsbrugs** [deployd/deployd#461]
When working on my project, I sometimes have bugs in my code (yes I'm not a genius ...), so I have to restart my server.

First method (have to relaunch manually) :
```javascript
node my-server-script.js
```
Second method (-w option for watching for code changes and reload server):
```javascript
forever -w start my-server-script.js
```

With both methods I get a :

```javascript
Error: db object already connecting, open cannot be called multiple times
    at Db.open (/var/www/wine-deploy/node_modules/deployd/node_modules/mongodb/lib/mongodb/db.js:234:11)
    at getConnection (/var/www/wine-deploy/node_modules/deployd/lib/db.js:122:13)
    at collection (/var/www/wine-deploy/node_modules/deployd/lib/db.js:153:3)
    at SessionStore.Store.find (/var/www/wine-deploy/node_modules/deployd/lib/db.js:336:3)
    at SessionStore.createSession (/var/www/wine-deploy/node_modules/deployd/lib/session.js:67:10)
    at /var/www/wine-deploy/node_modules/deployd/lib/attach.js:91:23
    at /var/www/wine-deploy/node_modules/deployd/lib/util/http.js:64:9
    at /var/www/wine-deploy/node_modules/deployd/node_modules/corser/lib/corser.js:79:13
    at exports.setup (/var/www/wine-deploy/node_modules/deployd/lib/util/http.js:24:3)
    at Object.handleRequest [as handle] (/var/www/wine-deploy/node_modules/deployd/lib/attach.js:88:5)
```
Reading some docs on stackoverflow on this quite common error : [http://stackoverflow.com/questions/10108170/node-js-reuse-mongodb-reference](http://stackoverflow.com/questions/10108170/node-js-reuse-mongodb-reference), I tried to make a change in deployd/lib/db.js, changing : 
```javascript
this._mdb = new mongodb.Db(this.options.name, new mongodb.Server(this.options.host, this.options.port));
```
by :
```javascript
this._mdb = new mongodb.Db(this.options.name, new mongodb.Server(this.options.host, this.options.port, {auto_reconnect: true}));
```
But it didn't resolve the issue. I'm wondering if in attach.js, there shouldn't be something closing the db connection when server crashes ?

Does anybody encoutered this error which is annoying when developping because the only solution I found for know is just waiting before restarting my server ...

Thanks for sharing your thoughts about it !

**Comment by andreialecu** [comment]
@hugsbrugs I had the exact same error, it will be fixed by #467 . You can use my branch at https://github.com/andreialecu/deployd/tree/update-dependencies in the mean time to test and see if it fixes it for you.

**Comment by hugsbrugs** [comment]
@andreialecu it seems to work great ! thank you very much for this fix !

**Comment by andreialecu** [comment]
I think this is fixed now, so closing it.
