### ISSUE TITLE
PUT request with a combined query of `$push` and `$pull` leads to inconsistent `validate` call

### ISSUE THREAD

**Issue by DaGaMs** [deployd/deployd#463]
In my code, I am trying to update two arrays `sharedWith` and `unsharedWith` simultaneously, using a query like this:

``` dpd.items.put(itemID, {"sharedWith": {'$push': me.id}, "unsharedWith": {"$pull": me.id}}, function (res, err) ```

In **items/validate**, I noticed that `this` and `previous` are incorrect. The database shows this:

    sharedWith: [], unsharedWith: [ '80d55f3717be2878' ]

however my logging shows this:

    //previous
    sharedWith: [ '80d55f3717be2878' ], unsharedWith: [ '80d55f3717be2878' ]
    //this
    sharedWith: [ '80d55f3717be2878' ], unsharedWith: []

So, it seems that previous is taken *after* the `$push` is applied but *before* the `$pull`.

**Comment by andreialecu** [comment]
I have fixed this in #470. I also added a (previously failing) test for this error.

If you need it right away feel free to pull it in your own repo.

**Comment by andreialecu** [comment]
#470 was merged, closing this.
