### ISSUE TITLE
Dead link after selecting "Show Starter Guide" at end of Windows Installer

### ISSUE THREAD

**Issue by cmacdonnacha** [deployd/deployd#487]
After selecting the checkbox at the end of the Windows installer ![installer](https://cloud.githubusercontent.com/assets/9777763/5785384/dc9c6c00-9dcd-11e4-917a-acdb8ba80df0.png)
a browser is launched and tries to navigate to http://www.deployd.com/docs

But it's seems to redirect to http://docs.deployd.com/redirect?url=/docs which is a dead link.

**Comment by cmacdonnacha** [comment]
Looks like the link should be updated to: http://docs.deployd.com/docs/

**Comment by korpirkor** [comment]
Same for me: dead link `http://docs.deployd.com/redirect?url=/docs` after installation.

In the dummy index.html file there are also two dead links:
- http://docs.deployd.com/docs/getting-started/what-is-deployd.md
- http://docs.deployd.com/docs/getting-started/your-first-api.md

**Comment by NicolasRitouet** [comment]
Unfortunately, we don't have the script to build the windows and macosx binaries, which means that we won't be able to update them.
If somebody has some experience with this and wants to help, let us know.

**Comment by dallonf** [comment]
I have the Windows build script lying around somewhere... let me track it down sometime this week. Stay tuned!

**Comment by NicolasRitouet** [comment]
That would be awesome, I really think we should keep the binaries :+1:

**Comment by dallonf** [comment]
Here's the link to the repo, by the way: https://github.com/deployd/dpd-win-installer/commits/master

It uses, uh, NSIS I think? It's been a long time since I've been in there.

And I have *no* idea where the Mac installer comes from. @ritch @jeffbcross Do you still have that lying around?

**Comment by cmacdonnacha** [comment]
I've also noticed some dead links within the deployd app itself:

![dead_link_1](https://cloud.githubusercontent.com/assets/9777763/5798700/f49ff056-9fc1-11e4-833a-7c9cc9d4458b.PNG)


![dead_link_2](https://cloud.githubusercontent.com/assets/9777763/5798702/f9595b78-9fc1-11e4-84b7-0ec3063fc2f5.PNG)

**Comment by korpirkor** [comment]
Do we really need installer ? If there would be clear info, for that I can just `npm install -g deployd`, I wouldn't even download the installer :)

**Comment by NicolasRitouet** [comment]
The installer also includes mongodb, which can be problematic to install for beginners.

**Comment by dallonf** [comment]
OK @NicolasRitouet, I've got a new Windows installer built at `https://www.dropbox.com/s/47bhlt4q8qo6oee/deployd-win-0.7.0.exe?dl=0`. (As an added bonus, I bumped to version to 0.7.0 instead of the ancient 0.6.1 that's up on the site now) I completely forgot how we update the website, though; do you happen to know? **Let me know when it's up on the site** so I can remove it from my Dropbox account.

Also, I don't seem to have commit permissions to the https://github.com/deployd/dpd-win-installer repo - can anyone grant that to me so I can update the script?

**Comment by NicolasRitouet** [comment]
@dallonf awesome, thanks.
Unfortunately, I don't have access to the site's code and also don't have write access to the dpd-win-installer repo.

I'll ask @jeffbcross to fix all of these.
In the meanwhile, can you send a PR to the dpd-win-installer, so I can start working on the update for 0.8 (coming soon) ?

**Comment by NicolasRitouet** [comment]
> Also, I don't seem to have commit permissions to the https://github.com/deployd/dpd-win-installer repo - can anyone grant that to me so I can update the script?

@dallonf: you should have commit permission on dpd-win-installer, can you verify?

**Comment by dallonf** [comment]
@NicolasRitouet It seems that I do not. I submitted a pull request, though.

**Comment by ritch** [comment]
@dallonf @NicolasRitouet added you both as collaborators on https://github.com/deployd/dpd-win-installer

**Comment by NicolasRitouet** [comment]
@ritch thx
@dallonf I tested the latest version of the installer and it works perfectly.
I created a bintray account to host the binaries:
https://bintray.com/nicolasritouet/dpd-win-installer
You can already remove the file from your dropbox account if you want to.
Now, we just need the same for the macosx and then update the link on the website.

**Comment by NicolasRitouet** [comment]
@dallonf 
We have a new version, could you update the windows installer?
I created a [bintray organisation](https://bintray.com/deployd), if you have an account on bintray, I can add you.
