### ISSUE TITLE
Return Object instead of Array

### ISSUE THREAD

**Issue by kvdmolen** [deployd/deployd#507]
First, thanks for this great tool, it's exactly right for so many things.

Would it be possible to output the records as Object? Like:
```json
{
    "a1b2c3d4": {
        "title": "Hello"
    },
    "e5f6g7h8": {
        "title": "World"
    }
}
```
instead of
```json
[
    {
        "id":  "a1b2c3d4",
        "title": "Hello"
    },
    {
        "id":  "e5f6g7h8",
        "title": "World"
    }
]
```
Thanks!

**Comment by ipepe** [comment]
How do You imagine doing loops over that?

**Comment by kvdmolen** [comment]
Same as Arrays:
```javascript
for(var i in result){
    ... result[i] ...
}
```
Point is, when `id` is known, I'd say it's much cleaner (and faster) to use
```javascript
var item = result[id];
```
(in case `result` is an object) then
```javascript
var item = result.filter(function(el){return el.id = this.id},{id:id});
```
(in case `result` is an array). Yes you could do separate requests, but my app requests many small items at once.

Though, [this](http://stackoverflow.com/questions/12553274/getting-index-of-an-arrays-element-based-on-its-properties) provides another relatively clean solution too.

**Comment by ipepe** [comment]
My bad. But it is still not common practice. All controllers and models in frameworks use arrays, not id-based objects with other objects attached to them. You can always do:
```javascript
    var resultObj;
    result.forEach(function(eachObj){
        result[each.id] = each;
    });
```
or if You already know id of some object in collection, then query it on get:
```javascript
dpd.todos.get({id:'myid'}, function(result,error){
//handle code here
});

**Comment by kvdmolen** [comment]
Yes, you're right. It is not standard, but I somehow find in convenient (which is also due to the recursive code I use). Could be a switch in the resource editor.

I'll close this issue and leave it as an optional feature-request :)

**Comment by ipepe** [comment]
Thank You for Your contribution into deployd project
