### ISSUE TITLE
Action URLs and nested Paths

### ISSUE THREAD

**Issue by tsldh** [deployd/deployd#508]
It would be awesome if you could add the ability to define custom action URLs / routes. Just like `/users/login` and `/users/me`, it would be cool to be able to do actions on other collections, e.g.
`/comments/5/like` 
or also nested Paths
`/projects/45/tasks` or `/projects/45/tasks/234`

**Comment by ericfong** [comment]
deployd may provide util for express middleware to handle this problem.

But I don't think deployd standard API should be that flexible (too many config and hard to learn)

**Comment by andreialecu** [comment]
This is possible to do with https://github.com/deployd/dpd-event

You define an event for 'projects' then use `parts[]` to split it and use 

```javascript
dpd.realcollection.get(query).then(function (results) { setResult(results); })
```

**Comment by ericfong** [comment]
Thanks @andreialecu !
