### ISSUE TITLE
Allow to resize the code editing window

### ISSUE THREAD

**Issue by Maddis1337** [deployd/deployd#516]
Deployd uses a pretty good editor for writing the event code in the browser, but it does not allow to resize the editing window or even to display it in fullscreen mode (meaning the editor should fill the whole page, not the 'real' fullscreen mode from HTML5). Especially the vertical height is too small in my opinion.

**Comment by andreialecu** [comment]
Fixed by https://github.com/deployd/deployd/pull/573
