### ISSUE TITLE
Middleware does not work if request stream was already drained

### ISSUE THREAD

**Issue by Maddis1337** [deployd/deployd#519]
I am using deployd 0.8.0 and recently switched to using deployd as a middleware and created a custom middleware that reads from the request stream on the end event and then calls next. Example code:

```
app.use(require('body-parser')());
app.use(server.handleRequest)
```
probably because the stream already called the 'end' event. There is a related [link](http://lexaux.blogspot.de/2013/10/nodejs-express-middleware-be-aware-of.html).

**Comment by ericfong** [comment]
Hi, 

server.handleRequest is quite hacky way to turn deployd into express compatible middleware.

Personally, I don't use body-parser. But cookieParser, basicAuth, morgan work.

Why you need body-parser by the way ?

**Comment by Maddis1337** [comment]
Body parser is just an example that is a one-liner, I have a self-made middleware that is basically a firewall and has to skip deployd under certain conditions. 

> server.handleRequest is quite hacky way to turn deployd into express compatible middleware.

Not [according to the docs](http://docs.deployd.com/docs/server/work-with-express.html).

**Comment by ericfong** [comment]
Will try to look into this issue. 
But, I am not a profession of express middleware. 
If you want to submit a PR to us.
We will try to rebase that ASAP
