### ISSUE TITLE
Deployd 0.7 for windows error 

### ISSUE THREAD

**Issue by ramstein74** [deployd/deployd#520]
i installed latest deployd for windows and i got this error.

![image](https://cloud.githubusercontent.com/assets/1210858/6353084/fbeec780-bc3e-11e4-81cc-3fc0bdcee6b0.png)

**Comment by dallonf** [comment]
Are you using a 32-bit or 64-bit machine? You'll most likely need 64-bit, as 32-bit MongoDB has been deprecated.

**Comment by ipepe** [comment]
From where do You have installer file?

**Comment by andreialecu** [comment]
Your OS seems to be 32-bit. This should be resolved if you install the 32-bit nodejs.
