### ISSUE TITLE
dpd fails after start in OSX

### ISSUE THREAD

**Issue by jsphstls** [deployd/deployd#524]
$ dpd
    starting deployd v0.8.0...
    listening on port 2403
    type help for a list of commands
    dpd > Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deployd.com/docs/basics/cli.html)

As instructed I try:

    $ dpd --mongod
    starting deployd v0.8.0...
    child_process.js:1129
      var err = this._handle.spawn(options);
                         ^
    TypeError: Bad argument
        at TypeError (native)
        at ChildProcess.spawn (child_process.js:1129:26)
        at exports.spawn (child_process.js:988:9)
        at Object.exports.restart (/usr/local/lib/node_modules/deployd/lib/util/mongod.js:38:14)
        at start (/usr/local/lib/node_modules/deployd/bin/dpd:149:16)
        at Object.<anonymous> (/usr/local/lib/node_modules/deployd/bin/dpd:278:31)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3

I am able to run `$ mongod` without issue. I have a guess that the problem is.

MongoDB only works well on osx if you create /data/db as instructed in their install guide `mkdir -p /data/db`. But, Deployd instructs MongoDB to use the `/data` directory inside the app that I create with `dpd create` ? Everytime Mongo starts, it looks for the original `/data/db` while Deployd is working with the app `/data` ?

**Comment by ericfong** [comment]
what is the output of ```which mongod``` ?

or please try  ```dpd --mongod `which mongod` ```

**Comment by jsphstls** [comment]
$ which mongod
    /usr/local/bin/mongod

and then

    $  dpd --mongod `which mongod`
    starting deployd v0.8.0...
    listening on port 2403
    type help for a list of commands
    dpd > Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deployd.com/docs/basics/cli.html)

**Comment by CWalig** [comment]
I had the same problem, I have to use sudo all the time.

Have you tried ?
```
sudo dpd
```

**Comment by ericfong** [comment]
When you use sudo. Can you see "data" folder created in the project folder?

**Comment by ericfong** [comment]
May related to https://github.com/deployd/deployd/issues/515

**Comment by CWalig** [comment]
Yup I can see the data folder.
Indeed I was about to write a message on #515 , I had also this problem with my new module and "npm install" didn't fix it, but I don't think it was for the same reason though.

**Comment by ericfong** [comment]
I guess you need sudo dpd because mongo cannot create a folder in your project folder.

But #515 hide the real error message.

**Comment by CWalig** [comment]
agreed, yes I had many various errors and always had the #515  message while knowing it wasn't the real problem.

**Comment by jsphstls** [comment]
confirmed `sudo dpd` works

	$ sudo dpd
	Password:
	starting deployd v0.8.0...
	listening on port 2403
	type help for a list of commands
	dpd >

**Comment by ericfong** [comment]
You should not need sudo. please check the permission of your project folder.

**Comment by jsphstls** [comment]
What is the best way to give this folder access to mongod/dpd?

**Comment by ericfong** [comment]
I think you should use same user to run dpd and own the project folder. So the dpd process can work

**Comment by jsphstls** [comment]
$ ls -ld
    drwxr-xr-x  7 myuser  mygroup  238 Feb 26 12:22 .

**Comment by ericfong** [comment]
I am not sure why then.

**Comment by CWalig** [comment]
I think I found why. It's coming from node, you just need to fix the ownership of the .npm
```
sudo chown -R $(whoami) ~/.npm
```

**Comment by jsphstls** [comment]
$ sudo chown -R me ~/.npm
	Password:
	$ dpd
	starting deployd v0.8.0...
	listening on port 2403
	type help for a list of commands
	dpd > Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deployd.com/docs/basics/cli.html)

**Comment by kengregson** [comment]
don't know if it's exactly the same problem but with:
- MongoDB (v3.0.1) installed via MacPorts in /opt/local and autorun via launchctl
- deployd (v0.8.0) installed globally via npm

for dpd hello-world app:
dpd>Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deployd.com/docs/basics/cli.html)

running as root via sudo worked.

Two issues that resolved the problem were:
1) start dpd via "dpd -H localhost -P 27017" to connect with already running mongod

Resulted in "Error: EACCES, open '/usr/local/lib/node_modules/deployd/.latestversion'"
(globally installed .latest version owner:group are "root:staff")
2) sudo chmod 666 /usr/local/lib/node_modules/deployd/.latestversion (no idea why dpd needs write permission)

**Comment by ericfong** [comment]
Please try to use a server.js 

http://docs.deployd.com/docs/server/as-a-node-module.html

I think that should be the default way to use dpd

**Comment by fimdomeio** [comment]
@kengregson I had the same issue, your solution also worked for me
