### ISSUE TITLE
Deployd doesn't work with NodeJS v0.12

### ISSUE THREAD

**Issue by javaguy44** [deployd/deployd#529]
Hi,

Just got a new macbook and thought I would upgrade my Node version in the process.

Using Node v0.12, when I start deployd I get the infamous mongod error e.g. Make sure 'mongod' is in your $PATH

However, mongod is def in $PATH as I can >mongod in terminal successfully, and even start the mongod instance passing data folder as argument.

Downgrading node to v0.10.32 (which is what I was running initially) fixed the issue.

**Comment by ericfong** [comment]
Any stack trace after Make sure 'mongod' is in your $PATH ?

**Comment by javaguy44** [comment]
No stacktrace, that was the only error message.

I can see why you prob wouldn't believe me since most people don't have $PATH configured, but I def have $PATH configured w/ mongod.

As I said, I can do the following from terminal as a test:
>mongod /deployd/dbfolder and mongodb will startup correctly

Downgrading + uninstall node v0.12 and re-install 0.10.32 = deployd success.  This should not happen if $PATH was incorrectly configured for mongodb.

Thx

**Comment by javaguy44** [comment]
Nope, no stacktrace after Make sure 'mongod' is in your $PATH

I did dig around a bit -- as I said I ran mongod from terminal pointing to deployd db folders and mongodb started up ok.

e.g. the following worked OK and mongodb fired up.
>mongod /deployd/dbfolder/

Just deployd wouldn't start.

**Comment by ipepe** [comment]
title is misleading, could You change it please?

**Comment by javaguy44** [comment]
How is it misleading?  Deployd does not work since it can't make requests from mongodb.  If you want a new title, please suggest.  Thx

**Comment by ipepe** [comment]
Isn't DPD mongo portable instance jest not working? I mean that saying: "Airconditioning is broken, so car doesn't work" is not actually a truth.

**Comment by javaguy44** [comment]
Do you use DPD without a DB?  Personally I do not.  No saves or reads from DB.  To use your analogy, a part of the engine is broken so the car won't drive.

**Comment by ipepe** [comment]
I tought that DPD commandline mongo doesnt work

**Comment by ericfong** [comment]
Actually, as I know, deployd unit test fail in node v0.12 and iojs.

But I am running my production deployd server with iojs.

I have a server.js instead of "dpd -d"

Actually, I think dpd -d is not a good for long running. I suggest everyone should have their server.js and treat deployd as an library.

**Comment by ipepe** [comment]
I use openshift hosting so im also using server.js. Also a side note: I tried benchmarking deployd api with Apache Benchmark and dpd -d fails/crashes because of too big overload. Normal instance of DB + server.js runs fine.

**Comment by ericfong** [comment]
You saw this error string
https://github.com/deployd/deployd/blob/master/bin/dpd#L161

with server.js ??

**Comment by andreialecu** [comment]
#577 fixes unit tests on node 0.12

**Comment by NicolasRitouet** [comment]
fixed with #577
