### ISSUE TITLE
Chinese character encoding problems

### ISSUE THREAD

**Issue by Sami-M** [deployd/deployd#543]
Hi all,

So I'm testing out deployd and found you could prepopulate collections using mongoimport. This works with most english language data, but the troubles begin with utf-8 characters such as chinese. I imported a csv (via mongoimport) containing chinese, but the deployd dashboard only shows these elements as "...", and the data is encoded incorrectly when retrieved using the rest api calls. I know the problem isn't inputting the data in mongo since logging the data there shows the characters correctly.

So is this a bug? A non-supported issue? Has anyone experienced a similar problem and got it to work?

Thanks

**Comment by ericfong** [comment]
My DB has many UTF-8 chinese always, they show correctly in my app and dashboard and mongo shell.

I have never use mongo csv import. Try to use node to read the csv and write the item by dpd.

Thanks

**Comment by Sami-M** [comment]
Hey Eric,

Thanks for the advice, upon using dpd to populate mongo everything went fine.
