### ISSUE TITLE
Data changes in dashboard don't emit?

### ISSUE THREAD

**Issue by ryanfields** [deployd/deployd#545]
When I make changes to data in the dashboard, nothing is emitted.  Is this intentional?  I can't tell if this is because of something I did wrong, or if data changes in the dashboard are always silent.

Shouldn't changes made to the data always trigger events, no matter where those changes are made?

**Comment by andreialecu** [comment]
Changes made in the dashboard bypass the code in all the Events (on get/on post/etc). So if you have emits there they won't fire. 

The data view in the dashboard is supposed to be a "bare metal" interface to the data store, to be used while prototyping, but not in production. 

Running Events could have unintended side effects.
