### ISSUE TITLE
Password is not updated while inserting

### ISSUE THREAD

**Issue by narayananramu** [deployd/deployd#549]
Hello,

Password is not updated in deployd when inserting a new record to user collection. Post request

**Comment by ericfong** [comment]
more detail ?  how your script look like?

**Comment by narayananramu** [comment]
Simple Post request through POSTMAN 

POST /users HTTP/1.1
Host: localhost:2403
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

username=ramuusddf&password=1234

output i get
{"username":"ramuusddf","id":"25a5d09adec6d9f8"}

**Comment by dallonf** [comment]
Passwords are never returned as output. That would be a major security problem! Try logging in as that user, it should work fine.

Closing this as a non-issue, feel free to re-open if I'm misinterpreting.
