### ISSUE TITLE
deployd access mongodb on compose

### ISSUE THREAD

**Issue by kaisatec** [deployd/deployd#559]
I hope to use  deployd to access the mongodb on compose.io(DBAAS)
mongodb on compose.io

>mongodb://<user>:<password>@kahana.mongohq.com:10016/myname

> mongodb://<user>:<password>@kahana.mongohq.com:10016/myname

I try to call
> dpd -P kahana.mongohq.com   

it reports error

> starting deploydV0.8.0...                                                                                                                                              

> Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. 

your comment welcome

**Comment by andreialecu** [comment]
Create a package.json and try a server.js with something like this in it:

https://gist.github.com/andreialecu/a563c9a5ab7fdd7dc02f (replace `process.env.MONGOHQ_URL` with your connection string)
