### ISSUE TITLE
Cryptic "db error" when saving data

### ISSUE THREAD

**Issue by planttheidea** [deployd/deployd#560]
I have had quite a bit of struggle setting up deployd via NodeJS module (likely due to being on Arch Linux), but I finally got an instance up and running. I was able to create new collections, however I could not actually add any data to those collections. I ran with DEBUG=* and get the following rather cryptic error (I generified the user / app names):

> router routing /users to /users +0ms
> db Error
>     at Object.&lt;anonymous&gt;(/home/user/localhost/app/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:42:24)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
 >    at Object.&lt;anonymous&gt; (/home/user/localhost/app/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/index.js:2:17)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10) +13ms

It then cascades into a 'Cannot read property "findOne" of undefined' error, but I know this is a consequence of the aforementioned DB error. Is there a way to investigate this error deeper? I find it odd I can create collections (which means it must be talking to the DB) but not add data to them.

**Comment by ipepe** [comment]
Could You try to see what is happening inside mongo? Maybe create some collection in deployd like 'todo list' and add property name, and checkout inside mongodb what is there, maybe try to add some record from Your database client?

**Comment by ericfong** [comment]
Is node + mongodb working in same machine?

Can try with some node + express + mongodb boilerplate repo

**Comment by andreialecu** [comment]
This is usually an error with your mongodb connection (wrong host, port, db name or auth). 

We need to better report these.

**Comment by andreialecu** [comment]
Fixed in #575
