### ISSUE TITLE
migrate mongodb to couchbase

### ISSUE THREAD

**Issue by kaisatec** [deployd/deployd#562]
one of my project uses couchbase as db server.
it is socket server.
http server I hope to use deployd as restful api server.
I hope they use same db server.
Thus I need to change the db of deployd from mongodb to couchbase.
I noticed most code concern mongodb are in db.js

Just wonder if I only need to change the code of db.js

your comment welcome

**Comment by ericfong** [comment]
I think the query and results from DB will be very different.
Only changing db.js may work but won't be nice enough.

**Comment by andreialecu** [comment]
@kaisatec you're welcome to try. Most of the db code is in db.js, but there are some things that are probably mongo specific in collection/index.js as well (such as $fields query, etc)
