### ISSUE TITLE
emit on delete does not work

### ISSUE THREAD

**Issue by shaggybb** [deployd/deployd#563]
Hello,

First of all, thank you for an impresive tool!

I am using deployd as node module and everything works well except emiting when an object is being deleted. In fact, the object has been perfectly deleted but it seems that dpd is not able to trigger this emit.

*Server side*
```javascript
//------------------
// SERVER SIDE
//------------------
// On Delete /conversations
if (!(me && me.id === this.user)) {
  cancel("Not authorized", 401);
}

emit('messages:deleted', this);
```

*Client side*
```javascript
//------------------
//CLIENT SIDE
//------------------
dpd.messages.del(id, function(result, err) {
    if (err) {          
        // error
    } else {
       // success
    }
  });

// test - listen emit 1
dpd.messages.on('deleted', function(item) {
    console.log(item);  
});

// test - listen emit 2
dpd.on('messages:deleted', function(item) {
    console.log('dpd.on - deleted', item);    
}); 

// test- listend emit 3
dpd.socketReady(function () {
    dpd.on('messages:deleted', function(item) {
      console.log('socketReady - deleted', item);     
    });
});
```

What am I doing wrong?

**Comment by andreialecu** [comment]
I have emits on delete in my application and everything seems to be working
properly.

Your code seems fine. Try making a separate repro project and if you can
duplicate it there attach it here and I'll take a look.

În Joi, 14 mai 2015 la 18:53 Ivan Rubio <notifications@github.com> a scris:

**Comment by shaggybb** [comment]
@andreialecu 

Lastly I have found the mistake. I had put emit('message:delete') in messages collection so listeners  dpd.messages.on('delete') does not work.

Changing emit to 'messages:delete' I can listen through dpd.on('messages:delete', fn) and dpd.messages.on('delete', fn).

Thank you for your time!
