### ISSUE TITLE
How to filter by logged user into 'on get' event

### ISSUE THREAD

**Issue by shaggybb** [deployd/deployd#564]
Hi,

I am newbie in this project so my doubt may be a very easy to solve :smile: 

First of all the environment, collections, and events:

#### Environment
* ubuntu 14.04
* nodejs 0.10.25
* deployd (as node module) 0.8.2
* mongo 2.4.9

##### messages
```json
{
	"type": "Collection",
	"properties": {
		"user": {
			"name": "user",
			"type": "string",
			"typeLabel": "string",
			"required": false,
			"id": "user",
			"order": 0
		},
		"body": {
			"name": "body",
			"type": "string",
			"typeLabel": "string",
			"required": true,
			"id": "body",
			"order": 1
		}
	}
}
```
#### users 
```json
{
	"type": "UserCollection"
}
```
##### messages on POST
```javascript
cancelUnless(me,"Not authorized", 401);
this.user = me.id;
emit('message:created', this);
```
##### messages on GET
```javascript
cancelUnless(me, "Not authorized", 401);
this.user === me.id; 
```

As you can see, I have tried to get list of message by logged user but this code doesn't work. I am able to disable messages list if user is not logged (cancelUnless ...)  but always I have to put {user: me.id} in dpd.messages.get and, personally, I think this is not quite clean. How can I filter by user in the server side?

**Comment by andreialecu** [comment]
Your userid comparison code in the get event needs to be wrapped in a
cancelUnless() call like the first line.

Remember that events are written in JavaScript too, your comparison there
simply does nothing useful by itself.
În Vin, 15 mai 2015 la 10:25 Ivan Rubio <notifications@github.com> a scris:

**Comment by ipepe** [comment]
```
cancelUnless( isMe(this.user_id), "Not authorized", 401);
```

**Comment by shaggybb** [comment]
@ipepe @andreialecu 

thank you for your replies. With the @ipepe reply it works very well.
