### ISSUE TITLE
User `onGet` event can break session handling

### ISSUE THREAD

**Issue by 0ff** [deployd/deployd#565]
This code here https://github.com/deployd/deployd/commit/26b9448ee4c89d4ce5d5b4f1b5eb30b99a125873#diff-a030694f2d36b54385439136636f4a74R101 results in a severely bad situation: The UserCollection runs `getUserAndPasswordHash` on an object that is returned by the `onGet`-Event on that UserCollection.

Think of the following event code:
```javascript
    hide(username);
```
-> getUserAndPasswordHash in this code would return a wrong result, the user would be logged out.

Internal code must not rely on the user's events output.

**Comment by Maddis1337** [comment]
+1

**Comment by andreialecu** [comment]
PR with fix at #574
