### ISSUE TITLE
deployd crashes with RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by parceval** [deployd/deployd#571]
I always get this crash:

POST /process/ RangeError: Maximum call stack size exceeded
    at Array.forEach (native)
    at wrapAsyncFunctions (/usr/home/user42/my_website/node_modules/deployd/lib/script.js:294:31)
    at /usr/home/user42/my_website/node_modules/deployd/lib/script.js:299:7
    at Array.forEach (native)
    at wrapAsyncFunctions (/usr/home/user42/my_website/node_modules/deployd/lib/script.js:294:31)
    at /usr/home/user42/my_website/node_modules/deployd/lib/script.js:302:7
    at Array.forEach (native)
    at wrapAsyncFunctions (/usr/home/user42/my_website/node_modules/deployd/lib/script.js:294:31)
    at /usr/home/user42/my_website/node_modules/deployd/lib/script.js:302:7
    at Array.forEach (native)
    at wrapAsyncFunctions (/usr/home/user42/my_website/node_modules/deployd/lib/script.js:294:31)
    at /usr/home/user42/my_website/node_modules/deployd/lib/script.js:302:7
    at Array.forEach (native)
    at wrapAsyncFunctions (/usr/home/user42/my_website/node_modules/deployd/lib/script.js:294:31)
    at /usr/home/user42/my_website/node_modules/deployd/lib/script.js:302:7
    at Array.forEach (native)

if i run a certain REST API call,
i am running node v0.12.2 and deployd 0.8.2 on  FreeBSD 10.0-RELEASE AMD64. Even after increasing the stack-size of node with --stack-size=524288 the error still happens. Looking into the source of script.js, it seems to me that the recursion in wrapAsyncFunctions() could be the problem. Maybe there is some process.nextTick missing or something.

**Comment by andreialecu** [comment]
Please share some relevant bits of code from your event.

**Comment by parceval** [comment]
console.log("processing gallery");

dpd.gallery.get(galleryId, function(gallery, failReason) {
    if (failReason) {
        error(failReason);
    }
    if (gallery) {

        if (turnId) {   // nur einen Turn processen
            console.error("turnid:", turnId)
            dpd.turns.get(turnId, function (turn, failReason) {
                if (failReason) {
                    error(failReason);
                }
                if (turn) {
                    make_thumbnail(turn, gallery);
                }
            });
        }
        else {  // ganze gallery updaten.
            // turnliste aus group lesen
            console.log('process/post for whole gallery for groupId', gallery.groupId)

            dpd.turns.get({groupId: gallery.groupId}, function (turns, err) {
                //console.log("turns: ", turns);
                if (err) {
                    console.log('error in process/post for whole gallery ', err)
                }
                for (var turn in turns) {
                    make_thumbnail(turns[turn], gallery);
                }
            });
        }
    }
});

This is the event which is called. The thing is that not even the first line (console.log) gets executed.

**Comment by andreialecu** [comment]
So if you remove everything but the console.log() line you get that error with no other code in the event?

Are you using dpd-event here? Or what is this /process you're posting to?

**Comment by parceval** [comment]
Yes i use dpd-event here. and if i just leave the one console.log() in there it still crashes.

**Comment by andreialecu** [comment]
What does your startup script look like? Did you modify the script context? Try to track down which module is responsible for this error, it looks like something is wrong with your configuration.

**Comment by parceval** [comment]
i am using forever.js with a simple script.
What do you mean by modifying the script context?
This is my start script:

    var deployd = require('deployd');
    
    var server = deployd({
      port: process.env.PORT || 8080,
      env: 'production',
      db: {
        host: 'localhost',
        port: 27017,
        name: '-deployd',
      }
    });
    
    server.listen();
    
    server.on('listening', function() {
      console.log("Server is listening");
    });
    
    server.on('error', function(err) {
      console.error(err);
      process.nextTick(function() { // Give the server a chance to return an error
        process.exit();
      });
    });

**Comment by andreialecu** [comment]
I suggest trying a fresh/bare project with just that event in it with the `console.log()` line and see if you can get it to run. There must be something else interfering.

But if you can get the simple project to reproduce the error please attach it here.

**Comment by parceval** [comment]
So i finally found the problem, i was adding the path module to the domain of the event, that was creating the "Maximum call stack size exceeded" error. As soon as i removed that from the events domain, the error disappeared.

**Comment by ericfong** [comment]
You means ``` var path = require('path') ``` will break the whole thing?

**Comment by parceval** [comment]
No not this line, but i added the path module to the domain variable of the event like this:

    domain.path = path

because i wanted to use path inside one of my events. But as soon as i add it to the domain, even an event which does nothig at all breaks the whole thing.

**Comment by andreialecu** [comment]
That's what I was asking about when I asked if you changed the script context.

You may use `var path = require("path");` right in that event instead.

**Comment by parceval** [comment]
Ok thanks for clearance, but why does it blow the stack when passed in the domain object to the event.

**Comment by andreialecu** [comment]
The reason for that is pretty complicated. 

It has to do with some magic deployd does to suppress returning a result from an event until all async methods are done. This is so you can do things like:

```javascript
// On GET
dpd.someothercol.get(...).then(function(res) { 
   this.othercoldata = res;
});
```

And the resulting JSON response will include `othercoldata`. It does it by monkey patching all methods it thinks are async and trying to count callbacks.

This magic is enabled for everything and only currently supported for internal classes so far, so I suggest not messing with the domain unless you really know deployd internals.
