### ISSUE TITLE
deployd 0.8.4 and dpd-passport 0.3.3 does not work

### ISSUE THREAD

**Issue by shaggybb** [deployd/deployd#581]
Hello,

I've upgraded my to use multple sockets by session and multiple sessions by user but now dpd-passport does not work with deployd 0.8.3 neither 0.8.4.

With a logged user through social network is correctly stored in database and appearently created a session but after that when I use dpd.users.me it returns an empty object

### Register a user from social network
* Call to HTTP://SERVER:PORT/auth/twitter 
* Twitter returns a user 
* dpd-passport store a user in database:
```javascript
            // new user
            debug('creating new user w/ profileId %s', profile.id, profile);
            saveUser.$limitRecursion = 1000;

            // will run deployd post events
            dpd[config.usersCollection].post(saveUser, function(res, err) {
                if(err) { return done(err); }

                // set the password hash to something that is not a valid hash which bypasses deployds checks (i.e. user can never login via password)
                userCollection.store.update({id: res.id}, {password: saveUser.password}, function() {
                    debug('created profile for user');
                    
                    // cleanup before responding
                    saveUser.id = res.id;
                    delete saveUser.password;

                    done(null, saveUser);
                });
            });
```
* dpd-passport store session
```javascript
        ctx.session.set(sessionData).save(function(err, session) {
            console.log(err, session);
            // apply the sid manually to the session, since only now do we have the id            
            ctx.res.cookies.set('sid', session.id, { overwrite: true });

            return sendResponse(ctx, err, config.disableSessionId);
        });
```
* app returns session object
```
{
    "id": "dsfsfsdfdsafdsfadsfas12312312asr41dsfadsr2342341dsfasrf234124sdefasdf",
    "path": "/users",
    "uid": "2131sdafsdf21312"
}
```

### Try to retreive logged user
* Call to HTTP://SERVER:PORT/index.html
* dpd.users.me returns an empty object

### Environment
monog 2.4.9
npm 2.10.1
node 0.12.4
deployd 0.8.4
dpd-passport 0.3.3

Can anybody help me?

**Comment by andreialecu** [comment]
Yes, dpd-passport is broken. There is a PR to fix it here:
https://bitbucket.org/simpletechs/dpd-passport/pull-request/7/fix-compatibility-with-deployd-084/diff

**Comment by andreialecu** [comment]
Paging @0ff :)

**Comment by 0ff** [comment]
Thanks for the pink @andreialecu :) But from the report it looks as if he's experiencing a different issue, isn't he? Redirect is not a problem, rather it seems the session cookie was not set?

@shaggybb can you please check the header of the response when you get the session object in the body? There must be a line `Set-Cookie: sid=....` (must be the same as id in the response) in there (set by `ctx.res.cookies.set('sid', session.id, { overwrite: true });`). Can you see it?

**Comment by andreialecu** [comment]
Actually, I was seeing the exact same problem @shaggybb mentioned with dpd.users.me() not working because the hash would not match any more due to: 

https://github.com/deployd/deployd/blob/master/lib/resources/user-collection.js#L104
(notice $fields query)

Not allowing this monkey patched method to work properly any more (sorry for breaking dpd-passport over and over :) ):
https://bitbucket.org/andreialecu/dpd-passport/src/8d9638694373cef8b27b6dbd36c226ff1c236039/index.js?at=master#cl-56

Thus, no user will be returned after logging in.

**Comment by shaggybb** [comment]
@0ff I've used @andreialecu PR in dpd-passport and it works fine.

The problems has been well-explain by @andreialecu at the previous comment. His PR seems to be the solution.

Thank you @andreialecu

**Comment by rgolea** [comment]
+1 @andreialecu thanks!
I added @andreialecu's PR and added a cleanup on the success/error callback so you don't have those parameters there.
https://bitbucket.org/simpletechs/dpd-passport/pull-request/8/feature-angularjs-url-cleanup/diff

**Comment by 0ff** [comment]
Update is live for `dpd-passport` (0.3.4), should resolve this issue.

**Comment by andreialecu** [comment]
Thanks @0ff
