### ISSUE TITLE
Can't we have mac installer again?

### ISSUE THREAD

**Issue by ahayder** [deployd/deployd#587]
I am very upset with the nasty process of installing deployd & mongo db in mac. At least a npm installer?

**Comment by ericfong** [comment]
```npm install -g deployd``` don't work for you ?

**Comment by ahayder** [comment]
Ya it worked! Then I installed mongo db separately. The deployd server also runs but mongodb don't work along with it so when I make a  resource and click save then it's not work. I have looked in many solutions but didn't work anything.

**Comment by rgolea** [comment]
Please use [this](https://github.com/rgolea/angular-deployd-admin/blob/master/app.js) to instanciate to that different mongodb instance.

I am going to close this. If you still have issues, please feel free to reopen it.
