### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by ktmn** [deployd/deployd#595]
When using Deployd as Express middleware (http://docs.deployd.com/docs/server/work-with-express.html), if I use

    app.use('/api', server.handleRequest);

instead of

    app.use(server.handleRequest);

when navigating to /api/dashboard/ the page basically doesn't work because it assumes it's located at http://127.0.0.1:3000/dashboard/  not http://127.0.0.1:3000/api/dashboard/ 

I need to "app.use()" a different handler for other stuff, and can't just stack them because handleRequest returns 404 if it isn't a Deployd related thing, not next().

Am I doing something wrong or? Any ideas/workarounds?

**Comment by ericfong** [comment]
Hi

We have a PR for that. but need works on that before it go to main branch.
Would you be able to help?

On Fri, Jul 3, 2015 at 11:10 PM, ktmn <notifications@github.com> wrote:

> When using Deployd as Express middleware (
> http://docs.deployd.com/docs/server/work-with-express.html), if I use
>
> app.use('/api', server.handleRequest);
>
> instead of
>
> app.use(server.handleRequest);
>
> when navigating to /api/dashboard/ the page basically doesn't work because
> it assumes it's located at http://127.0.0.1:3000/dashboard/ not
> http://127.0.0.1:3000/api/dashboard/
>
> I need to "app.use()" a different handler for other stuff, and can't just
> stack them because handleRequest returns 404 if it isn't a Deployd related
> thing, not next().
>
> Am I doing something wrong or? Any ideas/workarounds?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployd/deployd/issues/595>.
>



-- 
Best Regards,
Eric Fong

**Comment by ericfong** [comment]
https://github.com/deployd/deployd/pull/544

On Sat, Jul 4, 2015 at 11:55 PM, Eric Fong <ericff@gmail.com> wrote:

> Hi
>
> We have a PR for that. but need works on that before it go to main branch.
> Would you be able to help?
>
> On Fri, Jul 3, 2015 at 11:10 PM, ktmn <notifications@github.com> wrote:
>
>> When using Deployd as Express middleware (
>> http://docs.deployd.com/docs/server/work-with-express.html), if I use
>>
>> app.use('/api', server.handleRequest);
>>
>> instead of
>>
>> app.use(server.handleRequest);
>>
>> when navigating to /api/dashboard/ the page basically doesn't work
>> because it assumes it's located at http://127.0.0.1:3000/dashboard/ not
>> http://127.0.0.1:3000/api/dashboard/
>>
>> I need to "app.use()" a different handler for other stuff, and can't just
>> stack them because handleRequest returns 404 if it isn't a Deployd related
>> thing, not next().
>>
>> Am I doing something wrong or? Any ideas/workarounds?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/deployd/deployd/issues/595>.
>>
>
>
>
> --
> Best Regards,
> Eric Fong
>



-- 
Best Regards,
Eric Fong
