### ISSUE TITLE
automatically quit version 0.8.4 on OSX 

### ISSUE THREAD

**Issue by mapleeit** [deployd/deployd#599]
version 0.8.4
There is a problem that when I type `dpd` in the OSX terminal. It will automatically come out 
```
$ dpd
starting deployd v0.8.4...
listening on port 2403
type help for a list of commands
dpd > bye
```
I didn't enter Ctrl+c or other keys.

**Comment by andreialecu** [comment]
This is usually a problem with your `mongod`, make sure you have mongo installed.

**Comment by mapleeit** [comment]
I have installed `mongod`, but unfortunately. It still can't work well. Can you give me an URL which show how to install `deployd` correctly on OSX? Thank you so much

**Comment by mapleeit** [comment]
Ok, I got the answer [HERE](https://github.com/deployd/deployd/issues/524).
Use the `sudo dpd` and it worked.
May be the mongo can't create the file on the project folder if just use `dpd`.

This issue may close, thank you~

**Comment by ericfong** [comment]
Actually, I suggest we use ```npm install --save deployd``` + server.js instead of ```npm install -g deployd```

**Comment by ericfong** [comment]
I think problem come from 
https://github.com/deployd/deployd/blob/master/bin/dpd#L301
