### ISSUE TITLE
Cannot rename a resource

### ISSUE THREAD

**Issue by hamidabdulmalik** [deployd/deployd#610]
When you try to delete or rename a resource, deployd crashes

**Comment by docnoe** [comment]
Which version?
Which platform?
How about some more info about the error message?

**Comment by hamidabdulmalik** [comment]
The version is 0.8.4
Running on Ubuntu 14.04
![screenshot from 2015-07-21 18 03 24](https://cloud.githubusercontent.com/assets/340532/8813701/62e97d7e-2fd3-11e5-8177-328083f6d608.png)
![screenshot from 2015-07-21 18 04 50](https://cloud.githubusercontent.com/assets/340532/8813705/6cf1e7f2-2fd3-11e5-89b9-e9c182a92926.png)

**Comment by hamidabdulmalik** [comment]
I also caught this exception while deleting:

DELETE /__resources/tests TypeError: Cannot read property 'shift' of undefined
    at rmFile (/usr/local/lib/node_modules/deployd/node_modules/wrench/lib/wrench.js:382:33)
    at /usr/local/lib/node_modules/deployd/node_modules/wrench/lib/wrench.js:394:11
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by hamidabdulmalik** [comment]
Also dpd does not run when I am connected to my WiFi, I have to always disconnect from the network whenever I want to use it.

**Comment by docnoe** [comment]
Hi again. 
I was able to reproduce this error by tying to rename/delete a fresh and empty collection. 
The error means that mongodb does not have a collection with that name. My guess is that Deployd does not create a mongodb collection before the first item is added. 

Try inserting some bogus document and then again try to rename, or delete it.

As for your wifi problem I have no idea, sorry.

**Comment by NicolasRitouet** [comment]
Thanks to #648, the problem should be fixed.

If not, feel free to reopen this ticket and add more information.
