### ISSUE TITLE
wait for async function in "on get" event

### ISSUE THREAD

**Issue by hjanuschka** [deployd/deployd#611]
hello

i want to do something like this:

    var followers = process.server.createStore('follow');
    var self = this;

    followers.find({following: me.id,userId: this.id, $fields: {following: 1}}, function(err, result) {
            console.log(result);
            if(result && result.length > 0) {
                self.following=true;
             }
        });

and bypass the internal client - instead of using dpd.followers (i want to avoid, ifing all the business logic with `if(!internal)`, and make sure no event is fired on the query.)
the result is printed to the console, but the object key "following" is not availaible in the response json.

is there anyway to force the "on get", to wait for the .find() ? 

regards

**Comment by andreialecu** [comment]
This is in the latest master.

See the $addCallback/$finishCallback functionality added in PR https://github.com/deployd/deployd/pull/591

Feel free to test the master until a new release is created.

**Comment by hjanuschka** [comment]
nice one, and blazing fast reply - like that
now i have to figure out how i can get npm to install the latest master :dizzy_face: , nodejs noob

**Comment by andreialecu** [comment]
if you change your `package.json` to read `"deployd": "deployd/deployd"` instead of a specific version number, when you run `npm install` it will get from the latest master here on github.

**Comment by hjanuschka** [comment]
works

**Comment by hjanuschka** [comment]
ok update - on some collections "on get" event i get a 

    {
      "status" : 400,
      "message" : "$addCallback is not defined"
    }

any hint?

**Comment by ericfong** [comment]
please check your lib/script.js

see contains the new $addCallback function or not?

**Comment by hjanuschka** [comment]
thx for the hint, i had deployd installed with -g, and also without -g - i think i messed my folders up - after running the install command once with -g and once without -g it seems to work.

**Comment by coderofsalvation** [comment]
for whatever it's worth, i usually use these lines on older deployd versions:

```
var done = ctx.done
ctx.done = function(){}

// do async stuff
done({})
```
