### ISSUE TITLE
RecursionLimit doesn't actually count recursion?

### ISSUE THREAD

**Issue by dopry** [deployd/deployd#617]
Recursion limit isn't actually measuring stack depth, but number of calls to a specific URL. 

In my use case I have an story resource with an author property that is the id of an author resource.

story::OnGet says
```
var self=this;
dpd.author.get(self.author, function(author) {
  self.author = author;
});
```
If I am loading more than 2 stories, author is null.  The recursionLimit is in fact a call limit to /authors/:id, regardless of the stack depth.

Ideally the recursion would only limit a case where

author::onGet also said...
```
var self=this;
dpd.story.get({author: self.id}, function(stories) {
  author.stories = stories
});
```

**Comment by andreialecu** [comment]
You can work around this by specifying a higher `$limitRecursion` value in your query. See: http://docs.deployd.com/docs/collections/reference/querying-collections.html#s-$limitRecursion-1416

**Comment by rgolea** [comment]
Please feel free to reopen this issue if necessary.
