### ISSUE TITLE
Cannot npm install deployd : No compatible version found: socket.io

### ISSUE THREAD

**Issue by tianshuo** [deployd/deployd#619]
npm ERR! notarget No compatible version found: socket.io@'automattic/socket.io#93b571406e3d8f950d9132d3f88bc55d055a6b13'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.3.8","0.4.0","0.4.1","0.5.1","0.5.3","0.6.0","0.6.1","0.6.3","0.6.4","0.6.5","0.6.6","0.6.7","0.6.8","0.6.9","0.6.10","0.6.11","0.6.12","0.6.14","0.6.15","0.6.16","0.6.17","0.6.18","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","0.7.6","0.7.7","0.7.8","0.7.9","0.7.10","0.7.11","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.8.7","0.9.0","0.9.1","0.9.1-1","0.9.2","0.9.3","0.9.4","0.9.5","0.9.6","0.9.7","0.9.8","0.9.9","0.9.10","0.9.11","0.9.12","0.9.13","0.9.14","0.9.15","0.9.16","1.0.0-pre","1.0.0-pre2","1.0.0-pre3","1.0.0-pre4","1.0.0-pre5","0.9.17","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.1.0","1.2.0","1.2.1","1.3.0","1.3.1","1.3.2","1.3.3","1.3.4","1.3.5","1.3.6"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Darwin 12.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "deployd"

**Comment by Kvarkas** [comment]
You should got new package.json or edit existing one to:
"socket.io": "^1.3.6",

**Comment by wolfdogg** [comment]
maybe what Kvarkas is saying is it works otherwise.  i was able to install it via npm
sudo npm install deployd -g i believe.
it took some configuring.  
i got alot of errors to overcome, so sudo npm install include-all so you can bring up all dependencies to date if you have to.  

Then the trick show there is overcoming PATH issues, once you tackle that you start it with --mongod if you have ... 

Have you tried all that?

**Comment by Kvarkas** [comment]
Hello, issue is with package.json download it separately, ignore errors, put to same folder - do update - should be fine

**Comment by wolfdogg** [comment]
i dont believe so Kvarkas, i think the issue is with either the .npm directory permissions, where he needs to chown user:group -R on that directory , or dpd binary or its symlink needs to be added executable permission ugo +x to the binary.  is it /usr/bin/dpd?  forgot..

**Comment by Kvarkas** [comment]
I am windows user ;) I have issue until update package,json to correct versions and now its gone, so perhaps for *nix users its exist, cant check that now.

**Comment by NicolasRitouet** [comment]
@tianshuo is your problem solved?
If not, feel free to reopen the ticket and add more information.
