### ISSUE TITLE
File uploading

### ISSUE THREAD

**Issue by tianshuo** [deployd/deployd#62]
Uploads to a directory, and generates an url in the database

**Comment by sumomostudio** [comment]
The link given by ritch is broken, where can I find the latest info for 'file upload/download' examples(for common servers other than amazon's)? thank you in advance.
Really great work!

**Comment by NicolasRitouet** [comment]
I created a module for that:
https://github.com/NicolasRitouet/dpd-fileupload

Here's a demo:
https://github.com/NicolasRitouet/dpd-fileupload-demo

**Comment by sumomostudio** [comment]
Thank you!
I will take a closer look today!
:+1:
