### ISSUE TITLE
Scaling DPD

### ISSUE THREAD

**Issue by hjanuschka** [deployd/deployd#620]
hello

we plan to use a large DPD based app :)
we love dpd

there will be a big sharded/replicated mongo db cluster.
are there any guides on how to scale dpd?

currently i have the following idea:
mongodb sharded replicated cluster
N DPD instances (running as a docker container) - and in front of that a http loadbalancer wich splits up the request to the N dpd instances

would that work out?

regards
helmut

**Comment by ericfong** [comment]
Unfortunately, dpd are not designed for that. (Welcome for PR by the way)

For my personal experience, I will use koa + monk (parallel with dpd) when
need high performance.

On Wed, Jul 29, 2015 at 4:21 PM, Helmut Januschka <notifications@github.com>
wrote:

> hello
>
> we plan to use a large DPD based app :)
> we love dpd
>
> there will be a big sharded/replicated mongo db cluster.
> are there any guides on how to scale dpd?
>
> currently i have the following idea:
> mongodb sharded replicated cluster
> N DPD instances (running as a docker container) - and in front of that a
> http loadbalancer wich splits up the request to the N dpd instances
>
> would that work out?
>
> regards
> helmut
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployd/deployd/issues/620>.
>



-- 
Best Regards,
Eric Fong

**Comment by hjanuschka** [comment]
ok thats not so good, what are the common issues i will run into when scaling?
as i ve seen - i can run it with --databasePort etc... to connect to an existing mongo.

right now i have an prototype app - wich heavly relies on the onGet events and so on, so sticking with dpd is my prefered option.!

**Comment by andreialecu** [comment]
If your app is read heavy, then there is pretty much no overhead from using deployd and you should have no issues with the scenario you presented. If you have no state, and your API is fully REST compatible, then you can scale it to multiple machines easily. 

If you want to use emit(), the web sockets require state, so they won't scale across multiple servers right now, but support for it is definitely possible - it would require a PR.

**Comment by hjanuschka** [comment]
@andreialecu  ok that sounds good. - the app is fully REST compatible - and 90% reads vs. 10% writes.
right now i am not using the emit/websocket parts.
