### ISSUE TITLE
Deployd tries to load config.json from hidden folders in /resources

### ISSUE THREAD

**Issue by sigbjornt** [deployd/deployd#623]
It seems like hidden files in the resources folder are included in the list of folders where deployd expects to find configuration files. As we are still using subversion, this creates problems since there wil be a .svn folder in each directory. 

```
#./node_modules/.bin/dpd
starting deployd v0.8.4...

Error loading resources:
Error: Expected file: resources/.svn/config.json
    at /u01/test/node_modules/deployd/lib/config-loader.js:127:15
    at taskCallback (/u01/test/node_modules/deployd/node_modules/async/lib/async.js:468:21)
    at fs.js:208:20
    at Object.oncomplete (fs.js:108:15)

```

**Comment by ericfong** [comment]
OH ... 

do you have package.json 

if have package.json, it may work around that

**Comment by andreialecu** [comment]
As @ericfong said, try running `npm init` in your project folder and see if that solves it - this will create a package.json for you.

**Comment by sigbjornt** [comment]
I am unable to reproduce this in a consistent manner, so I guess the problem is on my end. Sorry for the interruption.
