### ISSUE TITLE
cancel() and $limit $skip

### ISSUE THREAD

**Issue by hjanuschka** [deployd/deployd#624]
hello

in my OnGet Event i do cancel() on some conditions, but this messes up the overall $skip, $limit
is there a solution for this, that paging with $skip, $limit and cancel() works?

regards

**Comment by hjanuschka** [comment]
i looked at the before request, but the cancel() is not a simple (field $ne) like @andreialecu  mentioned in 
https://github.com/deployd/deployd/pull/596

the cancel happens in the onGet if a record in another collection is not found:


    if(query.ifollow) {
        //Only show users i am following
        if(!me) {
            error("need to be logged in to view this");
            cancel();
        }
        
        
    
        dpd.follow.get({userId: me.id, following: self.userId,doNotResolve:true,  $limit: 1}, function(obj, err) {
            if(obj.length <= 0) {
                cancel();
            }
        });
        
        
        
    }


any chances this could be worked around so that limit and skip still work - because otherwise it is a huge request just for returning a small amount of records.

**Comment by andreialecu** [comment]
$limit and $skip work at the Mongo layer. There is no way to do what you want with custom logic without pulling the entire database - think about it.

I suggest you move your querying logic to a dpd-event which queries multiple collections and aggregates result/or rethink your schema. NoSQL databases should not be used like SQL - you cannot do traditional joins with 100% SQL compatibility. 

You may need to duplicate some data across collections and keep it in sync.

**Comment by hjanuschka** [comment]
thx for clarification - i know that the whole relational stuff in onGet is bad practice in a nosql scenario.
duplicating data  / and syncing it would be the best solution, but i am pretty much scared of the 16MB limit in my case!


in the example above - if a add all followers (by id) to each upload object, i am pretty sure i hit the 16 mb in short time.

i think i have to rework - the solution/structure

**Comment by hjanuschka** [comment]
ok thx - i am now using dpd-event with a even resource to fullfill my requirements :dancers: 

    var follow = dpd.follow.getResource().store;
    var uploads = dpd.uploads.getResource().store;
    
    var followers=[];
    //get followers
    
    
    var my_ctx = ctx;
    /*
    
    search_query.userId = me.id;
    search_query.$fields={following: 1};
    */
    if(!me) error("Need to be logged in");
    
        
    $addCallback();
    follow.find({userId: me.id}, function(err, obj) {
       if(err) {
           setResult(err);
           return;
       }
       obj.forEach(function(e) {
          followers.push(e.following); 
       });
      
      dpd.uploads.get({userId: {$in: followers}, $skip: ctx.query.$skip, $limit: ctx.query.$limit, $sort: ctx.query.$sort, $limitRecursion: 200}, function(uploads, err) {
           setResult(uploads);
       });
      $finishCallback();  
    });
