### ISSUE TITLE
Mongo Aggregations

### ISSUE THREAD

**Issue by kvdmolen** [deployd/deployd#625]
I'm trying to get Mongo to aggregate my data, but none is working.

I would expect this query to work, according to the [Mongo Manual](http://docs.mongodb.org/manual/reference/operator/aggregation/group/):

```javascript
dpd.collection.get({
   $group: {_id: {somename: "$dbfield"}  }
}, console.log)
```

Any thoughts? How about [Aggregations](http://docs.mongodb.org/manual/core/aggregation-pipeline/)?

Thanks!

**Comment by andreialecu** [comment]
Mongo aggregation is not directly supported, however, you could create a dpd-event and use the functionality added in this PR:

https://github.com/deployd/deployd/pull/608

An example:

dpd-event On GET:

```javascript
if (parts[0] === "my-group") {
   $addCallback(); // direct mongo callbacks are not automatically handled, we need to do increase the callback counter manually
   dpd.collection.getResource().store.getCollection().then(function(col) {
     col.find({
       $group: {_id: {somename: "$dbfield"}  }
     }, function(err, data) {
       if (err) return cancel(err);
       setResult(data);
       $finishCallback();
     })

```
