### ISSUE TITLE
Dashboard type dropdown is sortable like the properties

### ISSUE THREAD

**Issue by kwantum0** [deployd/deployd#629]
### Description
In the properties panel of a collection, all datatype dropdowns are sortable. You can click-drag and rearrange the types, something causing them to disappear and empty properties to be added to the collection. (This also breaks the data panel of the collection).

### Examples:
http://imgur.com/a/iFGH3

Sortable datatype list items, that disappear on rearrangement
![Sortable](http://i.imgur.com/Wvff0CA.png)

Random junk property that appears after sorting
![Funny Property](http://i.imgur.com/Q5pQ3z9.png)

What the property looks like when you save and come back
![Empty Property](http://i.imgur.com/wOI9QVQ.png)

A broken data panel if you let the empty property name persist
![Broken Data Panel](http://i.imgur.com/hUwnDD0.png)

**Comment by kwantum0** [comment]
I've encountered this bug in:
* firefox 39.0
* chrome 44.0.2403.130 m
* ie 11.0.9600.17914

I'm using deployd v0.8.4

**Comment by Kvarkas** [comment]
Could you please update to new version? On deployd v0.8.5 I was unable to reproduce that.

**Comment by kwantum0** [comment]
I downloaded the latest zip,
and in bash i did:
`cd deployd-master`
`npm install`
`cd test-app`
`dpd --mongod "C:\Program Files\MongoDB\Server\3.0\bin\mongod.exe"`

but even the test app had the same problems:
http://imgur.com/a/OJxmd

My environment isn't special,
Just Windows 7 Professional SP1.

**Comment by Kvarkas** [comment]
I will try to look into that on weekend, I think its related to dashboard skript files only

**Comment by docnoe** [comment]
Was actually very easy to fix, PR is pending...
