### ISSUE TITLE
Log requests in debug mode

### ISSUE THREAD

**Issue by pensierinmusica** [deployd/deployd#631]
Hi,

I'm debugging a problem that I have with Deployd working behind a proxy. It would be useful if I could see a real-time log of the HTTP requests that the Deployd server receives. I wonder if it would be possible to have a "debug" mode (through some flag like `dpd -debug`) that logs these events in Terminal.

Thoughts? Thanks!

**Comment by andreialecu** [comment]
Deployd uses [debug](https://www.npmjs.com/package/debug). Set the `DEBUG` env variable to `*` and you will get some internal debug output.

**Comment by pensierinmusica** [comment]
Thanks! Shall we include this piece of info in the docs?

**Comment by docnoe** [comment]
This could be closed, no?

**Comment by pensierinmusica** [comment]
Shall we include this information in the docs?

**Comment by docnoe** [comment]
@pensierinmusica Somehow I didn't see your last comment, sorry! 
You're absolutely right, this should be in the docs. 
My first thought was to put it in the "developing modules" section as this is where most people would use/need it. Nevertheless, some might just want to see what Deployd is doing in the background (as we can see at your proxy problem). 
So maybe it's better to just put a little note somewhere right at the beginning of the docs. Maybe at ["your first Deployd API"](http://docs.deployd.com/docs/getting-started/your-first-api.html) ?

**Comment by pensierinmusica** [comment]
Mmm, makes sense... we could explain how debugging works in one of these two sections:
- "[Using the dpd command line tool](http://docs.deployd.com/docs/basics/cli.html)"
- "[Creating a Module](http://docs.deployd.com/docs/developing-modules/creating-modules.html)"

And then just put a reference (link) to it in "[Your first Deployd API](http://docs.deployd.com/docs/getting-started/your-first-api.html)".

This way the information is available in both cases. Let me knwo your thoughts and how you'd like to proceed. Cheers  :)

**Comment by NicolasRitouet** [comment]
@pensierinmusica I agree 100% with your proposition :+1: 
If you can send a PR to improve the documentation, that would be awesome! :trophy:

**Comment by pensierinmusica** [comment]
@NicolasRitouet, done  :)

**Comment by NicolasRitouet** [comment]
Great, I love PR for documentation!
Thanks a lot @pensierinmusica :+1:
