### ISSUE TITLE
Fields with underscore (_) like user_id

### ISSUE THREAD

**Issue by tb** [deployd/deployd#635]
The UI does not allow me to use names with underscore (_) like "user_id", through it works when I change it via resource config.json

**Comment by ericfong** [comment]
_ is not js naming conversion, right?

**Comment by tb** [comment]
Why would you restrict API building tool to js naming conversion?

**Comment by safaorhan** [comment]
Any improvements on that?

Think about the case user may want to store data coming from external sources, like facebook graph api.

Since there is created_time and fields name like that, we should be able to use underscores in the field names.

**Comment by anugrahsulaeman** [comment]
@safaorhan You can directly modify config.json in your resource/[collection_name] folder if you really want underscore name

example:
`
{
	"type": "Collection",
	"properties": {
		"created_time": {
			"name": "created_time",
			"type": "string",
			"typeLabel": "string",
			"required": false,
			"id": "created_time",
			"order": 0
		}	
	}
}
`

**Comment by NicolasRitouet** [comment]
Since we'll be working on a new dashboard (https://github.com/deployd/deployd/issues/764), we could add this.

**Comment by kkrishnan90** [comment]
Is this added to the new dashboard yet ? I don't see any evidence of this on the new dashboard ? @Nicholas

If not pls guide me so that I can include them in the new dashboard and float across a PR to you. Kindly let me know which file to modify. I've been trying to work around with this entire day, wasn't able to figure out where to change.

**Comment by kkrishnan90** [comment]
Ok, so I figured out this and have a way to handle it right now. All I have to do is to modify the file inside the ```node_modules``` folder and now it allows me to set ```_```(underscore) in my field names.
For some one who's looking to implement it.Here's the steps to be followed 

1. Create a deployd project. Run the project as you would normally run.
2. Stop the server.
3. Go through the ```YOUR_PROJECT/node_modules/deployd/lib/resources/collection/dashboard/js/util/knockout-util.js``` directory and open the file and replace this bunch of codes that I give you here,

Basically, there's a key binding event that happens on each of your keyevent to the properties while naming them on the dashboard. The keyevent checks for the value and there's a regex that accepts only numbers, lowercase and uppercase characters (no underscore or any other foreign keystroke shall be recognised here). 
So we need to modify this function (to be precise the regex pattern) to accept the ```_``` (underscore)

```
ko.extenders.variableName = function(target) {

  target.subscribe(function(newValue) {
    console.log('New Value : ', newValue);
    newValue = newValue.replace(/[^A-Za-z0-9]/g, '');  /*CHANGE THIS LINE to [^A-Za-z0-9_] thus making the pattern accept underscore as a literal character*/ 
    target(newValue);
  });

  return target;

};
```
There you go ! 
4. Now restart the server and check by adding a new property to the resources. It will now accept underscore.
@NicolasRitouet  If you want you can edit the same and release a new commit. Else I shall send a PR for your acceptance. 

Kindly confirm the same and hope this helps someone who's badly looking out for a solution (like myself) 😄
