### ISSUE TITLE
Bug: can't create users!

### ISSUE THREAD

**Issue by guyskk** [deployd/deployd#638]
### can't create users if I generate username on events

I am test on Postman(chrome-extension), set Content-Type:application/json;

POST
```json
{
    "nickname": "131",
    "email": "131",
    "firstname": "131",
    "lastname": "131",
    "password": "3131"
}
```
and I generate username on validate event.

```javascript
this.createtime = new Date().toISOString();
var n=Math.floor(Math.random()*10000+10000);
this.username=n.toString();
```
also I add `console.log("----on xxx");` to the top of each event.

When the users collection has no data, it success,**otherwise it return errors and didn't print any message** on my console:

```json
{
    "errors": {
        "username": "is already in use"
    },
    "status": 400
}
```
but if I add ` "username": "" `,

POST
```json
{
    "username": "",
    "nickname": "131",
    "email": "131",
    "firstname": "131",
    "lastname": "131",
    "password": "3131"
}
```
it aways success,
```json
{
    "email": "131",
    "nickname": "131",
    "firstname": "131",
    "lastname": "131",
    "username": "19503",
    "createtime": "2015-08-18T04:33:22.961Z",
    "id": "01e6352231a018e2"
}
```

**Comment by rgolea** [comment]
You might want to use [dpd-event](https://www.npmjs.com/package/dpd-event) module to replace the username.
