### ISSUE TITLE
type-loader/config-loader loading all modules on each request

### ISSUE THREAD

**Issue by hjanuschka** [deployd/deployd#641]
hello

is it true, that on every get request all plugins/configs are loaded?

i am currently trying dpd-express -> and obvisiouly on every request (even one that does not belong to the resource created for the Express module) - calls the Express.handle - and that calls the init script. wich results in a freshly created "app" (express) instance, even if not required.

is that expected behaviour?
the modules are even loaded freshly on serving static files.

will that be scaling issues ?!

@andreialecu am i doing something wrong here?

edit: using lates master commit.

regards

**Comment by hjanuschka** [comment]
ok nevermind, i forked dpd-express, and removed the .load function
changed the self.path (to not run on all resources) - and moved the app intialization to the resource .handle :)

now dpd-express only handles requests assigned to the resource

**Comment by NicolasRitouet** [comment]
Looks to be solved to me, feel free to reopen the ticket if necessary.
