### ISSUE TITLE
fs:missing callback Error: EPERM, 'C:\Program Files <x86x>\Deployed\node_modules\deployed\.latestversion'

### ISSUE THREAD

**Issue by amitabhaghosh197** [deployd/deployd#676]
I have Windows8 and 64bit and have installed the Deployed following the instruction. I have created a project as guided. But when I am typing in cmd  cd maps it is giving error command as mentioned below:

                                  
 C:\Users\ADITYAM GHOSH\maps>dpd -dstarting deployd v0.8.0...        listening on port 2403            type help for a list of commands  dpd >fs:missing callback Error: EPERM, 'C:\Program Files <x86x>\Deployed\node_modules\deployed\.latestversion'

So after going the the deployed folder under node_modules I can't see the .latestversion.

Please help me what I am going wrong.

Thanks in advance.

**Comment by NicolasRitouet** [comment]
You need to update to 0.8.5, this issue has been fixed with d8a507d5
