### ISSUE TITLE
Error Message - "Error Saving Event - Cannot convert undefined or null to object" while updating 'Events' under collections 

### ISSUE THREAD

**Issue by rahulakash** [deployd/deployd#677]
Hello,

I am a newbie to Deployd, trying to setup Deployd as a backend for my application. Lately I have been getting the error message "Error Saving Event - Cannot convert undefined or null to object"  when I try to edit or write a new event emitter under 'on put/on post' in the collection dashboard. It would be really helpful if anyone can point me out on how to solve this error. I have included the error message for reference. 

Any kind of help is highly appreciated!

Thank you!

![event_error message](https://cloud.githubusercontent.com/assets/6896985/10947347/6ed24eca-82f5-11e5-898d-75afb5d9c48c.png)

**Comment by rgolea** [comment]
Hi! Can you give me more info on this error? Does it still appear?

**Comment by rahulakash** [comment]
It seems to be resolved with the update. Thank you!
