### ISSUE TITLE
Deployd keygen has no effect?

### ISSUE THREAD

**Issue by daslicht** [deployd/deployd#679]
Hello, 
I have followed the following instructions:
http://docs.deployd.com/docs/server/your-server.html#s-Dashboard%20Access-2728

But after restarting with *dpd* I am not asked to enter a key ?

What am I missing please?

**Comment by thomasbreitbach** [comment]
Do you running dpd in production mode?

**Comment by daslicht** [comment]
Ahh, no anything default. That note would be nice if also placed at the Access Section :)
