### ISSUE TITLE
deployd project gets invalid 

### ISSUE THREAD

**Issue by daslicht** [deployd/deployd#681]
Hello,
I have locally (osx 10.11.1, dpd 0.8.7) followed the simple comments tutoria which worked like a charm.

But after some time? It got invalid without changing any file.

The Folder structure looks now like this:
![broken](http://i.imgur.com/HcnGsBF.png)

Notice the t folder? I have never created it manually  !
Before it got corrupted it supposed to be the name property

**Comment by NicolasRitouet** [comment]
do you still have the issue?
If yes, please, reopen the ticket.
