### ISSUE TITLE
messy word when data's value is chinese

### ISSUE THREAD

**Issue by zhoujiantao** [deployd/deployd#684]
How to change db encoding when data's value is chinese?thanks

**Comment by ericfong** [comment]
I think string stored in utf-8. And chinese should be ok

On Tue, Nov 24, 2015 at 9:23 AM, zhoujiantao <notifications@github.com>
wrote:

> How to change db encoding when data's value is chinese?thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployd/deployd/issues/684>.
>



-- 
Best Regards,
Eric Fong

**Comment by rgolea** [comment]
Any more updates on this? Can we close this issue?
