### ISSUE TITLE
GeoJson / 2dSphere / 2d indexes querying

### ISSUE THREAD

**Issue by Mortgy** [deployd/deployd#686]
I'm trying to query location over HTTP "2d" field, but it doesn't seem to recognize my parameters at all, my query like
{ location :
{ $geoWithin :
{ $center : [[100,100], 10]
} } }

Query : /collectionName?{"location":{"geoWithin":{"$center":[[100,100],10]}}}

when i use it on Robomongo it retruns data correctly with location based sorting, but when i use it through URL , i just get all objects in collection regardless whatever parameters i sent for location field, any suggestions ?
thanks in advance

**Comment by rgolea** [comment]
I think there might be 2 problems:
1.  query should be /collectionName?{"location":{"$geoWithin":{"$center":[[100,100],10]}}}
2. I'm not sure by default you can access those kind of parameters. If you can, no problem, if not, create a resource that handles that for you. See #625

**Comment by rgolea** [comment]
Found answer. The `dpd.collection.get()` does not support `$geoWithin` nor `$geoNear`. #625 is the solution you might want to find.

**Comment by rgolea** [comment]
Feel free to open this if needed.
