### ISSUE TITLE
Deployed Crash on RangeError: Invalid string length

### ISSUE THREAD

**Issue by mobi-life** [deployd/deployd#687]
Hi
I use deployd in a production space , but in some special conditions it crashes with the error that I mentioned blow.
Deployd Version : **v0.8.7**
MongoDB : **v3.0.7  64bit**
NodeJS : **v5.0.0**
Server : **Dedicated , Ubuntu 14.04 , 32GB RAM , CPU 3.7GHz 8 cores.**
Crash Condition:
Server works well in normal traffic , but when a little traffic grows and RAM usage reaches about 3-9GB  , deployd server crashes frequently by printing this error message on log output. Important point is that in this situation , operations related to database doesn't work anymore and it is a thing like that mongodb hangs and doesn't respons nonethles deployed administration panel responses and opens very well , but doesn't load collection resources into table anymore , and also queries from application doesn't response and doesn't work too. I tried to solve this by puting that line of error inside a try/catch , by doing this crashes stopped , but again the problem of mongodb hanging and loading collections still exists and I know putting try/catch is not the right solution and main problem is in another place. I think I have enough server resources to handling relatively huge requests and my queries inside deployd are not like that huge and heavy that this server can't handle!!!. When this crash happens there is average 200 query call per second.

Please guid me how can I solve this problem , where should I search for the problem , I know a little NodeJs programming and I just need your guid about deployd. If you need more explanation about crash condition let me know.

I hope this problem be solved in next deployd version.

Thank you.

Crash Error:

**RangeError: Invalid string length
    at Socket.<anonymous> (/home/user1/myproject/node_modules/deployd/lib/util/mongod.js:41:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)**

**Comment by andreialecu** [comment]
It seems like you are using the `dpd` command to start your server. 

For production, I would suggest creating a custom start script and running `mongod` separately. If the error still occurs, it might be easier to see what is causing it.

You can use this as a template for your startup script:
https://gist.github.com/andreialecu/a563c9a5ab7fdd7dc02f

**Comment by mobi-life** [comment]
Thank you for fast reply and checking the issue. 
Actually I have my own script to run deployd and I use **PM2** for managing its process and restarting server when it crashes  and I get above error message in **PM2** log output . But again I will try the script you mentioned above too. **PM2** provides clustring in NodeJs so it runs and manages 8 instances of my script at same time(because cpu has 8 core) , so I made my own script from deployds original run script that exists in deployd package , my version checks wether if mongodb process is running or not , if mongodb running it will not start mongodb multiple times so it prevents errors and crashes because of clustering and multiple runscript instances. 
**My script run command :**
```
sudo pm2 start project.js --node-args="--max-old-space-size=30720" -l pm2.log -i 0 --max-memory-restart 30720M
```
**My script :**
```
var deployd = require('deployd');
var mongod = require('deployd/lib/util/mongod');
var Server = require('deployd/lib/server');
var  path = require('path');
var shelljs = require('shelljs/global');
var fs = require('fs');

var myFile = "project/app.dpd";

try{ 
	require('events').EventEmitter.defaultMaxListeners = Infinity;
}catch(ex){}

function start(file) {
  var port = 1212
    , host =  '127.0.0.1'
    , dbname = '-deployd'
    , mongoPort = 27017
    , env = 'production'
    , retries = 20
    , credentials
    ;

  if (!port) {
    port = 1212;
    retries = env === 'production' && 20;
  }


  if (file) {
    process.chdir(path.dirname(file));
  }
  if (test('-f', 'app.dpd')) {


    if (!test('-d', './.dpd')) mkdir('-p', './.dpd');
    if (!test('-d', './.dpd/pids')) mkdir('-p', './.dpd/pids');
    if (!test('-d', './data')) mkdir('-p', './data');

	var now = process.hrtime()[0];
	var lastTime = fs.readFileSync('lastTime.json');
	var diff ;
	if(lastTime)
		diff = now - lastTime;
	
		if(isMongodAlive()) {
            console.log("---------------- Mongod is Alive-----------"); //mongodb process is running so we dont start it from scratch and just connect to it
            setTimeout(startup, 5000);
        }
		else {
            console.log("xxxxxxxxxxxxx Mongod Is Not Alive xxxxxxxxxxxxx"); //mongodb process is not runing so we start its service
            mongod.restart('mongod', env, mongoPort, startup);
        }

  } else {
    console.log("This directory does not contain a Deployd app!");
    console.log("Use \"dpd create <appname>\" to create a new app");
    console.log("or use \"dpd path/to/app.dpd\" to start an app in another directory");
    stop(1);
  }

  function startup (err) {
      if (err) {
          console.log("behzad : " + err);
        console.log("Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deployd.com/docs/basics/cli.html)");
		return stop(1);
      }

	  
	  
      var options = {port: port, env: env, db: {host: host, port: mongoPort, name: dbname}};

      options.env = process.env.DPD_ENV || options.env;
      if(options.env !== 'development') console.log('starting in %s mode', options.env);

      if(credentials !== undefined) options.db.credentials = credentials;
	  console.info('Starting Server In ' + env + ' Mode...');
      var dpd = createServer(options);
      dpd.on('listening', onListening);
      dpd.on('error', onError);
      dpd.listen();

      function onListening () {
        console.info('listening on port', options.port);
      }

      function onError (err) {
        if (err.code === "EADDRINUSE") {
          console.error();
          console.error("ERROR: port " + options.port + " is already in use");
          if (retries > 0) {
            options.port++;
            console.log("Trying again on port " + options.port + "...");
            console.log();
            retries--;
            dpd = createServer(options);
            dpd.on('listening', onListening);
            dpd.on('error', onError);
            dpd.listen();
          } else {
			  process.exit();
          }
        } else {
          console.error(err);
		  process.exit();
        }
      }
    }
	

}
function isMongodAlive(){
		var pid;
		pid = fs.readFileSync('./.dpd/pids/mongod');
		
		if(pid && pid!='')
		{
			pid = JSON.parse(pid);
			if(test('-d', '/proc/'+pid))
				return true;
		}
		return false;
	}
function createServer(config) {
   var server = new Server(config);
  server.options = config;
  return server;
}

start(myFile);


var gcInterval = setInterval(function(){
    if(global.gc){
		global.gc();
	}
}, 1000 * 30);
```

**Comment by hamidabdulmalik** [comment]
This is the most interesting I have ever read here. @mobi-life please let us know what went down after running the script. Thanks

**Comment by mobi-life** [comment]
You're welcome.
After running the script in 8 clusters it works very well and 8 instances of deployd , processes the requests coming from clients. But the problem is when the ram usage reaches about 10%~30% of RAM , so deployed frequently crashes about every 30 minutes and output log shows the above error message that I mentioned in the first post . I don't think the problem is the run script because it works normal and well until the condition I have said , I pasted the script here just because maybe some one else wants to use it in own project.
As the error says it seems that it receives a very long string as I guess . The error happens in the file **node_modules/deployd/lib/util/mongod.js** at this part of the code ,  and I made the error line bold here : 
```javascript
  var proc = spawn(mongod, options, {title: 'FOOBAR', stdio: 'pipe'})
    , buf = '';
  proc.stdout.on('data', function(data) {

    buf += data; //------- The crash happens here! ----------

    if(~buf.indexOf('waiting for connections on port')) {
      proc.emit('listening');
    }
    debug(data);
  });
```
I put that line in try/catch but it just prevent deployd crashes and the problem of mongodb hanging and loading data still remains and when the traffic of server is high mongodb doesn't response.
I guess we should do something like preventing "data" variable from containing very long string before it reach to inside this function. I don't know how deployd architecture works maybe there is better solution , I don't want to take your time to solve this , I just need a guide from you professionals then I will do a research and solve it. What do you think about main source of this error ?

**Comment by andreialecu** [comment]
Running the dpd command in a cluster is a bad idea. It is starting multiple Mongo processes on the same db file. Use a start script like the above and start Mongo separately.

**Comment by mobi-life** [comment]
You are right , but as I said above I used a simple strategy in my script to preventing multiple Mongo processes , and also said even by 8 instances of running scripts , one of instances starts Mongodb just one time and other 7 instances automatically detect it running Mongodb and just make connection to the Mongodb and not start new one . And also please read my code there isn't any dpd command , it starts deployd by "deployd" module and runs mongodb automatically . Again I say every 8 instances working good until that condition that I mentiond above happens.
I don't have any problem in running clusters or even run script of deployd , my problem happens in the file that I mentiond above!!!

**Comment by andreialecu** [comment]
Right. I'm on mobile so I guess I didn't read carefully enough. However I still think you should let Mongo run separately and not worry about that file at all. If you make a run script like I specified, the error cannot happen in that file since it is not used.

**Comment by mobi-life** [comment]
It is a nice idea ! I didn't thought from that view point .
But even if this idea works , then downside will be this , when server hardware restarts each time I should run mongodb manually!
Thanks for giving this idea , I will try the idea and put the result here.

**Comment by rahulakash** [comment]
@mobi-life Interesting idea. Please update on your change and outcome. Thank you.

**Comment by mobi-life** [comment]
Now I wrote 2 script , one for runing and keep running the mongodb process and other one is a modified script of the script that @andreialecu gave the link . first script runs the mongodb just once and independent of deployd processes , and second one can run the deployd as a single process or in clusters that all of them will connect to one mongodb process. I think this strategy were the best way for running deployd in production mode until now, it solved the problem of server crashing problem with the error message that I have mentioned in first post , but still there is a **BIG** problem remaning and it is hanging of mongodb and it goes to coma after a while!!! , I will explain it in continue of this post .
Script for starting mongo db : 
```javascript
var  path = require('path');
var shelljs = require('shelljs/global');
var fs = require('fs');
var spawn = require('child_process').spawn;


if(isMongodAlive()) {
        console.log("---------------- Mongod is Alive-----------");
}
else {
        console.log("xxxxxxxxxxxxx Mongod Is Not Alive xxxxxxxxxxxxx");
        runMongoDb();
}

function runMongoDb(){

	var cmd = 'mongod --dbpath="./data" --pidfilepath="./.dpd/pids/mongod" --port="27017" --journal --smallfiles --nssize="4"';
	exec(cmd, function(error, stdout, stderr) {
		// command output is in stdout
	});
}

function isMongodAlive(){
		var pid;
		pid = fs.readFileSync('./.dpd/pids/mongod');
		
		if(pid && pid!='')
		{
			pid = JSON.parse(pid);
			if(test('-d', '/proc/'+pid))
				return true;
		}
		return false;
}

```

and second script for running deployd instances : 
```javascript
var deployd = require('deployd');
var  path = require('path');
var shelljs = require('shelljs/global');

var serverOptions = {
  port: process.env.PORT || 1333,
  env: 'production',
  db: {host: '127.0.0.1', port: 27017, name: '-deployd'}
};

// configure database etc. 
var server = deployd(serverOptions);
console.log("server starting");
// start the server
server.listen();
console.log("server started");
// debug
server.on('listening', function() {
  console.log("Server is listening on port: " + (process.env.PORT || 1333));
});

// Deployd requires this
server.on('error', function(err) {
  console.error(err);
  process.nextTick(function() { // Give the server a chance to return an error
    process.exit();
  });
});

```

even by these new changes the problem of mongodb hanging exists , as I said server works well and responses good until the memory usage is about lower than 10% as you can see at this picture , the memory usage is on 4% of 31GB : 
![normaltraffic](https://cloud.githubusercontent.com/assets/13516509/11761147/88c7c71c-a0cb-11e5-9f4d-852bf0087181.png)
but the times that traffic grows and memory usage goes higher than 10% mongodb doesn't work and response even by existing enough memory and cpu resources , as you can see here mem usage is 34% of 31GB  and doesn't load data of collections :
<img width="482" alt="hightraffic" src="https://cloud.githubusercontent.com/assets/13516509/11761160/4ff46b06-a0cc-11e5-805d-53d59f2297c1.png">

It is interesting that even in high traffic times deployd panel loads very well , it opens very fast but doesn't load data of collections that were created in deployd , even the data doesn't load by the queries that the application sends to the server , you can see in this picture the deployd panel opend in high traffic times very well but it wasn't able to load data even by many refreshes  : 
<img width="593" alt="hightraffic_notloading" src="https://cloud.githubusercontent.com/assets/13516509/11761179/25451472-a0cd-11e5-9a39-051dc0504e80.png">

I'm very confused , some thing here is working wrong ! , which one can be possible ?
1. I did a wrong configuration and wrong start script again. (if it's true , then what is the solution)
2. there is a problem and performance issue between internal connections of deployd to mongodb.
3. there is a problem with mongodb itself and it doesn't work well !

please let me know your oponion about this problem , I bet it is the problem of many people who are using deployd or will use it in the future .

**Comment by hamidabdulmalik** [comment]
@mobi-lifeIf you are on Facebook and Twitter, please leave your contact info as well as Gmail. I would love to be in direct contact with you and learn some stuff. Thank you

**Comment by andreialecu** [comment]
@mobi-life. that seems like a memory leak somewhere. Can you explain what you mean by high traffic? What numbers does that mean?

The process shouldn't ever get that high in memory usage. Are you using just plain old deployd collections or do you have any custom events/other code that could have memory leaks?

**Comment by mobi-life** [comment]
@hamidabdulmalik you can find me on twitter by this ID "bdeveloper2015"
@andreialecu I have about 600K users and 300K daily active users , at mornings the traffic is low but by closing to night it increases. when I say high traffic I mean I have about 300-400 active user per sconde , and as "mongostat" command shows there is average 60~100 query per second that I think it is not too much !!
this mongostat picture is captured when memory usage is about 70% : 
<img width="587" alt="mongostat" src="https://cloud.githubusercontent.com/assets/13516509/11762544/94ea72ae-a0ff-11e5-990e-15e4ce999f29.png">
as you see there isn't even insert and delete queries just select and some rare update queries happen.

the picture that I put in previous post about deployd panel was plain old deployd collection that werent able to load data to table, by the way I use these modules too : dpd-beforeget , dpd-event , dpd-event-extension.
But again I should say even when you want to just work with plain old collections deployd can't respond to queries .

**Comment by ericfong** [comment]
Actually, for high traffic site, I suggest you take a look on koa + monk.

I face similar traffic problem for deployd. deployd is good for bootstrap
to mid-traffic.

But for scale up, I choose to migrate API to koa which is more on-you-own
but more control over all kind of things.

Hope that work

On Sat, Dec 12, 2015 at 11:16 PM, mobi-life <notifications@github.com>
wrote:

> @hamidabdulmalik <https://github.com/hamidabdulmalik> you can find me on
> twitter by this ID "bdeveloper2015"
> @andreialecu <https://github.com/andreialecu> I have about 600K users and
> 300K daily active users , at mornings the traffic is low but by closing to
> night it increases. when I say high traffic I mean I have about 300-400
> active user per sconde , and as "mongostat" command shows there is average
> 60~100 query per second that I think it is not too much !!
> this mongostat picture is captured when memory usage is about 70% :
> [image: mongostat]
> <https://cloud.githubusercontent.com/assets/13516509/11762544/94ea72ae-a0ff-11e5-990e-15e4ce999f29.png>
> as you see there isn't even insert and delete queries just select and some
> rare update queries happen.
>
> the picture that I put in previous post about deployd panel was plain old
> deployd collection that werent able to load data to table, by the way I use
> these modules too : dpd-beforeget , dpd-event , dpd-event-extension.
> But again I should say even when you want to just work with plain old
> collections deployd can't respond to queries .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployd/deployd/issues/687#issuecomment-164160588>.
>



-- 
Best Regards,
Eric Fong

**Comment by mobi-life** [comment]
@ericfong thank you for your good suggestion , I'm started writing and testing my own API using expressjs and maybe try and test koa too , but it is a big sadness that we can't use deployd in practice! , after many researches about opensource baas systems I decided to use deployd because of its wonderful dynamic abilities but now in this point it stopped me and itself became a big issue in my project.
By the way I want to share here one more info about performance issue of deployd , maybe it help developers to solve it in next versions.
I had about 200k record in one of my collections , in post event I made a get to the same collection to do some check and then let it to add new record. in this condition the result of mongotop shows that collection is involved too long time about 5 seconde and causes mongodb and then deployd doesn't response to queries fast : 
<img width="455" alt="mongotop_before" src="https://cloud.githubusercontent.com/assets/13516509/11864859/250f7826-a4b5-11e5-9a4d-23101be5aff4.png">

I decided to remove all records of that collection and check it again , and after cleaning collection the speed of responses became better and deployd were able to load data in its panel easily , as you see the time that mongodb were involve in collection is reduced to 1 second : 
<img width="433" alt="mongotop_after" src="https://cloud.githubusercontent.com/assets/13516509/11865012/60643bfe-a4b6-11e5-9c13-dd0efd19d9ea.png">

So the result of this test shows by increasing and reaching my records of database to about 200K it makes queries and deployd very slow , but in low amount of records it works well !

If you need more explanations let me know.

**Comment by iKristjan** [comment]
@mobi-life ~1000ms MongoDB query seems very slow, even for a collection with 200k records.
Forgive me for asking, but have you optimized queries and have correct collection indexes in place?

**Comment by mobi-life** [comment]
It's ok @iKristjan , no this is the database that deployd created for me and I didn't touched it , do you know how can I optimaize it ?

**Comment by ericfong** [comment]
My production server is based on a very old fork of deployd. So, may not
apply to the current one.

From my experience, Parse.com is also very slow. (And also mongoose)
I think any nice and magic framework is slow....

On Thu, Dec 17, 2015 at 4:48 PM, mobi-life <notifications@github.com> wrote:

> It's ok @iKristjan <https://github.com/iKristjan> , no this is the
> database that deployd created for me and I didn't touched it , do you know
> how can I optimaize it ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployd/deployd/issues/687#issuecomment-165385914>.
>



-- 
Best Regards,
Eric Fong

**Comment by iKristjan** [comment]
I think we have found the problem then. ;)

Indexing is a bit of art really, but basically you need to add indexes to fields which you use in your queries. Otherwise searching takes a very long time.

Which MongoDB version are you using @mobi-life ?
Methods are a little different between MongoDB 2 and 3.
But I expect you are using v2.4?

For v2.4 you can add an index like this through the MongoDB shell:
`db.COLLECTION.createIndex( { FIELD: 1 } )`

There are good docs for MongoDB indexing:
https://docs.mongodb.org/v2.4/core/indexes-introduction/

For fine tuning you should setup profiling level (https://docs.mongodb.org/v2.4/reference/method/db.setProfilingLevel/) and check your log files for slow queries (which I believe are massive if almost every query is that slow).

**Comment by mobi-life** [comment]
@ericfong which version of deployd do you use ? 
are you ok with that ?
do you suggest I use old versions too ?
thanks.

**Comment by mobi-life** [comment]
@iKristjan thank you for useful information and guid .
I was using mongodb v3.0.7 and I updated it some days ago to v3.2 . I hope by indexing it become ok :)

**Comment by iKristjan** [comment]
No worries, and sorry I didn't see you were using v3 and with v3.2 just use the latest docs:
https://docs.mongodb.org/manual/core/indexes-introduction/

Post your results here afterwards, which I believe will be massive. My results were with ~30k record collection that 500ms (or slower) queries (without indexes) went to ~10ms (with indexes) and so on...

I have wondered if there are any issues with running Deployd with MongoDB 3 and now 3.2 in production. But other than these non-optimized queries, it performs OK? Maybe @ericfong or @andreialecu have had experience with that?

**Comment by andreialecu** [comment]
@mobi-life do you use socket.io in your app? (`emit`, `dpd.on`)?

**Comment by andreialecu** [comment]
I have a branch at https://github.com/andreialecu/deployd/tree/fix-sessionleak with some memory leak fixes, it's pretty untested, but it should be safe I think. 

If you feel like it, give it a try.

**Comment by mobi-life** [comment]
@iKristjan thank you very much for this amazing superhelpful guid , I did indexing and then mongodb operation on the busy collection reduced from **~5sec** to just **5ms~7ms!!!** and I didn't thought just by indexing the speed will affect like this !
actually problem was in database not in deployd and I'm happy that I can still continue using deployd . And also I'm sorry if I botherd you friends by wrong information here. I think it's better to implement the ability of setting indexes for collection fields easily from deployd dashboard , because this issue can cause the people like me who it is the first time they are facing with mongodb and deployd fall in confusion and misunderstanding . 
I can help in deployd develompent in these ways (ofcourse if you like) :
1. I want to make a list of tips about deploying the deployd server on linux systems (specially ubuntu) that I experienced them from first day I started to use deployd server in production environment until now , and maybe you like to put these tips and tricks in deployd site for people who are trying to deploy it on linux servers.
2. I can help you in testing deployd versions in the real production environment by relatively high traffics and queries to debug and improve it .
3. I wrote a simple android java library for connecting to and using deployd backend from mobile applications , and I will publish it in github after finishing tests , maybe it can be helpful for fans of deployd server.
4. I know some nodejs if there is any need to write some code I can help you this way too.

again thanks to @andreialecu , @ericfong and @iKristjan for answering me by patient.

**Comment by mobi-life** [comment]
@andreialecu no I don't used socket.io yet , but maybe I use socket.io in future too .
thank you for sharing your own deployd version , I will use and test it definitely.

**Comment by iKristjan** [comment]
@mobi-life that's awesome! I'm glad I was able to help.

Speaking of tips, I guess this MongoDB indexing is something we should mention in Deployd docs as this is not handled by Deployd and needs to be done manually. When I was new to MongoDB I too didn't think of that first when I was investigating slowness, although indexing is kind of obvious even coming from MySql world.

**Comment by ericfong** [comment]
Don't suggest old version of dpd.

New version of session and event memory control is much better.

On Sat, Dec 19, 2015 at 4:54 PM, Kristjan Lilleoja <notifications@github.com
> wrote:

> @mobi-life <https://github.com/mobi-life> that's awesome! I'm glad I was
> able to help.
>
> Speaking of tips, I guess this MongoDB indexing is something we should
> mention in Deployd docs as this is not handled by Deployd and needs to be
> done manually. When I was new to MongoDB I too didn't think of that first
> when I was investigating slowness, although indexing is kind of obvious
> even coming from MySql world.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployd/deployd/issues/687#issuecomment-165961563>.
>



-- 
Best Regards,
Eric Fong

**Comment by andreialecu** [comment]
@mobi-life the leak-fix PR has been merged recently, did you see any memory usage improvements? There's no caching anywhere in deployd, so even with your traffic numbers, I don't see why memory usage would ever go above 500 MB or so.

**Comment by mobi-life** [comment]
@andreialecu Thank you for bug fixes , I installed new version from master branch and yea it seems memory fixes are working now , before update memory usage was about **10%~20%** and sometimes was even more , but after updating deployd  memory usage reduced to about **3%~4%** by using PM2 and 8 clusters. 
Also I should say even before this update memory usage issue was just by **PM2** and by using **Forever** it was normal and about **3%**, but after updating now it is work normal by **PM2** and clustering too!.
I didn't test it using your new introduced socket.io and redis configuration yet (it seems very cool) , I will put here the result of testing with those configuration too.

**Comment by mobi-life** [comment]
@andreialecu 
I have installed redis and tested server with new configuration , when it is a single instance it works well , but unfortunately when I run it as multiple clusters then clients aren't able to connect to the server via socket.io  .
This is my edited run script , please tell me if it is wrong : 
```javascript
// require deployd
var deployd = require('deployd');
var  path = require('path');
var shelljs = require('shelljs/global');
var redis = require('redis');
var redisAdapter = require('socket.io-redis');

var REDIS_URL = "redis://127.0.0.1:6379";
var sioPub = redis.createClient(6379,"127.0.0.1");
var sioSub = redis.createClient(6379,"127.0.0.1", { 'return_buffers': true });

var dpdPub = redis.createClient(6379,"127.0.0.1");
var dpdSub = redis.createClient(6379,"127.0.0.1");

var serverOptions = {
  port: process.env.PORT || 5555,
  env: 'production',
  db: {host: '127.0.0.1', port: 27017, name: '-deployd'},
	sessions: {
    pubClient: dpdPub,
    subClient: dpdSub,
  },
	 socketIo: {
		options: {
				transports: ['websocket'], // only websocket transport allowed (no xhr-polling)
			},
    adapter: redisAdapter({ pubClient: sioPub, subClient: sioSub })
  }
};

// configure database etc. 
var server = deployd(serverOptions);

// start the server
server.listen();

// debug
server.on('listening', function() {
  console.log("Server is listening on port: " + (process.env.PORT || 5555));
});

// Deployd requires this
server.on('error', function(err) {
  console.error(err);
  process.nextTick(function() { // Give the server a chance to return an error
    process.exit();
  });
});

```

**Comment by andreialecu** [comment]
For socket.io, you need to enable sticky sessions. See http://socket.io/docs/using-multiple-nodes/

**Comment by mobi-life** [comment]
@andreialecu 
I tested this PR : https://github.com/deployd/deployd/tree/ff5f840c9514679f9161af146266d83f3a4f16af too.
It works well by **sticky sessions** module , but the problem is using by other clustering wrapers like **PM2** . I mean sockets.io not working with **PM2** clustering system even by using **sticky sessions** , because **sticky sessions** module runs clusters by its own and you should choose one between **PM2** or **sticky sessions** module !!!
Maybe **sticky sessions** mechanism should be implemented inside deployd for default and let other clustering tools manage clusters , and also I think **sticky sessions** module is not efficient in case of running deployd , because this module runs only one instance of deployd server as master node and some other empty child nodes , while **PM2** runs many instances of deployd without confliting with each other !
Maybe I'm doing wrong in my run script , I will share mine script here that it uses sticky sessions , and please tell me how do you run deployd in clusters ?!

```javascript
var cluster = require('cluster'); 
var deployd = require('deployd');
var  path = require('path');
var shelljs = require('shelljs/global');
var redis = require('redis');
var redisAdapter = require('socket.io-redis');
var sticky = require('sticky-session');


var REDIS_URL = "redis://127.0.0.1:6379";
var sioPub = redis.createClient(6379,"127.0.0.1");
var sioSub = redis.createClient(6379,"127.0.0.1", { 'return_buffers': true });

var dpdPub = redis.createClient(6379,"127.0.0.1");
var dpdSub = redis.createClient(6379,"127.0.0.1");

var serverOptions = {
  port: process.env.PORT || 3333,
  env: 'production',
  db: {host: '127.0.0.1', port: 27017, name: '-deployd'},
	sessions: {
    pubClient: dpdPub,
    subClient: dpdSub,
  },
	 socketIo: {
		options: {
				transports: ['websocket'], // only websocket transport allowed (no xhr-polling)
			},
    adapter: redisAdapter({ pubClient: sioPub, subClient: sioSub })
  }
};

// configure database etc. 
var server = deployd(serverOptions);

// start the server

if (cluster.isMaster)
	server.listen();
if (!sticky.listen(server, 3000)) {
        // Master code
        server.once('listening', function() {
            console.log('server started on 3000 port');
        });
	console.log("server started");
	// debug
	server.on('listening', function() {
		console.log("Server is listening on port: " + (process.env.PORT || 3333));
	});
 }else {
  // Worker code
	console.log("A cluster is running");
	// Deployd requires this
	server.on('error', function(err) {
		console.error(err);
		process.nextTick(function() { // Give the server a chance to return an error
			process.exit();
		});
	});
}
```

**Comment by andreialecu** [comment]
@mobi-life sticky sessions are required for socket.io if you're using `xhr-polling`. 

If you're just using the `websockets` transport exclusively then it should just work without sticky sessions.

This is a socket.io limitation.

**Comment by NicolasRitouet** [comment]
Really interesting discussion! 👍 
Seems that the main issue has been solved.
Feel free to reopen the ticket if necessary.
