### ISSUE TITLE
"Cookbook" in documentation with code samples for common tasks

### ISSUE THREAD

**Issue by dallonf** [deployd/deployd#69]
This would allow us to document specific tasks, as well as help us see which use cases are awkward and should be optimized.

What kinds of "recipes" would you like to see documented? So far we know that our users want to 
know how to:

- Relate data to a parent 
- Restrict access for unauthorized users
- Allow users to "follow" other users

**Comment by ericfong** [comment]
This seems like a discussion, we can move this to gitter or google group.

let's close this issue first
