### ISSUE TITLE
Going Cookieless 

### ISSUE THREAD

**Issue by mwmwmw** [deployd/deployd#692]
I have an API that I use for a number of clients hosted on separate domains. For this I require third party cookies to be enabled on the users browser. Normally, this would be fine as most of my projects are "internal" facing where I have some control over the configuration of the browser. 

However, I have a number of public facing projects launching soon. Due to changes in how certain browsers handle third party cookies, I want to change the cookie behavior to something like: 

1. User logs In 
2. I respond with a session id, store it in localstorage.
3. they use that session id as part of a signing request with each request sent back to API (like JSON web token or something)
4. If the session id is expired, they have to re-log in and get a new session id. 

No cookies sent, no third party cookies are required. 

Any recommendations? Could deployd work this way?

**Comment by andreialecu** [comment]
Deployd does support HTTP header authentication instead of cookies using `Authorization: Bearer <sid>`. This isn't properly documented anywhere, but have a look at https://github.com/deployd/deployd/pull/521 and https://github.com/deployd/deployd/pull/540

**Comment by mwmwmw** [comment]
Yes, this is exactly what I had imagined. 

I'm using Backbone, but I know how to extend it to incorporate this. I will give this a shot.

**Comment by mwmwmw** [comment]
Works like a charm. Thank you so much!
