### ISSUE TITLE
Real time value change on collection is not visible until page refresh. 

### ISSUE THREAD

**Issue by rahulakash** [deployd/deployd#694]
Hello, 

I am using a program with constantly updates values on a Deployd collection. I am unable to see the value changes from the dashboard in real time. To see the updated values I have to refresh the dashboard page every time. I don't know if it is a browser issue. I am using Chrome 45.0.2454.85.
Is there a possible solution? Your help is highly appreciated.

Thank you.

**Comment by rgolea** [comment]
Maybe don't rely on the dashboard to do that since the dashboard is not configured to have socket.io nor the collections to emit sockets by default. Try creating your own table that views the content.

**Comment by rgolea** [comment]
Feel free to reopen this if necessary
