### ISSUE TITLE
Multiple apps on same instance 

### ISSUE THREAD

**Issue by saleeh93** [deployd/deployd#695]
I am looking to use deplyd as multiple apps in a same instance, So that each app has its own users and collections
Does deployd has an option to do that.?

**Comment by MattW86** [comment]
Hi @saleeh93, have you found out the answer of this question?

**Comment by thbl** [comment]
+1

**Comment by rgolea** [comment]
You can develop your own script for that. Just use `child_process` and some sort of filter for the calls. Also take a look into docker to deploy multiple instances, maybe you can deploy progamatically.
