### ISSUE TITLE
How to modify post response json 

### ISSUE THREAD

**Issue by tekinarslan** [deployd/deployd#699]
Hi,
Iam post json request my service and get response with same json with dynamic id. How can I change this auto response json only standart 200 ok response json.

Thanks.

**Comment by andreialecu** [comment]
If I understand your question correctly, you can call `ctx.done(null, { ok: true } );` from the `On POST` event

**Comment by tekinarslan** [comment]
Thanks.

**Comment by moorthi07** [comment]
It throws this error in server side though!  It returns a response before the call back resolved.  Any idea?
Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)

**Comment by cristianfd** [comment]
In which file are you modifing the post?

**Comment by moorthi07** [comment]
I use a **get**  url as webhook :  localhost:2403/confirmemai/123456 
 From On Get , update emails and  return ,
"Email verified"

**Comment by andreialecu** [comment]
You should use `dpd-event` for this.

**Comment by moorthi07** [comment]
Yes. I was too lazy to add a wrapper to update my emails collection.  Thanks. One more thing, is there any way to **redirect** from ctx.res ? - I guess it is wrapper of 'http '  right?

**Comment by andreialecu** [comment]
You can just return status code `301`/`302` by setting `ctx.res.statusCode = 301;` prior to calling `setResult()` (if you're using dpd-event). Yes, `ctx.res` is the nodejs ServerResponse object: https://nodejs.org/api/http.html#http_class_http_serverresponse
