### ISSUE TITLE
Save data

### ISSUE THREAD

**Issue by tekinarslan** [deployd/deployd#704]
Hi,
Iam create save user service and how can I save user if not exist on db. When if user exist ,I will update it. 

Thanks

**Comment by ericfong** [comment]
I think do and get first, and then post or put.

You can also do a special plugin for that. But, dpd don't have findAndModify build in

**Comment by tekinarslan** [comment]
I found query sample for id but I dont understand how does it work.

**Comment by tekinarslan** [comment]
I solved issue .Send post json and get id. İn next time, if json include this id, user not multiply.
Thanks.
