### ISSUE TITLE
Image upload service

### ISSUE THREAD

**Issue by tekinarslan** [deployd/deployd#706]
Hi
I want to make image upload service and is deplyd support this type?
Also, I may found upload image js files, how can I import prepared upload image service files ?
Thanks,

**Comment by mwmwmw** [comment]
It should be pretty simple to setup using the DPD File upload package.
https://www.npmjs.com/package/dpd-fileupload


If you're using AWS, DPD Storage Cloud is better.
https://github.com/simpleTechs/dpd-storage-pkgcloud

**Comment by tekinarslan** [comment]
dpd-fileupload module not working. I install it but I dont see it on my dashboard.
Also, I am using digitalocean and I try to dpd-storage-pkgcloud.

Thanks
