### ISSUE TITLE
Error loading module node_modules/deployd

### ISSUE THREAD

**Issue by dopry** [deployd/deployd#709]
I have a project with an odd structure

/package.json
/node_modules
/server/server.js

I run the project from the /server folder with `node server.js`.
Deployed is being used as an express app.

I get the following error.

Error loading module node_modules/deployd
Error: Cannot find module 'C:\Users\Darrel\src\org\project\server/node_modules/deployd'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\Darrel\src\org\project\node_modules\deployd\lib\type-loader.js:25:32
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13)

The typeloader is not following the same behavior as require and recursing up to the project folder to search for node_modules.

It raises the question of why is the type loader doing anything more than just requiring the custom resource packages and letting require('...') do the hard work? Is there a reason the type loader is duplicating all this work?

**Comment by rgolea** [comment]
Did you install deployd locally?

**Comment by rgolea** [comment]
Feel free to reopen this if needed.
