### ISSUE TITLE
Collection type of ¨Date¨

### ISSUE THREAD

**Issue by stweet4000** [deployd/deployd#713]
just  wondering why there ait a collection type of Date in deployd ?
Could be realy nice, any easy way to add this ?

**Comment by rgolea** [comment]
As far as I can tell, the dashboard doesn't display it, but if you change the config.json file in your resource folder and set the type to "date" it might work.

I'm saying this based on the next 3 parts of the scripts around
1. https://github.com/deployd/deployd/blob/master/package.json#L36 (Module validation). It supports type="date"
2. https://github.com/deployd/deployd/blob/0adf309a5325949144a1f617f2fd5673ab4b7060/lib/resources/collection/index.js#L76. It clearly uses this module to validate if it works or not.
3. https://github.com/deployd/deployd/blob/0adf309a5325949144a1f617f2fd5673ab4b7060/lib/resources/collection/dashboard/js/properties.js#L32 Here you have all the property types that the dashboard supports.

Having all this info, maybe do a PR?

**Comment by rgolea** [comment]
I'm closing this issue, feel free to reopen it if necessary
