### ISSUE TITLE
Dashboard not working on another /api/dashboard

### ISSUE THREAD

**Issue by kvdmolen** [deployd/deployd#714]
I'm using middleware to setup Deployd:

``` javascript
require('deployd').attach(https, { ... });
app.use("/api", https.handleRequest);
```

Now the `/api/dashboard` does NOT work as files are expected to be served from the root. Any ideas how to set a `basePath` for the SERVER?

The rest works fine (especially in combination with HTML5 pushState)!

**Comment by gustavotero7** [comment]
I have the same problem, any solution yet?

**Comment by gustavotero7** [comment]
Solved, just edit the index.ejs and auth.html files to avoid the root ref, you can see how the updated files look here https://github.com/ChimeraDigital/deployd/tree/master/lib/resources/dashboard

**Comment by gustavotero7** [comment]
I have forget the sub "folders" for the url, an absolute url path to the linked files should work

**Comment by moorthi07** [comment]
Great. Good job. Thanks
