### ISSUE TITLE
Managing client-end scripts using npm fails to start deployd server - type-loader issue 

### ISSUE THREAD

**Issue by RaghuChandrasekaran** [deployd/deployd#717]
I am using **webpack** to manage my client end scripts.So,I have installed angular using npm.

Since angular dependency  is found in package.json,deployd's type-loader tries to load angular and fails to start the **deployd** server.

**Error log:**
```
Error loading module node_modules/angular
ReferenceError: window is not defined
    at Object.<anonymous> (D:\WorkSpaces\storytracker\node_modules\angular\angul
ar.js:30426:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\WorkSpaces\storytracker\node_modules\angular\index
.js:1:63)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at C:\Users\441669\AppData\Roaming\npm\node_modules\deployd\lib\type-loader.
js:25:32
    at doNTCallback0 (node.js:419:9)
bye
```

**package.json:**
```
{
  "name": "storytracker",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "./node_modules/.bin/webpack",
    "start": "npm run build && nodemon server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "angular": "^1.5.0",
    "deployd": "^0.8.8"
  },
  "devDependencies": {
    "babel-core": "^6.5.2",
    "babel-loader": "^6.2.3",
    "babel-preset-es2015": "^6.5.0",
    "webpack": "^1.12.13"
  }
}
```
**Server.js:**
```
var deployd = require('deployd');
var server = deployd({
    port: 2403,
    env: 'development',
    db: {
        host: 'localhost',
        port: 27017,
        name: 'storytracker'
    }
});
server.listen();
server.on('listening', function() {
    console.log('Server is listening on port: 2403');
});
server.on('error', function(err) {
    console.error(err);
    process.nextTick(function() { // Give the server a chance to return an error
        process.exit();
    });
});
```
I tried after removing the angular dependency from the package.json. The server will start with no issues.

So is there any way to make deployd type-loader ignore certain packages?

**Comment by rgolea** [comment]
@NicolasRitouet can you give a feedback on how to do it better? Maybe inside the `package.json` we could use something like:
```
dependencies: {
 angular: "*"
},
dpdIgnore: ["angular"]
```

**Comment by juodumas** [comment]
Maybe just document that it is recommended to have one `package.json`
for the backend and another one for the frontend?

Anyway, automatic loading of all node modules is asking for problems.

**Comment by rgolea** [comment]
yes, but having multiple `package.json` files asks for another set of problems with maintenance. That is why I would want to implement a dpdIgnore property in the package file.

**Comment by juodumas** [comment]
Well, if you have

    project/package.json
    project/public
    project/client-dev/package.json
    project/client-dev/...frontend-things...
    project/...backend-things...

Then `npm run build-frontend` can `cd client-dev && npm run build`,
which would bundle up frontend files to `project/public`.

Maintaining a single `package.json` file for backend and frontend can
also be confusing, especially since `package.json` doesn't accept
comments.

So again, maybe it would be better to think about not load everything
from `node_modules/`, at least for `1.0.0`? Note that when using a
single `package.json` there will likely be far more things for the
frontend than for deployd.

**Comment by RaghuChandrasekaran** [comment]
@rgolea I just tried the _dpdIgnore_  property and it works :smile: .Thanks for the quick patch.

Like @juodumas  suggests automatic loading of all node modules will cause many such inconvenient problems.Will it not be better to load only modules starting with "dpd-" .

**Comment by rgolea** [comment]
@RaghuChandrasekaran Maybe. The thing is that I'm not sure all deployd modules start with `dpd-`. That is why I wanted to give the option to not load if not necesary.
