### ISSUE TITLE
Can we update multiple document through single request?

### ISSUE THREAD

**Issue by vafrcor** [deployd/deployd#719]
Documentation [here](http://docs.deployd.com/docs/collections/reference/dpd-js.html#s-.put%28[id%20or%20query],%20object,%20fn%29)

Can we update multiple Collection document through single `dpd.collection.put()` request ?

**Comment by rgolea** [comment]
I'm not sure that `dpd.collection.put()` might do that eventhough the docs say you might. If this doesn't work you could use `dpd.collection.getResource().update()` and do a mongodb query.

I will close this issue. Feel free to reopen it if needed.
