### ISSUE TITLE
Make dpd.js isomorphic

### ISSUE THREAD

**Issue by PaulMaly** [deployd/deployd#723]
Not so long ago I began to develop isomorphic web apps. So, I believe it will be very cool to be able to use dpd.js library on both sides (browser and NodeJS server). Seems, to do that, we need to use some isomorphic HTTP requests library in dpd.js. 

What do you think about it?

**Comment by moorthi07** [comment]
dpd commands are isomorphic already both in client library and in server. 
dpd command is in built in the server side. 
dpd commands for client (from deployd 1.0) is a separate library dpd-client you will have to add in your client index.html or so.
But, the functionalities of dpd commands are same.  
There is another set of dpd commands for commandline console in server side (dpd-cli - which is separate library .)
