### ISSUE TITLE
Deployd as node module, but db-path on current root project

### ISSUE THREAD

**Issue by vafrcor** [deployd/deployd#726]
Is there any way if we wanted to create project with requirements as below?
* Deployd run as Node module (ref: http://docs.deployd.com/docs/server/as-a-node-module.html)
* Set database inside root path of current project (within `./data/` directory, just like Deployd basic example)

Appriciate any answer and thank you.

**Comment by vafrcor** [comment]
I don't think there is any solution for now.

**Comment by andreialecu** [comment]
You can do this by spawning `mongod` yourself. Have a look at:

https://github.com/deployd/deployd/blob/master/bin/dpd
https://github.com/deployd/deployd/blob/master/lib/util/mongod.js

Possible code:

```javascript
var mongod = require('deployd/lib/util/mongod');

mongod.restart('mongod', 'development', 12345 /* maybe generate a random port */, function(err) {
  if (err) {
    // an error occurred, kill process maybe
  }

  // continue startup
});
```
