### ISSUE TITLE
Need deployd to support multiple apps via web interface.

### ISSUE THREAD

**Issue by sahilshekhawat** [deployd/deployd#729]
I want to get list of all the collections created in a particular app. 

Also, I am working to create an web interface to create multiple apps via web client itself. Can someone point me in the right direction?

**Comment by hjanuschka** [comment]
you ll get a list of resources if you call `localhost:2403:/__resources`  and sending the `dpd-ssh-key` header (wich has to be the key as value)

**Comment by rgolea** [comment]
This is highly problematic since the dpd-ssh key can be used to skip events and access other data. Maybe try using a dpd-event module to do an internal dpd.__resources.get() or even with fs.readDirSync

**Comment by andreialecu** [comment]
Rather than `fs.readDirSync` or `dpd.__resources.get()`, you could read all the keys of `dpd`. For example with underscore: `_(dpd).keys()` would return all your collection names from an event script.

**Comment by sahilshekhawat** [comment]
Thanks everyone :+1:
