### ISSUE TITLE
Push notification with dashboard

### ISSUE THREAD

**Issue by hoangtrongphuc** [deployd/deployd#744]
Push notification is important with mobile, please add dpd-fcm to dashboard UI

**Comment by houmark** [comment]
There's nothing to do here. If developers wants to use a third party deployd module, they can do so by including it in their installation package.json. If the module is correctly developed, it will then show up in the UI.

**Comment by hoangtrongphuc** [comment]
So how can I change the UI in dashboard ?, default I only know add Resource to UI, but I want add button or any UI element to dash.

**Comment by houmark** [comment]
Do you want to send push notifications directly from the dashboard using your module?

**Comment by hoangtrongphuc** [comment]
Yes, module deployd-fcm is great! But I dont want send post by command line.

**Comment by hoangtrongphuc** [comment]
I created push notification with dash  
 https://github.com/hoangtrongphuc/deployd-push-dashboard
