### ISSUE TITLE
Flood Request to api/AdmobApi

### ISSUE THREAD

**Issue by hoangtrongphuc** [deployd/deployd#745]
When I set DEBUG env to *, console flood output : 

> config-loader Loading from cache +0ms
>   router resources ["/ads","/apps","/clients","/configs","/fcm","/","/__resources","/dpd.js","/dashboard"] +0ms
>   router routing /api/AdmobApi/Get?id=69 to / +1ms
>   send stat "/root/mplserver/public/api/AdmobApi/Get" +0ms
>   server GET /api/AdmobApi/Get?id=69 +25ms
>   config-loader Loading from cache +0ms
>   router resources ["/ads","/apps","/clients","/configs","/fcm","/","/__resources","/dpd.js","/dashboard"] +0ms
>   router routing /api/AdmobApi/Get?id=69 to / +1ms
>   send stat "/root/mplserver/public/api/AdmobApi/Get" +0ms
>   server GET /api/ConfigApi/Get +0ms
>   config-loader Loading from cache +0ms
>   router resources ["/ads","/apps","/clients","/configs","/fcm","/","/__resources","/dpd.js","/dashboard"] +1ms
>   router routing /api/ConfigApi/Get to / +0ms
>   send stat "/root/mplserver/public/api/ConfigApi/Get" +0ms
>   server GET /api/ConfigApi/Get +10ms
>   config-loader Loading from cache +1ms
>   router resources ["/ads","/apps","/clients","/configs","/fcm","/","/__resources","/dpd.js","/dashboard"] +0ms
>   router routing /api/ConfigApi/Get to / +0ms
>   send stat "/root/mplserver/public/api/ConfigApi/Get" +1ms
>   server GET /api/ConfigApi/Get +0ms
>   config-loader Loading from cache +0ms
>   router resources ["/ads","/apps","/clients","/configs","/fcm","/","/__resources","/dpd.js","/dashboard"] +0ms
>   router routing /api/ConfigApi/Get to / +0ms
>   send stat "/root/mplserver/public/api/ConfigApi/Get" +1ms

So what is api/AdmobApi/Get ?? I don't create any resource with name Admob.

**Comment by hoangtrongphuc** [comment]
Sometime, my deployd server is crash with error : too many open files "resources/config.json"?
What is the problem?

**Comment by NicolasRitouet** [comment]
For the first issue with `AdmobApi`, no idea, there's nothing about it in our code.
For the second issue, can you give us more details?

**Comment by houmark** [comment]
Too many open files can be due to running deployd/MongoDB on macOS which is limiting maxproc and maxfiles. More about that [here](http://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks).
