### ISSUE TITLE
deployd not working on Windows 10

### ISSUE THREAD

**Issue by SunilWagh78** [deployd/deployd#751]
I wish to use deployd on Windows 10, I receive following error when trying to test the installation,

This version of C:\Program Files\Deployd\tools\node.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

I've already installed node.js, what is the way out? Please help

**Comment by vinchauhan** [comment]
What version of node you have ?

node --version

**Comment by SunilWagh78** [comment]
Hi,
Its v4.5.0

**Comment by vinchauhan** [comment]
Looks like you didnt have node earlier and when you installed 'deployd' , it took its own version of node.

Try uninstalling deployd. The install node from https://nodejs.org/en/

After you have installed node. Try to install deployd from npm - node package manager

npm install -g deployd

**Comment by NicolasRitouet** [comment]
@vinchauhan is right.
We will deprecate the windows installer and recommend everybody to install deployd through npm.
Feel free to reopen this ticket if you still have an issue with windows 10.
