### ISSUE TITLE
get.js event get executed twice on a GET request

### ISSUE THREAD

**Issue by larafale** [deployd/deployd#758]
hello guys just digging into deployd

i've created a `/product` collection and added a `console.log('hello')` in the `get.js` and a `post.js` event file.

when i run a `dpd.product.post({})`, post.js is executed once as expected
but when i run `dpd.product.get()`  get.js is executed twice

is this normal ? First i thought it was my browser making `OPTIONS` request, so i tried with curl but same result.

**Comment by rgolea** [comment]
The get event is triggered for each product so you might have 2 products in the db.

**Comment by larafale** [comment]
that makes sense :) thx
