### ISSUE TITLE
Extract CLI from core repo

### ISSUE THREAD

**Issue by NicolasRitouet** [deployd/deployd#762]
Deployd's CLI should be extracted from the Core repo and have its own repo.
Required features:
- `dpd .` starts the dev environment (serve the app)
- `dpd create my-project` bootstrap a deployd project
- `dpd showkey` display the key to access the dashboard
- `dpd keygen` create a private key to access the dashboard
  Current documentation is available here:
  http://docs.deployd.com/docs/basics/cli.html

Also, remove usage of `app.dpd`

[`Ember-cli`](https://ember-cli.com/) is a good example of a CLI.

**Comment by NicolasRitouet** [comment]
The [new repo for the dpd-cli](https://github.com/deployd/deployd-cli) is available, please, try it and report/fix bugs.

**Comment by moorthi07** [comment]
What was the use of app.dpd?  If it was for dpd - config purpose, why remove? We need a simple dpd config  JSON file helps to  configure  mongodb, name , auth and some custom config data can be used. Any idea?

**Comment by NicolasRitouet** [comment]
The `app.dpd` has never really been used for config, we used to check if this file was present to verify that it is a deployd app.

Your configs don't have to be inside deployd, you could use [node-config](https://www.npmjs.com/package/config) for that.
