### ISSUE TITLE
Refactor dashboard

### ISSUE THREAD

**Issue by NicolasRitouet** [deployd/deployd#764]
The deployd dashboard is getting old and needs to be remade.
Ideally, the new dashboard would use angular2 or react.
- define the features we want, based on the current deployd API
- design a mockup of the new UI
- implement it (new repo?)

**Comment by gabrielperales** [comment]
React would be a good option! 👍

**Comment by houmark** [comment]
@gabrielperales Please elaborate why you think React is a better option than Angular2 for the dashboard. I am not particularly opinionated, but I think it would be nice to list pros and cons for each of the two main contenders in relation to a dashboard for listing/editing data such as is needed for deployd.

**Comment by gabrielperales** [comment]
@houmark I'm sure both are good options, I just say React because I'm doing stuff with react. Maybe react is more mature, lighter and I prefer to use ES6 with babel to use TypeScript (I know that there is not needing of using TypeScript and neither babel, but they are like their standard)

**Comment by andreialecu** [comment]
Actually TypeScript would be great to use with deployd as much as possible, since it could enforce some type checking on actual deployd collections. Since deployd collections have a schema, the additional power from TypeScript would be amazing.

Also since TypeScript is just a superset of ES6, and compiles down to JS just like ES6 it shouldn't be a problem, and any typescript constructs would be optional anyway.

**Comment by gabrielperales** [comment]
This should be something that the deployd core team should discuss. You are the maintainers and if all of you are happy with TypeScript, go for it.

I my opinion, TypeScript is not needed. For checking schemas in mongo, you can use something like mongoose for validation. And in the frontend with react you can use PropTypes to check the properties types.

**Comment by andreialecu** [comment]
I'm mainly talking about allowing event scripts to be written in TypeScript. 

TypeScript provides so much metadata about code that autocompletion and type checking can be provided in the editor, which can increase developer productivity a lot. 

Imagine being able to type `dpd.` in the code and see the full list of available collections immediately. Then when you get to `dpd.somecol.get(` you could also see all possible parameters you can pass, or queries you could do. 

This extends to the result of the call, so, for instance:

```javascript
dpd.somecol.get().then(results => {
  // results here is an array of an actual type of somecol objects, so typing something like
  results[0].someTextField // would be a string, and the moment you type the dot, you'd see all properties listed in your editor's autocomplete 
});
`

 Documentation would almost not be needed at all.

See the examples here for more info: https://atom.io/packages/atom-typescript

**Comment by gabrielperales** [comment]
Yeah, that sounds cool. But as I told you, that is something up to the Deployd maintainers. I can see the benefits of using a typed language, but at this moment, I keep working just with javascript.

**Comment by andreialecu** [comment]
To clarify, you can still write completely untyped code with TypeScript as well. You only use the explicit types when/if you want to. It's almost exactly like https://flowtype.org/ for react, but better in a lot of ways. 

And in reality, TypeScript support in the core would probably be for a 2.0 milestone rather than 1.0.

**Comment by gabrielperales** [comment]
Then, I you are thinking on using TypeScript for the 2.0, and you have more experience with angular than with react... the option is clear.

**Comment by NicolasRitouet** [comment]
the [new repo for the dpd-dashboard](https://github.com/deployd/dpd-dashboard) is available, feel free to start hacking.

**Comment by hussainb** [comment]
React can be written in typescript tsx, thus you get the advantage of both.

**Comment by PaulMaly** [comment]
Maybe just use https://github.com/marmelab/ng-admin ?
