### ISSUE TITLE
Password not available in users collection

### ISSUE THREAD

**Issue by kkrishnan90** [deployd/deployd#773]
I have a weird bug in creating users collection inside the dashboard and while POSTING new user to the collection. 

I hit the local host deployd and created the users collection. I now use POSTMAN plugin to POST a new user. The new user is created but weird enough that the supplied password property is empty in the POST response and dashboard too. I don't get any error neither on the dashboard nor during the request and response. Could someone help me on this ? I really love using Deployd as it's shaving a huge time for API creation.

**Comment by rgolea** [comment]
Hey! It's not a bug, it's how deployd was built. Try testing that you can log in (/users/login). You shouldn't be able to see the password directly in the dashboard or the api for obvious security reasons but both username/password are required fields. Try seeing your mongodb instance to see the hashed password there.

**Comment by rgolea** [comment]
Feel free to reopen this issue at any time
