### ISSUE TITLE
Realtime notification to the clients

### ISSUE THREAD

**Issue by kkrishnan90** [deployd/deployd#774]
I have gone through the documentation for deployd regarding the real time notifying the clients on a data or value being updated in the backend. Now, I have this backend deployd setup and I'm creating an API to support my android app. However, to update the client(android app) in realtime, I need to use socket operations on POST method to emit the changes from the server (using emit() method). I have seen a nodejs documentation to include a code on the client end that notifies the changes done on the server side. How do you notify my android user about the updated server data changes ? Any help over this would be much appreciated ! Thanks to all in advance.

**Comment by rgolea** [comment]
I have never worked with android and I couldn't say 100% but maybe you can try one of this deployd modules:
https://www.npmjs.com/package/dpd-gcm
https://www.npmjs.com/package/dpd-notify

Close this issue if the problem gets solved with this

**Comment by kkrishnan90** [comment]
Thanks I'll check that out! Let's keep this open so that someone who's worked with android client and deployd backend would drop their comment in here on how they handled this one ? Your thoughts ?

**Comment by andreialecu** [comment]
I've been sending GCM push notifications to Android apps with deployd. I have a fork of dpd-gcm here that I'm using:

http://github.com/andreialecu/dpd-gcm

The main package was limited to sending 1000 notifications at a time, I worked around that because I need to send more with my app. So it has this fix and a few others.

**Comment by kkrishnan90** [comment]
Hey ! I appreciate your comment over this issue. Will this work on FCM too ? As there is no more GCM concept existing but just FCM .

**Comment by andreialecu** [comment]
Well, my app still works, so I guess that yes. :)

**Comment by kkrishnan90** [comment]
Fantastic :. So all I need to input is the API key from firebase console and everything works out of the box is it ?

**Comment by andreialecu** [comment]
Pretty much. Assuming the firebase api key is the same as what the GCM api key used to be (it probably is).

**Comment by kkrishnan90** [comment]
Cool man.. I'll try this out tonight and will close this issue if it works.. keeping my fingers crossed :D

**Comment by vinchauhan** [comment]
Krishnan,

What are using to hosting deployd for your app. I am looking for low
pricing options.

Thanks

**Comment by kkrishnan90** [comment]
Well under what context was that question from ? To check if gcm would work.. ? I'm using Amazon Web Services free tier EC2 instance with centos VPS . Does this answer your question? Please do let me know what you're looking for and I'll try to help you out.

**Comment by kkrishnan90** [comment]
Hey hi ! I tried your 
http://github.com/andreialecu/dpd-gcm
dpd-gcm library. 

Im trying to create a custom payload message data. But every time when the notification gets triggered, it displays only default data (which is set through the dashboard while setting the API SERVER KEY). Could you share some code snippets for us to get a brief idea ?

Well, here's mine 

>   dpd.push.post({
>         message:'Testing message',
>         devices:[query.device]
>     }, 
>     function(result, err){
>         console.log(result);
>     });
>   });

rather than receiving the Testing message as my payload (my client being an android device) , I receive this 

> D/MyFirebaseMsgService: Message data payload: {message=Test from Deployd}

Could you help me on this ?

**Comment by NicolasRitouet** [comment]
I'll close the ticket since it's old and the main issue has been solved
