### ISSUE TITLE
Deployd with Express error

### ISSUE THREAD

**Issue by FunnyDevs** [deployd/deployd#775]
Hi! I have followed the docs, but when i start the server, i get

> db:error Error: Cannot open store: MongoError: failed to connect to server [127.0.0.1:27017] on first connect
>     at C:\Users\Pierfrancesco\Desktop\hello\node_modules\deployd\lib\db.js:144:17
>     at connectCallback (C:\Users\Pierfrancesco\Desktop\hello\node_modules\deployd\node_modules\mongodb\lib\mongo_client.js:315:5)
>     at C:\Users\Pierfrancesco\Desktop\hello\node_modules\deployd\node_modules\mongodb\lib\mongo_client.js:222:11
>     at nextTickCallbackWith0Args (node.js:420:9)
>     at process._tickDomainCallback (node.js:390:13) +0ms
>   session:error Error removing old sessions: Database connection error +4ms

The server starts and express works well, but i am to able to get deployd data from db.
Which is the problem???

**Comment by andreialecu** [comment]
Did you download and install mongodb? https://www.mongodb.com/download-center

**Comment by FunnyDevs** [comment]
I have installed deployd with exe files. Then i have created a basic project and started it with "dpd -d". 
I was able to add data and to call services (so mongodb is installed).
Now i'm trying to add express to this project and i get this error.

**Comment by andreialecu** [comment]
`dpd -d` handles starting mongodb for you. If you want to use your own start script (as you should), mongo will not be started, so you need to ensure it is running as a service.

See http://stackoverflow.com/questions/2438055/how-to-run-mongodb-as-windows-service

**Comment by FunnyDevs** [comment]
ok, thanks a lot!
