### ISSUE TITLE
Change status code on empty JsonArray response

### ISSUE THREAD

**Issue by kkrishnan90** [deployd/deployd#781]
hi, 
Upon having certain empty responses as JSONArray output. How do I manipulate this to change the header and show me an error code ? Like for example : I have a usercollection, and want to check if the user while getting him through email viz. GET request (url : http://localhost:2403/users?email=kkrishnan90@gmail.com), I would like the response to show an error if this user is not already there in the Users collection. 

Could anyone help me out on this one ? Thanks in advance.

**Comment by houmark** [comment]
This is not a bug in deployd but a support request.

For general support from the community, see [StackOverflow](http://stackoverflow.com/questions/tagged/deployd) or visit the [ Deployd chat](gitter.im/deployd/deployd).

**Comment by andreialecu** [comment]
You'd need to make a wrapper using `dpd-event` with your own code which queries the collection and returns an error if needed. Use gitter or stackoverflow for further questions.
