### ISSUE TITLE
Is deployd under active development? 

### ISSUE THREAD

**Issue by Obsessive** [deployd/deployd#789]
I read this note but I'm still gonna go ahead. 
"NOTE: Only file GitHub issues for bugs and feature requests. All other topics will be closed."

I find deployd a very promising tool thats about 20% complete. I want to know what the status is with respect to the development and roadmap for deployd
Who are the contributors to this project?
What plans do we have in terms of features?
What are the plans for getting more community support..?
you get where I'm going.. 

If you're a developer going through this, do leave a reply. maybe we can collaborate and build things faster.
PS: We'd love to contribute

**Comment by rgolea** [comment]
@Obsessive you can read all about it in #761. You can also contribute by doing pull requests, test the new features, contribute with new ideas, etc. You can read all about contributing in the [CONTRIBUTING.md](https://github.com/deployd/deployd/blob/master/CONTRIBUTING.md) file.
