### ISSUE TITLE
IMPORT/EXPORT 

### ISSUE THREAD

**Issue by eshk12** [deployd/deployd#790]
Hey,
I'm looking for some tool that can export/import data without dealing with mongo?
there is such a thing?

**Comment by rgolea** [comment]
@eshk12 can you ellaborate on it?

**Comment by eshk12** [comment]
Hey,
I am trying to backup the collation in deployd.
that mean I'll get file on the collation type and data, same as export/import in phpmyadmin..

Create tables and inserts queries..

**Comment by rgolea** [comment]
You might want to use mongoexport/mongoimport (it's not deployd specific)

**Comment by eshk12** [comment]
I have read in the internet about this plugins but I have a problem:
http://stackoverflow.com/questions/41315103/export-local-deployds-data-into-a-online-server

I can't find the collation in robomongo interface as you can see on stackoverflow, Thx for your kind help!

**Comment by rgolea** [comment]
First of all, you might not want to use the built in mongodb. Use your own mongodb instance. You can use import/export with mongoimport and mongoexport (built in tools from mongodb). Here is a tutorial on how to set up your deployd server.

https://www.youtube.com/playlist?list=PLrceyQl0Cmplzid4tveBvYBzHOSot6vjk

If anything, feel free to comment on this issue. I will leave it open a couple of days. Please send us feedback if your question has been solved.

**Comment by eshk12** [comment]
Hey there, 
I have seen your video and it was really nice.
According to your video - 
I write `mongo` in the shell,
and then I wrote `show dbs`, and then I get only 1 DB called users
Picture:
![mongo2](https://cloud.githubusercontent.com/assets/20819854/21483880/59696924-cb92-11e6-86f4-ba1b843d81ab.png)

once you can see on the browser deployd dashboard is open and its on `Parabi` DataBase.
why isnt show in mongo?

THX!

**Comment by vinchauhan** [comment]
Add some data to the collections and then you should see the DB.

Thanks,
Vineet

**Comment by eshk12** [comment]
Thx,
on the online-server thats work,
but in my local-server I get this error while lunch mongo:
`Failed to connect to 127.0.0.1:27017 after 5000ms milliseconds, giving up.`

you know how to fix it?

**Comment by vinchauhan** [comment]
Make sure your mongo was started on local. What was the outcome of mongod..

**Comment by rgolea** [comment]
@eshk12 make sure the db you are pointing is a local one. As far as I can see, you are trying to connect to your centos machine. For that you have to open a port on your server for that mongo and point the connection string to that machine. The connection string should be something like: `mongodb://[username:password@][centosURL][:port]/[database][?options]`

You also might NOT want to connect directly to the live database. Try installing mongodb on your own machine and point your local project to the local server. You can do environment changes with [dotenv](https://www.npmjs.com/package/dotenv) which will allow to set environment variables depending the server you are on.

**Comment by eshk12** [comment]
Hey,
I am tring to connect to the local mongo.
I have reinstall mongoDB setup and uninstall and install again the npm packages `mongo,mongod,mongodb` and its still give me the same error,

`C:\Users\Itzik>mongo
MongoDB shell version v3.4.1
connecting to: mongodb://127.0.0.1:27017
2016-12-26T19:44:06.753+0200 W NETWORK  [main] Failed to connect to 127.0.0.1:27017 after 5000ms milliseconds, giving up.
2016-12-26T19:44:06.754+0200 E QUERY    [main] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:234:13
@(connect):1:6
exception: connect failed
`

I have tried to launch deployd, and its work.

**Comment by rgolea** [comment]
@eshk12  If you're launching from deployd (dpd cli) you are launching the deployd database. It's nothing related to deployd, it's related to mongodb. https://www.youtube.com/watch?v=vbxVuaw_ktw

**Comment by eshk12** [comment]
I manage to succssed install mongo, but I cant find that database the deployd used.
I am uploading a video.

**Comment by eshk12** [comment]
https://vimeo.com/197112004

**Comment by rgolea** [comment]
@eshk12 that database is run in another mongo instance. You can find in your project inside the `data` folder. Maybe try and copy-paste that data folder structure inside your localhost mongo instance (the folder you're saving your local instance data)

**Comment by rgolea** [comment]
If this doesn't work, you might want to export/import one time manually and later on just use mongoexport/mongoimport

**Comment by eshk12** [comment]
how do i do it manually which files do i need to copy?

**Comment by rgolea** [comment]
I just tried that solution and it didn't seem to work. Try getting all of your collections manually and use mongoimport on your localhost database

**Comment by rgolea** [comment]
https://docs.mongodb.com/manual/reference/program/mongoimport/

**Comment by eshk12** [comment]
OK,
In my VPS its work, but how can I all the collection include the collection column name, and values?

and how do I import it?
