### ISSUE TITLE
Request doc update on - Accessing Collections - Building a Custom Client

### ISSUE THREAD

**Issue by thbl** [deployd/deployd#791]
Hello

Would some one add an example to the 
http://docs.deployd.com/docs/collections/advanced-guides/

on how to auth with socket.io so we can use the
 " emit(dpd.users, {id: this.creatorId}, 'postModified', this);"
as i really need this for a project :)

**Comment by rgolea** [comment]
@thbl please be more specific?

**Comment by thbl** [comment]
hmmm  
how do i  build a custom client  "nodejs" like in the doc.
Listening to and emit events, as a user. Authenticating client, like the dpd.users.login.

So how to do a dpd.user.login -> socket.on....
In a nodejs client

@rgolea is this specific enough ? :)

**Comment by rgolea** [comment]
Oh! Clear now! Well, you can either do a automated process to keep it in sync and use dpd.js all the time. Alternatively you can use @andreialecu's [angular-dpd](https://github.com/andreialecu/angular-dpd) or you can build your own by doing http requests and socket.io calls and you can get the collections by calling the `__resources` endpoint. This have some security concerns but you can see how the dpd client lib was made right [here](https://github.com/deployd/deployd/tree/master/clib).

**Comment by NicolasRitouet** [comment]
Looks like it a bit out of scope for the documentation.
I'll close the ticket
