### ISSUE TITLE
export deployd's collection structure

### ISSUE THREAD

**Issue by eshk12** [deployd/deployd#792]
Hey,
I am looking for a way to export collection's struture.
![deployd](https://cloud.githubusercontent.com/assets/20819854/21494408/0751f66e-cc1a-11e6-9126-e0ad56ba7937.png)

I mean `name, price, amount, desc` and etc..
If this option already exists i'd like to know more about it.
and if this option is exists there is a way that I could include the collections's data inside the output backup file?

Thank You!

**Comment by hjanuschka** [comment]
@eshk12  what exactly do you wan't to do?
for backup i think its best practice to dump the mongo-db and also backup the whole DPD folder (especially the `resources/` folder)  - as there are the get/post... handlers, and also the `config.json`  - this is where the valid fields are stored.

**Comment by moorthi07** [comment]
If you are talking only about  'exporting collection structure' - it is available and manually editable at '/resources/mycollectionName/config.json '  - folder.

Your data backup is to be done in MongoDB.
Deployd collections definitions are part of your project structure and it gets backed up with rest of your code.

it looks like this, 
{
	"type": "Collection",
	"properties": {
		"add1": {
			"name": "add1",
			"type": "string",
			"typeLabel": "string",
			"required": false,
			"id": "add1",
			"order": 0
		},
		"add12": {
			"name": "add12",
			"type": "string",
			"typeLabel": "string",
			"required": false,
			"id": "add12",
			"order": 1
		},
		"city": {
			"name": "city",
			"type": "string",
			"typeLabel": "string",
			"required": false,
			"id": "city",
			"order": 2
		},
		"city2": {
			"name": "city2",
			"type": "string",
			"typeLabel": "string",
			"required": false,
			"id": "city",
			"order": 2
		}
	}
}

**Comment by andreialecu** [comment]
This is also available under the `/__resources` url, if you're logged in as a root user (dpd-ssh-key http header).
