### ISSUE TITLE
Deployd - Key is invalid when try access to dashboard

### ISSUE THREAD

**Issue by eshk12** [deployd/deployd#793]
I have an online server on centos that I have installed A Deployd. All goes well, and suddenly today I want to enter the dashboard to check something.

Deployd asked for a keygen that i can get it by using this command dpd showkey in shell. but when I insert the key I get a response that the key is invalid. So I have tried to generate a new key dpd keygen and this key is also isn't working.

I have read inside docs where is the key file is locate, so I go ~/.dpd/keys.json and all the keys are inside. I have tried remove this file and create new keygen.

But none works. Thanks!

**Comment by vinchauhan** [comment]
If you are still in development - you can run the server in development mode and it think it wont ask any key then.

**Comment by eshk12** [comment]
how can I do it?

**Comment by vinchauhan** [comment]
http://docs.deployd.com/docs/server/run-script.html

provide the environment as 'development' int he run script

**Comment by eshk12** [comment]
its still asking a keygen..

**Comment by rgolea** [comment]
Are you sure you have the `~/.dpd/keys.json` in your server? If you're pushing to Heroku or some git based platform and you have a `.gitignore` file where you are ignoring that key, you might not be actually pushing it.
