### ISSUE TITLE
Is Deployd Still Maintained/Supported/Active???

### ISSUE THREAD

**Issue by quadsurf** [deployd/deployd#794]
I was just about to start a new project with Deployd, but then I saw this: https://github.com/deployd/deployd/issues/408

It's now 2017... just wondering if Deployd is still moving forward with any momentum, and what new features are on the roadmap/horizon, if any. If no new features, is this project still being maintained?

But more importantly, **is it safe to use in production???**

**Comment by thbl** [comment]
have you looked at #761    ?

**Comment by NicolasRitouet** [comment]
The commit activity has dramatically decreased over the last few months for a good reason: critical bugs are rare. :v:
We have a bunch of volunteers ( @andreialecu , @rgolea, myself and a few others) working on improving the codebase.
Currently, we are working on skimming the core of deployd to make contributions easier and less risky.
We are removing the dashboard, the CLI and the client-lib from the core.
(you can start testing using `npm install deployd-cli -g` and give us some valuable feedback).

Regarding your production question, yes, a lot of people are currently using deployd on production.
Maybe someone could write an article about the best practices to run deployd on production.
Short answer is:
- don't run deployd using the cli, use a script (something similar to this: https://github.com/NicolasRitouet/deployd-express-demo/blob/master/server.js)
- don't run the dashboard on production
- if you really need the dashboard on production, make sure the key is activated (`NODE_ENV !== 'development'`)
- secure your endpoints (eg. https://github.com/deployd/deployd/blob/680393491bc304bd759b09f9ab807922a4cded50/test-app/resources/users/login.js)
- use other standard nodejs best practices

@deployd/developers anything else to add?

**Comment by rgolea** [comment]
If you need a starting point you can use this [tutorial](https://www.youtube.com/playlist?list=PLrceyQl0Cmplzid4tveBvYBzHOSot6vjk)

**Comment by coderofsalvation** [comment]
> But more importantly, is it safe to use in production???

I've been keeping an eye on deployd since its beginning, and use it in production.
It's fair to say it has reached a mature level of stability.

**Comment by amitsang2000** [comment]
Asking for apology in advance if I am putting this question in a wrong place.
There is an open issue [https://github.com/deployd/deployd/issues/333](url) with deployd-importer. It takes mongodb's object _id  as the id (of deployd). Its not taking the id generated by deployd. So after importing the collections are not getting updated.
Please help me.

**Comment by amitsang2000** [comment]
https://github.com/deployd/deployd/issues/333
This issue is still open. Please help.

**Comment by NicolasRitouet** [comment]
I closed the open ticket, thanks for pointing.
I recommend to create a ticket on the repo of dpd-importer directly:
https://github.com/deployd/dpd-importer
There doesn't seem to be a maintainer anymore for this module, maybe you could create a PR to fix the issue.

**Comment by amitsang2000** [comment]
There is one more issue. The automatically generated dpd.js is not generating the login function and me function.
The url for dpd.js is as follows:
[http://konnect.asia:5000/dpd.js](http://konnect.asia:5000/dpd.js)

**Comment by rgolea** [comment]
@amitsang2000 you shouldn't really use the dpd.js in production. Please add your issues in separate threads.

**Comment by amitsang2000** [comment]
Thanks a lot for your guidance.
I have opened a new issue here:
[https://github.com/deployd/deployd/issues/796](https://github.com/deployd/deployd/issues/796)
Apology in advance if i created it at a wrong place. I am new to github.
