### ISSUE TITLE
Deployd with CouchDB

### ISSUE THREAD

**Issue by itbeckham7** [deployd/deployd#797]
I am trying to build web API using Deployd with couchDB.
but Deployd is woriking with MongoDB.
I would like to know that how i can work with couchDB.
please tell me kindly if you know about it.

**Comment by rgolea** [comment]
@itbeckham7 no, it doesn't. But if you really want it, you can make a Pull Requests to add that feature.

**Comment by itbeckham7** [comment]
hello, rgolea.
could you tell me how to make a Pull Requests? please give me reference url.

**Comment by rgolea** [comment]
[Here](https://github.com/deployd/deployd/blob/master/CONTRIBUTING.md) you have a way where you could do that.
