### ISSUE TITLE
Search (text index) as in Mongo would be great 

### ISSUE THREAD

**Issue by retronoodle** [deployd/deployd#798]
I'll begin by saying - I'm new to Mongo, Deployd, JS on a server, Node, etc. I come from other web technology backgrounds. So please excuse my terminology on some of this. 

I know in Mongo you can make a text field indexed and then search it. I guess there is a `$text` search, and I've heard about this in general being discussed here in the community but with no real answers. 

It would be great if the deployed dashboard allowed you to mark a text field as indexed then run dpd querys that search it like `$text` if that makes sense. 

Maybe this is already possible? I just don't see it anywhere. It *seems* like most of the elements are in place and it would just be a matter of tying it all together. 

As it stands I can make an app where everyone has skills like 'php development' or 'nodejs development' but I can't find a way to search it, where say the user searches for just 'nodejs' - it wouldn't return that 'nodejs development' record. 

Thanks!

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Deployd Version (`deployd -V`):
* Node version (`node -v`):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by hjanuschka** [comment]
right now i think its supposed to only work with a little extra work.

create a resource e.g.: "people"
add field of type string `skills`, `firstname`, `lastname`.


create the mongo db index via mongo shell (keep in mind , right now mongo only supports one fulltext index):

```
db.people.createIndex( { skills: "text" } )
```



create a event resource,  using https://github.com/deployd/dpd-event


in the `GET` event do something like this:

```javascript
//get raw mongo collection of people resource
var datasource = dpd.people.getResource().store;
var search={
    $text: {$search: query.search}
}

scorer={
  firstname: 1,
  lastname: 1,
  _id: 1,
  textScore: {
    $meta: "textScore"
  }
}
sorter = {
    sort: {
      textScore: {
        $meta: "textScore"
      }
    }
  };


$addCallback();
datasource.getCollection().then(function(col) {
  col.find(search, scorer, sorter).toArray(function(err, docs) {
    setResult(docs);
    $finishCallback();
  })
});

```


than call it with `http://localhost:2403/your-event-resource?search=php`

**Comment by hjanuschka** [comment]
see https://code.tutsplus.com/tutorials/full-text-search-in-mongodb--cms-24835 for  a tutorial on how to use fulltext stuff.
