### ISSUE TITLE
POST request is pending

### ISSUE THREAD

**Issue by RilRil** [deployd/deployd#799]
* Deployd Version (`deployd -V`): 0.8.9
* Node version (`node -v`): 7.0.0
* Operating System and version: osx  10.11.6

Hello, 
I'm trying out Deployd, I'm using it as an express middleware and testing with Postman.
I send GET requests. It's working fine as I do receive my data.
But POST request keeps hanging... 
The headers Content-Type is set to application/json and the body is a simple json. The fields are not even required..

any idea ? 
Thanks !

**Comment by hjanuschka** [comment]
hmmm thats strange, can you share your your config.json + the event handler scripts from the affected resource?

also try to run it with `DEBUG=* node your_app.js`

**Comment by RilRil** [comment]
Thx for your help but I found the issue and it was due to a middleware (bodyParser) I use which blocked the request.
if you place this :
`app.use(bodyParser.json());`
before 
`app.use(this._httpService.handleRequest);`
it's not working.

**Comment by rgolea** [comment]
That is because you didn't bind the handleRequest. You should do something like:
```
app.use(this._httpService.handleRequest.bind(this._httpService));
```
