### ISSUE TITLE
Installing Modules Don't Show In Dashboard

### ISSUE THREAD

**Issue by indiecore-fm** [deployd/deployd#803]
## Context

Whenever I use npm install dpd-passport (or any module) it will install, but it won't show in dashboard.

Even creating a package.json and using the --save flag doesn't help.

## Expected Behavior

Install a module and it shows in dashboard

## Actual Behavior

Install a module and nothing

## Steps to Reproduce

1. Fresh Install of Deployd
2. Install module
3. start dpd
4. module never added to dashboard

## Context

Can't go any further.

## Your Environment

* Deployd Version (`deployd -V`):  0.8.9
* Node version (`node -v`): 6.9.5
* Server type and version: 
* Operating System and version: Windows 10
* Link to your project:

Also someone just posted on the google group with the same issue yesterday.

**Comment by rgolea** [comment]
You need to have deployd installed in your project. Please follow the following tutorial.
https://www.youtube.com/playlist?list=PLrceyQl0Cmplzid4tveBvYBzHOSot6vjk

If this is still an issue, please feel free to reopen this issue.

**Comment by indiecore-fm** [comment]
I created a project using the cli? Following thr exact instructions on the
site. If that's not right, then they should be updated as that's confusing

**Comment by rgolea** [comment]
@indiecore-fm we are not too many people that maintain this project. We will do an update as soon as the final separation for the modules is done.
See #761

**Comment by indiecore-fm** [comment]
This is what fixed the issue btw.

Creating a server.js and including this:

`var deployd = require('deployd');`

That should be noted or at least created when someone runs

dpd create hello-world
cd hello-world
dpd -d.

Thanks for the point in the right direction @rgolea

**Comment by geocine** [comment]
@indicore-fm any idea why this is not working. I had hopes with your solution. This is my current structure

![directory](http://i.imgur.com/ydkMEmV.png)

**Comment by geocine** [comment]
I followed @rgolea advice and it is working without the `server.js` . Thanks!
