### ISSUE TITLE
Authentication With Websockets

### ISSUE THREAD

**Issue by p3nt4** [deployd/deployd#804]
Hi, has everyone ever implemented authentication with web sockets and deployd? 

I would like to restrict the 'emit' recipients to authenticated users.

Thanks

**Comment by p3nt4** [comment]
My bad, it's in the docs.... Sorry.

**Comment by kkrishnan90** [comment]
Hi @p3nt4 .. just wanted to know how did you resolve this ? I'm trying to emit my message to a particular group of users separated based on their departments. I'm not able to get the doc method to work.. any solutions from your side is much appreciated..

**Comment by andreialecu** [comment]
@kkrishnan90 Like other things that were recently changed, this is unfortunately not well documented.

You have to emit this from your client on the socket:
`socket.emit('server:setsession', { sid: .... });` 

Where sid is the session id you got while logging in.

**Comment by andreialecu** [comment]
See this test for additional clues: https://github.com/deployd/deployd/blob/master/test/sessions.unit.js#L490

**Comment by kkrishnan90** [comment]
Great thanks.but could you please help me for my scenario. I've been a loyal user of deployd for about a year now. Normal chat works like charm. But when I want to emit my chat messages to a bunch of users who belong to a particular category. What's to be on the server side and the client side. Is there any change in documentation .. I tried the ```emit(dpd.users,{id:this.id},'message', this);```
But this doesn't seem to work at all.. could you pls help me out.

**Comment by andreialecu** [comment]
@kkrishnan90 `emitToUsers` is not really efficient since it does queries all the time. 

You should use the (poorly documented) room functionality described here: https://github.com/deployd/deployd/pull/698#issuecomment-166901474 

If you use this and set the session id properly on the websocket, everything should work for you.

Let me know if you have problems.

**Comment by kkrishnan90** [comment]
Hi.. the newly documented session id in socket payload and I even tried emit to roomname and event with data payload doesn't work at all. My data gets posted whereas the socket emit doesn't work at all.. 
As suggested by you, I have connected the socket in the client and sent the sessionid payload initially before sending the actual socket event. And on the server (dashboard) side, I included ```session.joinRoom('roomname')``` in ```OnLogin``` and used 
```emit('roomname', 'eventname',data)``` in my collection ```OnPost``` .. this doesn't work at all. Tried all different combinations too..

**Comment by kkrishnan90** [comment]
I've been tearing my hair out on this for the past 1 week .. still no luck.. pls help me out as I've suggested deployd considering its ease of use to all my other clients too..

**Comment by andreialecu** [comment]
@kkrishnan90 PM me on gitter and I'll try to help you there

**Comment by kkrishnan90** [comment]
@andreialecu PM'd you on gitter with all relevant codes and background and my tries so far. Please help me out.

**Comment by andreialecu** [comment]
Got this sorted out for @kkrishnan90 

The issue wasn't related to deployd but due to a custom client side socket.io implementation creating multiple socket instances on the client instead of reusing a single one. And minor other initialization issues.

So, deployd is working properly here 😆

**Comment by kkrishnan90** [comment]
Thank you so much @andrie... Really appreciate your efforts in solving problem. Yes that was a mistake in my code..
