### ISSUE TITLE
Potential fix for "upstream prematurely closed connection" errors when using socket.io in deployd with nginx

### ISSUE THREAD

**Issue by vpxavier** [deployd/deployd#808]
## Context

When using socket.io and Nginx (latest version up-to-date) as reverse proxy, nginx's error log shows a lot of errors like "upstream prematurely closed connection while reading response header from upstream". Detail of this error can be found here: https://github.com/socketio/engine.io/issues/458

## Expected Behavior

No errors in nginx's logs
## Actual Behavior

nginx's error log shows a lot of errors like "upstream prematurely closed connection while reading response header from upstream"
## Possible Fix

Update engine.io to version 1.8.2 or higher which seems to include a fix for this (see here https://github.com/socketio/engine.io/issues/458)

## Steps to Reproduce

1.  Install deployd and use socket.io
2. Install Nginx as reverse proxy
3.
4.

## Context

Nginx shows a lot of errors.

## Your Environment

* Deployd Version (`deployd -V`): 0.8.9
* Node version (`node -v`): 6.10.2
* Server type and version: 
* Operating System and version: Ubuntu 16.04
* Link to your project:

**Comment by rgolea** [comment]
Have you tried this?
https://socket.io/docs/using-multiple-nodes/
