### ISSUE TITLE
Collection Events

### ISSUE THREAD

**Issue by ritch** [deployd/deployd#81]
Collection events besides `get` should be opt-in and `get` should be able to be opted out of. Opt in will also mean the underlying behavior will be disabled for external users unless an event exists. For example, clients would not be able to delete an object unless the `on get` event was created.

This also means we can support a larger number of events that expose new hooks. Here are some that I would like to see:

 - `before get` - includes the user, the query object, and allows users to filter queries before running the get event on each individual object
 - `save` - fired when a object is created or updated
 - `changed` - only fired when an objects values have changed
 - `after save` - fired after the transaction was committed fully to the database
 - `calculate` - fired when the dependencies of the calculate event change

**Comment by andreialecu** [comment]
BeforeRequest was added in https://github.com/deployd/deployd/pull/596
AfterCommit was added in https://github.com/deployd/deployd/pull/555

The rest don't seem to apply any more, or can be implemented in code inside of On POST/On PUT.
