### ISSUE TITLE
middleware folder for custom codes / .js files 

### ISSUE THREAD

**Issue by moorthi07** [deployd/deployd#815]
Can we have the custom middleware code files under a 

> **/middleware**

 folder (not inside /nodemodules) and get access from resource events? It helps a great way to maintain and separate custom code from node packages, 

Right now all code should be placed inside **/nodemodules** for deployd to load.

**Comment by armand1m** [comment]
I'm in search for a way to modify and insert headers into deployd responses, and find no way of doing it. This could help implementing this kind of feature?

**Comment by andreialecu** [comment]
@armand1m there is an undocumented way to manage headers:

get: 
`let res = ctx.req.headers["if-none-match"]`

set:
`ctx.res.setHeader('X-Session-Token', sess.id);`

**Comment by andreialecu** [comment]
@moorthi07 you can `require('../../middleware/yourfile')` from any event script.

I'm working on a better way to do this though.

**Comment by moorthi07** [comment]
@andreialecu yes. documenting the same. Looking forward for any other approach, that would put all the middleware code in one place like : middleware\resources , middleware\customfolders.  Or  middleware files inside /Resources - since /Resources is a mandatory folder.  Some best practice would be cool. Thanks.

**Comment by andreialecu** [comment]
Ok, the better way to do this is via `dpd-codemodule` which I published on npm.

Also available here: https://github.com/andreialecu/dpd-codemodule

**Comment by kkrishnan90** [comment]
@andrie should I get and set headers directly from the events on my dashboard ? I would like to activate some custom headers like X-TOTAL-COUNT header.. any help on this is much appreciated

**Comment by armand1m** [comment]
Hey @kkrishnan90, I've got the same need as you sometime ago. The answer of @andreialecu helped me a lot through this issue.

I've needed to configure a Content-Range header.

I've created a `createContentRange.js` helper:

```js
module.exports = function createContentRange(resourceName, results) {
    const { length } = results;

    const contentRange = resourceName
        .concat(' 0-')
        .concat(length)
        .concat('/')
        .concat(length);

    return contentRange;
};
```

In my BeforeRequest Event, I've got this code:

```js
const createContentRange= require('../../../helpers/create-content-range');

const resource = 'instructor';

ctx.res.setHeader('Access-Control-Expose-Headers', 'Content-Range');
ctx.res.setHeader('Content-Range', createContentRange(resource, []));
```

And in my Get Event code i've got:

```js
const createContentRange = require('../../../helpers/create-content-range');

const resource = 'instructor';

dpd[resource].get(function(results, error) {
    if (error) {
        return;
    }

    ctx.res.setHeader('Content-Range', createContentRange(resource, results));
});
```

Indeed, this is not a real pagination code, but it's somewhere a way to get there.

**Comment by andreialecu** [comment]
@armand1m: take a look at [dpd-codemodule](https://github.com/andreialecu/dpd-codemodule), it should also simplify the implementation for you a bit.

Closing this since it should now be resolved.
