### ISSUE TITLE
Unable to form a relationship on post

### ISSUE THREAD

**Issue by madd86** [deployd/deployd#827]
# Edit:

Collections:

* **Posts** {name: string, date: number, comments: array}

* **Comments** {comment: string, post: string}

Since I posted this, I modified a few things, Here's the code now (ON POST EVENT of COMMENTS):

```
dpd.posts.put({id: this.post}, {comments: [this.id]}, function(result, err) {
  if (err) cancel(err);
});
```

It does work, but the problem is that I'm modifying the post field (which is an array). I don't want to replace whatever's there, I want to add a new array in that field.

**Comment by madd86** [comment]
Solved it.

Here's the working code.

```
dpd.posts.put({id: this.post}, {comments: {$push: this.id}}, function(result, err) {
  if (err) cancel(err);
});
```

**Comment by moorthi07** [comment]
Great . Thanks @madd86 for sharing
