### ISSUE TITLE
GTM not working ! can't find ressource file

### ISSUE THREAD

**Issue by kamedan** [deployd/deployd#829]
i installed the plugin, firebase works fine but GTM not working, in logs it tells me cannot find ressource file GT-xxxxx.json file

**Comment by moorthi07** [comment]
We have a problem with Resource's folder names and files - naming convention. It has to be lowercase. Can you check your inside your resource folder collection name is correct?

**Comment by andreialecu** [comment]
What is plugin, what is GTM, and what does this have to do with deployd?
