### ISSUE TITLE
Setting session variable for in memory. (not using sessionstore)

### ISSUE THREAD

**Issue by moorthi07** [deployd/deployd#836]
Sessions document shows this example,
var session = new Session({id: 'my-sid', new SessionStore('sessions', db)});
session.set({uid: 'my-uid'}).save();

As mentioned in doc, 
'An in-memory representation of a client or user connection that can be saved to disk. '
Can you use session without SessionStore.  Some thing like,
var session = new Session();
session.set({uid: 'my-uid'});

**Comment by andreialecu** [comment]
What is this issue about?

**Comment by moorthi07** [comment]
Can we just use  .
var session = new Session();
not specifying a database to store.

**Comment by andreialecu** [comment]
Not sure why you need to create new sessions? There is already a `session` variable exposed to scripts.

You should be able to set arbitrary data on the current `session` using `session.set({key: value}).save();`

**Comment by moorthi07** [comment]
Yes. Then this need to be clear in the document. There are too much mix between developing custom dpd modules vs using simple collection events and available dpd syntax for those events. This need to be distinct in the document for starters. Thats just my thoughts.

**Comment by andreialecu** [comment]
The documentation is severely outdated at this point. If someone wants to take care of updating it, let me know and I'll help point to what changed and what the new practices are.
