### ISSUE TITLE
On Get (/users) returns all users data instead current user. Can we filter by me.id

### ISSUE THREAD

**Issue by moorthi07** [deployd/deployd#838]
A get query like,
/users or /posts  return results of all users, where as it should only return data of  currently logged in user.
How to restrict the above get query from mistakenly called  by spammers .
/posts should return  result of  '/posts?uid=123123'. 

Do we have any builtin restrictions to secure the "/collection" call  to the loggedin user's id.

Currently I only see some thing like below,
if (!me || query.id !== this.creatorId) { 
}

**Comment by cristianfd** [comment]
You need to write your own query in your collection (
http://docs.deployd.com/docs/collections/reference/dpd-js.html#s-.get([id],
[query], fn)-1286)

**Comment by andreialecu** [comment]
In `On BeforeRequest`: 

```javascript
if (event == 'GET') {
   query = query || {};
   query.uid = me.id;
}
```
