### ISSUE TITLE
Additional custom headers in response

### ISSUE THREAD

**Issue by kkrishnan90** [deployd/deployd#840]
I am planning to go for an admin dashboard for one of my clients app. I used deployd to generate my rest APIs. I use ngx-admin for my admin panel generation. When I query for list of users in my collection, it asks for X-Total-Count header in the response. However I don't get this header in my response when I hit the GET request API end point. Any suggestions to activate this header or include any custom headers.. ? Thanks in advance.

**Comment by andreialecu** [comment]
`Count`ing things is not directly supported by deployd.

The way I do this in my projects is to move the querying logic inside `dpd-event`s and do two queries. The count query, for efficiency, should use the MongoDB `.count()` function.

You can get to the `.count()` by going straight to the raw mongodb api, via functionality described in this PR: https://github.com/deployd/deployd/pull/608

**Comment by kkrishnan90** [comment]
Ok .. thanks.. but can I add them as a response header ? If so how do I do that ?

**Comment by andreialecu** [comment]
`ctx.res.setHeader(....)` https://nodejs.org/api/http.html#http_response_setheader_name_value
