### ISSUE TITLE
Get.js is not executed if 'there is no data in the collection'

### ISSUE THREAD

**Issue by moorthi07** [deployd/deployd#842]
Get.js is not executed if 'there is no data in the collection'

>resource: test
> get.js
> console.log('test11'); 
> var a = 10;
> console.log('total', a*2);

localhost:2403/test  returns []. But server console is not printing the above output.

**Comment by andreialecu** [comment]
This is by design, get is executed for every returned document.

**Comment by moorthi07** [comment]
But this is not the case for other Nodejs frameworks and other languages, right? Do you think we have to fix it to meet the standard?!

**Comment by andreialecu** [comment]
You have `On BeforeRequest`, which will be executed once for the whole result set. `On GET` will run once for every returned document, and exactly zero times for no results. :)

**Comment by moorthi07** [comment]
I agree 'On BeforeRequest' - some thing cute and could take care of many of these issues.
