### ISSUE TITLE
dpd emit repeat the emit function call

### ISSUE THREAD

**Issue by herOwOw** [deployd/deployd#855]
Hey , i don't know if this is a bug or something goes wrong but here the problem,
i have a collection called Event and in Deployd's dashboard , on post's event of event collection have just this,

` if(!me) cancel("You are not authorized", 401);
  emit('EventCreated', this);
`
and on event's list page i'm just console.log the item that being inserted in vuejs mounted function like so:

`
//the problem is , the event inserted console Logged many times , i already changed the dpd 'on' to 'once' its became worst it print the single item many times then the on fn did
  dpd.on('EventCreated', function( event ) {
   console.log( event );
}
` 
i have this conf:
Node: 8.9.1
Deployd version: 2.0.2
and vuejs with Browserify + vueify

**Comment by moorthi07** [comment]
May be you are posting multiple times on a socket event . Pl. share a gist with more code to take a look.

**Comment by herOwOw** [comment]
@moorthi07  thx for yr help while i was gisting the files suddenly  i found that i've duplicated my code 2 times on created and mounted , i am so exhausted that i couldn't even see the duplicated code..

**Comment by moeinrahimi** [comment]
how do you use dpd on vuejs ? I'm using vue with webpack

**Comment by moorthi07** [comment]
Different topic. Pl. discuss in gitter. Post issues here. Thx. 
FYI: if you are asking **dpd.js**  , you need  to write a wrapper for dpd.js on your own for other frameworks like react, angularjs, typescript , vue.  But, you can simply do a http ajax call to your end point (dpd.js is nothing more as you can read in the document).
