### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [deployd/deployd#858]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by andreialecu** [comment]
deployd itself doesn't use ejs. There is a dependency that is using it, but it's only for error messages. 

That dependency itself is marked to be removed. Tracking here: https://github.com/deployd/deployd/issues/856

**Comment by moorthi07** [comment]
@andreialecu  deployd does use ejs for dashboard.

@Drulac - fyi: this is the power of ejs. Its not just interpolate. Benchmark is not  comparing apple to apple.
ejs.renderFile(
          **srcfile**, string,  
          {},
          function (err, str) {
            if (err) throw err;   
            console.log('model.entityname', string, file) 
          });
