### ISSUE TITLE
how to count collection and append it to body

### ISSUE THREAD

**Issue by moeinrahimi** [deployd/deployd#861]
so i can get a collection count by using 

dpd.posts.getResource().store.getCollection().then(function(col) {
    var counts = col.count()    
});    
how can i append counts to body response ?

**Comment by andreialecu** [comment]
If you put this inside a `dpd-event`, just call `setResult({items: myItems, count: myCount})`. 

See http://npmjs.com/package/dpd-event

**Comment by moeinrahimi** [comment]
so i put my in the on get event i create with dpd-event and what, every request to deployd goes to that event first ?

**Comment by moeinrahimi** [comment]
@andreialecu  ok now i get it, custom events created with dpd-event have their own route right ? and also this is not working 

``` javascript
dpd.posts.getResource().store.getCollection().then(function(col) {
   var counts = col.count()
  setResult({ countscounts})

  });

```
i'm not sure it's because the code is promise base or anything else

**Comment by moeinrahimi** [comment]
i got it working like this, is this approach right ?
let data = this 
dpd.posts.get(query,function(posts,error){
  console.log(error,'got an error')
  data.posts = posts 
})
dpd.posts.getResource().store.getCollection().then(async function(col) {
  var count = await col.count()  
  setResult({ count: count,posts:data}) 
});

**Comment by moeinrahimi** [comment]
i got it working like this, is this approach right ?
```
let data = this 
dpd.posts.get(query,function(posts,error){
  console.log(error,'got an error')
  data.posts = posts 
})
dpd.posts.getResource().store.getCollection().then(async function(col) {
  var count = await col.count()  
  setResult({ count: count,posts:data}) 
});
there is only one issue here, my json is a posts that has an array called posts inside posts there is my data how can i remove second posts ?
```
