### ISSUE TITLE
query operators / filters not working : http://localhost:2404/address?{$fields: {city: 0} } 

### ISSUE THREAD

**Issue by moorthi07** [deployd/deployd#862]
`http://localhost:2404/address?{$fields: {city: 0} } `
 is not working as oppose to ,
`dpd.address.get({$fields: {city: 1} },console.log) `
which is working.

error:
HTTP/1.1 400 Bad Request
Content-Type: text/plain
Date: Thu, 15 Feb 2018 07:29:55 GMT
Connection: keep-alive
Content-Length: 82

Failed to parse querystring: SyntaxError: Unexpected token $ in JSON at position 1

Is this in the document wrong? [http://docs.deployd.com/docs/collections/reference/querying-collections.html](http://docs.deployd.com/docs/collections/reference/querying-collections.html)
When using an advanced query in REST, you must pass JSON as the query string, for example:

GET /posts?{"likes": {"$gt": 10}}

**Comment by rgolea** [comment]
The problem you have is parsing the url.
Steps to encode properly:
```
npm install -S qs
```
Then go in your code and do
```
const qs = require('qs');
const query = {$fields: {city: 0}};
request.get(`/address?${qs.stringify(query)}`);
```

**Comment by andreialecu** [comment]
You don't need qs, but your query is not valid json. you forgot the quotes:

`http://localhost:2404/address?{"$fields": {"city": 0} }`
