### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by pradeepgokul** [deployd/deployd#863]
dpd.users.put("af1c1a3a53a81aea",{password: "Pradeep"}); 
or
dpd.users.put("af1c1a3a53a81aea",{firstName: "Pradeep"});

Throws an error of **422 Unprocessable Entity**. Is there any other way to update user date by making API calls?

**Comment by rgolea** [comment]
You need to pass in the username any time you want to modify a user type

**Comment by pradeepgokul** [comment]
yes, passing the uid solved it, now I'm facing a problem where the password is not getting updated I'm not sure why, but I'm not getting any errors also. Any thoughts on that?

**Comment by whitehorse0** [comment]
i have same problem in here, have you got the solution? @pradeepgokul & @rgolea 

thanks
