### ISSUE TITLE
express middleware access to `process`

### ISSUE THREAD

**Issue by j3ko** [deployd/deployd#865]
## Context

After following http://docs.deployd.com/docs/server/work-with-express.html and installing deployd as express middleware, the event scripts no longer have access to the nodejs `process` global.

## Expected Behavior

in some arbitrary get.js, put.js, post.js, etc. file the following should execute properly 

`var key = process.env['SOME_KEY'] // key should be set properly`
`var cwd = process.cwd() // cwd should be set properly`

## Actual Behavior

`var key = process.env['SOME_KEY']`

throws: "Cannot read property 'SOME_KEY' of undefined"

`var cwd = process.cwd()`

throws: "process.cwd is not a function"

## Steps to Reproduce

1. follow http://docs.deployd.com/docs/server/work-with-express.html
2. in some event call `var cwd = process.cwd()`

## Your Environment

* Deployd Version (`deployd -V`): 1.1.2
* Node version (`node -v`): 8.1.3

**Comment by rgolea** [comment]
Hey! You have to use `process()`.
