### ISSUE TITLE
Move dpd created app to work with express. 

### ISSUE THREAD

**Issue by PaulMaly** [deployd/deployd#877]
Hi! I've created an app using dpd cli, but now I found I need to make it a part of express driven app. 

I read [those docs](http://docs.deployd.com/docs/server/work-with-express.html) but not sure how to connect to existing db collections created by dpd cli. 

Anyone can help me?

**Comment by andreialecu** [comment]
Just set up the connection string to your database and if you're starting a new repository, make sure to copy over the `resources` directory from your initial deployd setup.

**Comment by PaulMaly** [comment]
@andreialecu Thanks for the advise, but where I need to find a db credentials for my current deployd app?

**Comment by andreialecu** [comment]
If you use the dpd cli, it starts its own mongo instance which uses the `data` folder under your own app. This is only meant for development. 

See the mongo documentation on how to set up mongo system-wide, and provide that connection string to deployd. Usually there's an installer you can use, or there's already a MongoDB Windows Service that should be running on the default mongo port.

**Comment by PaulMaly** [comment]
@andreialecu Sure, I know how to setup MongoDB, but I already created a few collections and code in events. How to migrate all these things to new mongo instance?

**Comment by andreialecu** [comment]
You don't need to do anything. They are not created in mongo. The first time you save something to a collection it will create the collection in mongo. So you can just switch the server.

**Comment by PaulMaly** [comment]
Awesome, that's what I missed. Thanks!

**Comment by moorthi07** [comment]
@andreialecu can we have express routing still work  while attached to dpd?

**Comment by PaulMaly** [comment]
@moorthi07 I believe it should work, otherwise not much sense to use deployd with express, right?
