### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by PaulMaly** [deployd/deployd#879]
Hi! I try to use deployd as an API for another server. How can I manage authorization in this case? Afaik, deployd uses browser cookies to set authorization but seems it won't work with this case, right?

**Comment by andreialecu** [comment]
You can use an `Authorization: Bearer <sid>` HTTP header. `sid` is the session id, which you get as the response of the `login` REST call.

**Comment by andreialecu** [comment]
Some more information here: https://github.com/deployd/deployd/pull/521

**Comment by PaulMaly** [comment]
Ok, thanks!
