### ISSUE TITLE
dpd Failed to start MongoDB

### ISSUE THREAD

**Issue by Christophedlr** [deployd/deployd#882]
* Deployd Version (`deployd -V`): 2.0.2
* Node version (`node -v`): 12.16.1
* Operating System and version: Windows 10 1909 (18363.720)

Hello,

I'm fresh install deployd, node, typescript and mongodb in Windows 10. After launch **dpd** or **dpd -d**, the command return :

`D:\data\prog\learning\TypeScript\todolist\todos>dpd
deployd CLI version 2.0.2
starting deployd
Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deployd.com/docs/basics/cli.html)`

mongod.exe is located in : C:\Program Files\MongoDB\Server\4.2\bin
But, after launch command : dpd -m "C:\Program Files\MongoDB\Server\4.2\bin\mongod.exe" :
`D:\data\prog\learning\TypeScript\todolist\todos>dpd -m "C:\Program Files\MongoDB\Server\4.2\bin\mongod.exe"
deployd CLI version 2.0.2
starting deployd
Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deployd.com/docs/basics/cli.html)`

A dpd error and directory screenshots are joined.

![dpd_error](https://user-images.githubusercontent.com/994442/77894844-2a52d380-7276-11ea-8793-5c249fbd4e0d.png)
![mongod](https://user-images.githubusercontent.com/994442/77894850-2b840080-7276-11ea-86ae-d3ea22f9222c.png)

**Comment by rgolea** [comment]
You can use this in order to start your server: http://docs.deployd.com/docs/server/as-a-node-module.html. As for the cli I believe it's not been maintained.

**Comment by mistrydhruti** [comment]
After creating dpd project 
cd to project directory then
dpd --host "127.0.0.1" -P '27017' -n "mongodb" -u " " -s " "
it should work
