### ISSUE TITLE
/resources/**/config.json is required on a empty installation

### ISSUE THREAD

**Issue by jrichardsz** [deployd/deployd#883]
## Context

Start a fresh installation
## Expected Behavior

Run with a clean log
## Actual Behavior

Error or warnings in console

```
{ ENV: 'development', PORT: 2403 }
ls: no such file or directory: /../resources/**/config.json
ls: no such file or directory: /../resources/**/config.json
```

## Possible Fix

Detect if resources folder are empty before search **/config.json
## Steps to Reproduce

1.Start a fresh installation
2.npm run start
3. go to http://localhost:2403/dashboard/
4. log show several repetitive errors

## Your Environment

* Deployd Version (`deployd -V`): 1.2.0
* Node version (`node -v`): v8.11.2
* Server type and version: express
* Operating System and version: ubuntu
* Link to your project: comming soon

**Comment by rgolea** [comment]
I think you could just add a `resources` folder. That's the only real requirement on a fresh installation.
